load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "consumer",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    importpath = "go.atoms.co/splitter/pkg/service/consumer",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/core",
        "//pkg/model",
        "//pkg/service/coordinator",
        "//pkg/service/worker",
        "//proto/atoms/splitter/private:private_go_proto",
        "@co_atoms_go_iox//:iox",
        "@co_atoms_go_lib//chanx",
        "@co_atoms_go_lib//contextx",
        "@co_atoms_go_lib//log",
        "@co_atoms_go_lib//net/grpcx",
        "@co_atoms_go_lib_net_location//go/location",
        "@co_atoms_go_lib_net_session//go/session",
    ],
)
