// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/lib/service/location/location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_atoms_splitter_lib_service_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Location) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_atoms_splitter_lib_service_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Instance) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_atoms_splitter_lib_service_location_location_proto protoreflect.FileDescriptor

const file_atoms_splitter_lib_service_location_location_proto_rawDesc = "" +
	"\n" +
	"2atoms/splitter/lib/service/location/location.proto\x12#atoms.splitter.lib.service.location\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\bLocation\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"\xaf\x01\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12I\n" +
	"\blocation\x18\x02 \x01(\v2-.atoms.splitter.lib.service.location.LocationR\blocation\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04nameB0P\x01Z,go.atoms.co/splitter/lib/service/location/pbb\x06proto3"

var (
	file_atoms_splitter_lib_service_location_location_proto_rawDescOnce sync.Once
	file_atoms_splitter_lib_service_location_location_proto_rawDescData []byte
)

func file_atoms_splitter_lib_service_location_location_proto_rawDescGZIP() []byte {
	file_atoms_splitter_lib_service_location_location_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_lib_service_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_lib_service_location_location_proto_rawDesc), len(file_atoms_splitter_lib_service_location_location_proto_rawDesc)))
	})
	return file_atoms_splitter_lib_service_location_location_proto_rawDescData
}

var file_atoms_splitter_lib_service_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_atoms_splitter_lib_service_location_location_proto_goTypes = []any{
	(*Location)(nil),              // 0: atoms.splitter.lib.service.location.Location
	(*Instance)(nil),              // 1: atoms.splitter.lib.service.location.Instance
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_atoms_splitter_lib_service_location_location_proto_depIdxs = []int32{
	0, // 0: atoms.splitter.lib.service.location.Instance.location:type_name -> atoms.splitter.lib.service.location.Location
	2, // 1: atoms.splitter.lib.service.location.Instance.created:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_atoms_splitter_lib_service_location_location_proto_init() }
func file_atoms_splitter_lib_service_location_location_proto_init() {
	if File_atoms_splitter_lib_service_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_lib_service_location_location_proto_rawDesc), len(file_atoms_splitter_lib_service_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_lib_service_location_location_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_lib_service_location_location_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_lib_service_location_location_proto_msgTypes,
	}.Build()
	File_atoms_splitter_lib_service_location_location_proto = out.File
	file_atoms_splitter_lib_service_location_location_proto_goTypes = nil
	file_atoms_splitter_lib_service_location_location_proto_depIdxs = nil
}
