load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "logging",
    srcs = glob(["*.go"]),
    importpath = "go.atoms.co/splitter/pkg/util/logging",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/service/location",
        "//pkg/allocation",
        "//proto/atoms/splitter:splitter_go_proto",
        "@co_atoms_go_lib//log",
        "@co_atoms_go_slicex//:slicex",
        "@com_github_google_uuid//:uuid",
    ],
)
