// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/cluster.proto

package private

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNotifyRequest) Reset() {
	*x = ClusterNotifyRequest{}
	mi := &file_atoms_splitter_private_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNotifyRequest) ProtoMessage() {}

func (x *ClusterNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNotifyRequest.ProtoReflect.Descriptor instead.
func (*ClusterNotifyRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterNotifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterNotifyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ClusterNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNotifyResponse) Reset() {
	*x = ClusterNotifyResponse{}
	mi := &file_atoms_splitter_private_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNotifyResponse) ProtoMessage() {}

func (x *ClusterNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNotifyResponse.ProtoReflect.Descriptor instead.
func (*ClusterNotifyResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_cluster_proto_rawDescGZIP(), []int{1}
}

var File_atoms_splitter_private_cluster_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_cluster_proto_rawDesc = "" +
	"\n" +
	"$atoms/splitter/private/cluster.proto\x12\x16atoms.splitter.private\"@\n" +
	"\x14ClusterNotifyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x17\n" +
	"\x15ClusterNotifyResponse2w\n" +
	"\x0eClusterService\x12e\n" +
	"\x06Notify\x12,.atoms.splitter.private.ClusterNotifyRequest\x1a-.atoms.splitter.private.ClusterNotifyResponseB!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_cluster_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_cluster_proto_rawDescData []byte
)

func file_atoms_splitter_private_cluster_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_cluster_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_cluster_proto_rawDesc), len(file_atoms_splitter_private_cluster_proto_rawDesc)))
	})
	return file_atoms_splitter_private_cluster_proto_rawDescData
}

var file_atoms_splitter_private_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_atoms_splitter_private_cluster_proto_goTypes = []any{
	(*ClusterNotifyRequest)(nil),  // 0: atoms.splitter.private.ClusterNotifyRequest
	(*ClusterNotifyResponse)(nil), // 1: atoms.splitter.private.ClusterNotifyResponse
}
var file_atoms_splitter_private_cluster_proto_depIdxs = []int32{
	0, // 0: atoms.splitter.private.ClusterService.Notify:input_type -> atoms.splitter.private.ClusterNotifyRequest
	1, // 1: atoms.splitter.private.ClusterService.Notify:output_type -> atoms.splitter.private.ClusterNotifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_cluster_proto_init() }
func file_atoms_splitter_private_cluster_proto_init() {
	if File_atoms_splitter_private_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_cluster_proto_rawDesc), len(file_atoms_splitter_private_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_private_cluster_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_cluster_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_private_cluster_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_cluster_proto = out.File
	file_atoms_splitter_private_cluster_proto_goTypes = nil
	file_atoms_splitter_private_cluster_proto_depIdxs = nil
}
