// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: atoms/splitter/private/coordinator.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_Connect_FullMethodName = "/atoms.splitter.private.CoordinatorService/Connect"
	CoordinatorService_Handle_FullMethodName  = "/atoms.splitter.private.CoordinatorService/Handle"
	CoordinatorService_Observe_FullMethodName = "/atoms.splitter.private.CoordinatorService/Observe"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectMessage, ConnectMessage], error)
	Handle(ctx context.Context, in *CoordinatorHandleRequest, opts ...grpc.CallOption) (*CoordinatorHandleResponse, error)
	Observe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ObserverClientMessage, ObserverServerMessage], error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectMessage, ConnectMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[0], CoordinatorService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectMessage, ConnectMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_ConnectClient = grpc.BidiStreamingClient[ConnectMessage, ConnectMessage]

func (c *coordinatorServiceClient) Handle(ctx context.Context, in *CoordinatorHandleRequest, opts ...grpc.CallOption) (*CoordinatorHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorHandleResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Observe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ObserverClientMessage, ObserverServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[1], CoordinatorService_Observe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserverClientMessage, ObserverServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_ObserveClient = grpc.BidiStreamingClient[ObserverClientMessage, ObserverServerMessage]

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations should embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
type CoordinatorServiceServer interface {
	Connect(grpc.BidiStreamingServer[ConnectMessage, ConnectMessage]) error
	Handle(context.Context, *CoordinatorHandleRequest) (*CoordinatorHandleResponse, error)
	Observe(grpc.BidiStreamingServer[ObserverClientMessage, ObserverServerMessage]) error
}

// UnimplementedCoordinatorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) Connect(grpc.BidiStreamingServer[ConnectMessage, ConnectMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCoordinatorServiceServer) Handle(context.Context, *CoordinatorHandleRequest) (*CoordinatorHandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedCoordinatorServiceServer) Observe(grpc.BidiStreamingServer[ObserverClientMessage, ObserverServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue() {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServiceServer).Connect(&grpc.GenericServerStream[ConnectMessage, ConnectMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_ConnectServer = grpc.BidiStreamingServer[ConnectMessage, ConnectMessage]

func _CoordinatorService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Handle(ctx, req.(*CoordinatorHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Observe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServiceServer).Observe(&grpc.GenericServerStream[ObserverClientMessage, ObserverServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_ObserveServer = grpc.BidiStreamingServer[ObserverClientMessage, ObserverServerMessage]

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoms.splitter.private.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _CoordinatorService_Handle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _CoordinatorService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Observe",
			Handler:       _CoordinatorService_Observe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atoms/splitter/private/coordinator.proto",
}
