// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/coordinator.proto

package private

import (
	pb1 "go.atoms.co/splitter/lib/service/session/pb"
	pb "go.atoms.co/splitter/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinatorOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Req:
	//
	//	*CoordinatorOperationRequest_Info
	//	*CoordinatorOperationRequest_Restart
	//	*CoordinatorOperationRequest_Suspend
	//	*CoordinatorOperationRequest_Resume
	//	*CoordinatorOperationRequest_Drain
	//	*CoordinatorOperationRequest_Sync
	//	*CoordinatorOperationRequest_RevokeGrants
	Req           isCoordinatorOperationRequest_Req `protobuf_oneof:"req"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorOperationRequest) Reset() {
	*x = CoordinatorOperationRequest{}
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorOperationRequest) ProtoMessage() {}

func (x *CoordinatorOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorOperationRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorOperationRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatorOperationRequest) GetReq() isCoordinatorOperationRequest_Req {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetInfo() *CoordinatorInfoRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetRestart() *CoordinatorRestartRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetSuspend() *ConsumerSuspendRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_Suspend); ok {
			return x.Suspend
		}
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetResume() *ConsumerResumeRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetDrain() *ConsumerDrainRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetSync() *CoordinatorClusterSyncRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *CoordinatorOperationRequest) GetRevokeGrants() *CoordinatorRevokeGrantsRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorOperationRequest_RevokeGrants); ok {
			return x.RevokeGrants
		}
	}
	return nil
}

type isCoordinatorOperationRequest_Req interface {
	isCoordinatorOperationRequest_Req()
}

type CoordinatorOperationRequest_Info struct {
	Info *CoordinatorInfoRequest `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type CoordinatorOperationRequest_Restart struct {
	Restart *CoordinatorRestartRequest `protobuf:"bytes,2,opt,name=restart,proto3,oneof"`
}

type CoordinatorOperationRequest_Suspend struct {
	Suspend *ConsumerSuspendRequest `protobuf:"bytes,3,opt,name=suspend,proto3,oneof"`
}

type CoordinatorOperationRequest_Resume struct {
	Resume *ConsumerResumeRequest `protobuf:"bytes,4,opt,name=resume,proto3,oneof"`
}

type CoordinatorOperationRequest_Drain struct {
	Drain *ConsumerDrainRequest `protobuf:"bytes,5,opt,name=drain,proto3,oneof"`
}

type CoordinatorOperationRequest_Sync struct {
	Sync *CoordinatorClusterSyncRequest `protobuf:"bytes,6,opt,name=sync,proto3,oneof"`
}

type CoordinatorOperationRequest_RevokeGrants struct {
	RevokeGrants *CoordinatorRevokeGrantsRequest `protobuf:"bytes,7,opt,name=revoke_grants,json=revokeGrants,proto3,oneof"`
}

func (*CoordinatorOperationRequest_Info) isCoordinatorOperationRequest_Req() {}

func (*CoordinatorOperationRequest_Restart) isCoordinatorOperationRequest_Req() {}

func (*CoordinatorOperationRequest_Suspend) isCoordinatorOperationRequest_Req() {}

func (*CoordinatorOperationRequest_Resume) isCoordinatorOperationRequest_Req() {}

func (*CoordinatorOperationRequest_Drain) isCoordinatorOperationRequest_Req() {}

func (*CoordinatorOperationRequest_Sync) isCoordinatorOperationRequest_Req() {}

func (*CoordinatorOperationRequest_RevokeGrants) isCoordinatorOperationRequest_Req() {}

type CoordinatorOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resp:
	//
	//	*CoordinatorOperationResponse_Info
	//	*CoordinatorOperationResponse_Restart
	//	*CoordinatorOperationResponse_Suspend
	//	*CoordinatorOperationResponse_Resume
	//	*CoordinatorOperationResponse_Drain
	//	*CoordinatorOperationResponse_Sync
	//	*CoordinatorOperationResponse_RevokeGrants
	Resp          isCoordinatorOperationResponse_Resp `protobuf_oneof:"resp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorOperationResponse) Reset() {
	*x = CoordinatorOperationResponse{}
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorOperationResponse) ProtoMessage() {}

func (x *CoordinatorOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorOperationResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorOperationResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorOperationResponse) GetResp() isCoordinatorOperationResponse_Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetInfo() *CoordinatorInfoResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetRestart() *CoordinatorRestartResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetSuspend() *ConsumerSuspendResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_Suspend); ok {
			return x.Suspend
		}
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetResume() *ConsumerResumeResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetDrain() *ConsumerDrainResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetSync() *CoordinatorClusterSyncResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *CoordinatorOperationResponse) GetRevokeGrants() *CoordinatorRevokeGrantsResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorOperationResponse_RevokeGrants); ok {
			return x.RevokeGrants
		}
	}
	return nil
}

type isCoordinatorOperationResponse_Resp interface {
	isCoordinatorOperationResponse_Resp()
}

type CoordinatorOperationResponse_Info struct {
	Info *CoordinatorInfoResponse `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type CoordinatorOperationResponse_Restart struct {
	Restart *CoordinatorRestartResponse `protobuf:"bytes,2,opt,name=restart,proto3,oneof"`
}

type CoordinatorOperationResponse_Suspend struct {
	Suspend *ConsumerSuspendResponse `protobuf:"bytes,3,opt,name=suspend,proto3,oneof"`
}

type CoordinatorOperationResponse_Resume struct {
	Resume *ConsumerResumeResponse `protobuf:"bytes,4,opt,name=resume,proto3,oneof"`
}

type CoordinatorOperationResponse_Drain struct {
	Drain *ConsumerDrainResponse `protobuf:"bytes,5,opt,name=drain,proto3,oneof"`
}

type CoordinatorOperationResponse_Sync struct {
	Sync *CoordinatorClusterSyncResponse `protobuf:"bytes,6,opt,name=sync,proto3,oneof"`
}

type CoordinatorOperationResponse_RevokeGrants struct {
	RevokeGrants *CoordinatorRevokeGrantsResponse `protobuf:"bytes,7,opt,name=revoke_grants,json=revokeGrants,proto3,oneof"`
}

func (*CoordinatorOperationResponse_Info) isCoordinatorOperationResponse_Resp() {}

func (*CoordinatorOperationResponse_Restart) isCoordinatorOperationResponse_Resp() {}

func (*CoordinatorOperationResponse_Suspend) isCoordinatorOperationResponse_Resp() {}

func (*CoordinatorOperationResponse_Resume) isCoordinatorOperationResponse_Resp() {}

func (*CoordinatorOperationResponse_Drain) isCoordinatorOperationResponse_Resp() {}

func (*CoordinatorOperationResponse_Sync) isCoordinatorOperationResponse_Resp() {}

func (*CoordinatorOperationResponse_RevokeGrants) isCoordinatorOperationResponse_Resp() {}

type CoordinatorHandleRequest struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Service *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Types that are valid to be assigned to Req:
	//
	//	*CoordinatorHandleRequest_Operation
	Req           isCoordinatorHandleRequest_Req `protobuf_oneof:"req"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorHandleRequest) Reset() {
	*x = CoordinatorHandleRequest{}
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorHandleRequest) ProtoMessage() {}

func (x *CoordinatorHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorHandleRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorHandleRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorHandleRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *CoordinatorHandleRequest) GetReq() isCoordinatorHandleRequest_Req {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *CoordinatorHandleRequest) GetOperation() *CoordinatorOperationRequest {
	if x != nil {
		if x, ok := x.Req.(*CoordinatorHandleRequest_Operation); ok {
			return x.Operation
		}
	}
	return nil
}

type isCoordinatorHandleRequest_Req interface {
	isCoordinatorHandleRequest_Req()
}

type CoordinatorHandleRequest_Operation struct {
	Operation *CoordinatorOperationRequest `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

func (*CoordinatorHandleRequest_Operation) isCoordinatorHandleRequest_Req() {}

type CoordinatorHandleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resp:
	//
	//	*CoordinatorHandleResponse_Operation
	Resp          isCoordinatorHandleResponse_Resp `protobuf_oneof:"resp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorHandleResponse) Reset() {
	*x = CoordinatorHandleResponse{}
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorHandleResponse) ProtoMessage() {}

func (x *CoordinatorHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorHandleResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorHandleResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *CoordinatorHandleResponse) GetResp() isCoordinatorHandleResponse_Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *CoordinatorHandleResponse) GetOperation() *CoordinatorOperationResponse {
	if x != nil {
		if x, ok := x.Resp.(*CoordinatorHandleResponse_Operation); ok {
			return x.Operation
		}
	}
	return nil
}

type isCoordinatorHandleResponse_Resp interface {
	isCoordinatorHandleResponse_Resp()
}

type CoordinatorHandleResponse_Operation struct {
	Operation *CoordinatorOperationResponse `protobuf:"bytes,1,opt,name=operation,proto3,oneof"`
}

func (*CoordinatorHandleResponse_Operation) isCoordinatorHandleResponse_Resp() {}

type ConnectMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ConnectMessage_Session
	//	*ConnectMessage_Consumer
	Msg           isConnectMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMessage) Reset() {
	*x = ConnectMessage{}
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMessage) ProtoMessage() {}

func (x *ConnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMessage.ProtoReflect.Descriptor instead.
func (*ConnectMessage) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectMessage) GetMsg() isConnectMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ConnectMessage) GetSession() *pb1.Message {
	if x != nil {
		if x, ok := x.Msg.(*ConnectMessage_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ConnectMessage) GetConsumer() *pb.ConsumerMessage {
	if x != nil {
		if x, ok := x.Msg.(*ConnectMessage_Consumer); ok {
			return x.Consumer
		}
	}
	return nil
}

type isConnectMessage_Msg interface {
	isConnectMessage_Msg()
}

type ConnectMessage_Session struct {
	Session *pb1.Message `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type ConnectMessage_Consumer struct {
	Consumer *pb.ConsumerMessage `protobuf:"bytes,2,opt,name=consumer,proto3,oneof"`
}

func (*ConnectMessage_Session) isConnectMessage_Msg() {}

func (*ConnectMessage_Consumer) isConnectMessage_Msg() {}

var File_atoms_splitter_private_coordinator_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_coordinator_proto_rawDesc = "" +
	"\n" +
	"(atoms/splitter/private/coordinator.proto\x12\x16atoms.splitter.private\x1a\x1datoms/splitter/consumer.proto\x1a\x1aatoms/splitter/model.proto\x1a&atoms/splitter/private/operation.proto\x1a%atoms/splitter/private/observer.proto\x1a0atoms/splitter/lib/service/session/session.proto\"\xc0\x04\n" +
	"\x1bCoordinatorOperationRequest\x12D\n" +
	"\x04info\x18\x01 \x01(\v2..atoms.splitter.private.CoordinatorInfoRequestH\x00R\x04info\x12M\n" +
	"\arestart\x18\x02 \x01(\v21.atoms.splitter.private.CoordinatorRestartRequestH\x00R\arestart\x12J\n" +
	"\asuspend\x18\x03 \x01(\v2..atoms.splitter.private.ConsumerSuspendRequestH\x00R\asuspend\x12G\n" +
	"\x06resume\x18\x04 \x01(\v2-.atoms.splitter.private.ConsumerResumeRequestH\x00R\x06resume\x12D\n" +
	"\x05drain\x18\x05 \x01(\v2,.atoms.splitter.private.ConsumerDrainRequestH\x00R\x05drain\x12K\n" +
	"\x04sync\x18\x06 \x01(\v25.atoms.splitter.private.CoordinatorClusterSyncRequestH\x00R\x04sync\x12]\n" +
	"\rrevoke_grants\x18\a \x01(\v26.atoms.splitter.private.CoordinatorRevokeGrantsRequestH\x00R\frevokeGrantsB\x05\n" +
	"\x03req\"\xc9\x04\n" +
	"\x1cCoordinatorOperationResponse\x12E\n" +
	"\x04info\x18\x01 \x01(\v2/.atoms.splitter.private.CoordinatorInfoResponseH\x00R\x04info\x12N\n" +
	"\arestart\x18\x02 \x01(\v22.atoms.splitter.private.CoordinatorRestartResponseH\x00R\arestart\x12K\n" +
	"\asuspend\x18\x03 \x01(\v2/.atoms.splitter.private.ConsumerSuspendResponseH\x00R\asuspend\x12H\n" +
	"\x06resume\x18\x04 \x01(\v2..atoms.splitter.private.ConsumerResumeResponseH\x00R\x06resume\x12E\n" +
	"\x05drain\x18\x05 \x01(\v2-.atoms.splitter.private.ConsumerDrainResponseH\x00R\x05drain\x12L\n" +
	"\x04sync\x18\x06 \x01(\v26.atoms.splitter.private.CoordinatorClusterSyncResponseH\x00R\x04sync\x12^\n" +
	"\rrevoke_grants\x18\a \x01(\v27.atoms.splitter.private.CoordinatorRevokeGrantsResponseH\x00R\frevokeGrantsB\x06\n" +
	"\x04resp\"\xb6\x01\n" +
	"\x18CoordinatorHandleRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12S\n" +
	"\toperation\x18\x02 \x01(\v23.atoms.splitter.private.CoordinatorOperationRequestH\x00R\toperationB\x05\n" +
	"\x03req\"y\n" +
	"\x19CoordinatorHandleResponse\x12T\n" +
	"\toperation\x18\x01 \x01(\v24.atoms.splitter.private.CoordinatorOperationResponseH\x00R\toperationB\x06\n" +
	"\x04resp\"\x9f\x01\n" +
	"\x0eConnectMessage\x12G\n" +
	"\asession\x18\x01 \x01(\v2+.atoms.splitter.lib.service.service.MessageH\x00R\asession\x12=\n" +
	"\bconsumer\x18\x02 \x01(\v2\x1f.atoms.splitter.ConsumerMessageH\x00R\bconsumerB\x05\n" +
	"\x03msg2\xcf\x02\n" +
	"\x12CoordinatorService\x12]\n" +
	"\aConnect\x12&.atoms.splitter.private.ConnectMessage\x1a&.atoms.splitter.private.ConnectMessage(\x010\x01\x12m\n" +
	"\x06Handle\x120.atoms.splitter.private.CoordinatorHandleRequest\x1a1.atoms.splitter.private.CoordinatorHandleResponse\x12k\n" +
	"\aObserve\x12-.atoms.splitter.private.ObserverClientMessage\x1a-.atoms.splitter.private.ObserverServerMessage(\x010\x01B!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_coordinator_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_coordinator_proto_rawDescData []byte
)

func file_atoms_splitter_private_coordinator_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_coordinator_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_coordinator_proto_rawDesc), len(file_atoms_splitter_private_coordinator_proto_rawDesc)))
	})
	return file_atoms_splitter_private_coordinator_proto_rawDescData
}

var file_atoms_splitter_private_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_atoms_splitter_private_coordinator_proto_goTypes = []any{
	(*CoordinatorOperationRequest)(nil),     // 0: atoms.splitter.private.CoordinatorOperationRequest
	(*CoordinatorOperationResponse)(nil),    // 1: atoms.splitter.private.CoordinatorOperationResponse
	(*CoordinatorHandleRequest)(nil),        // 2: atoms.splitter.private.CoordinatorHandleRequest
	(*CoordinatorHandleResponse)(nil),       // 3: atoms.splitter.private.CoordinatorHandleResponse
	(*ConnectMessage)(nil),                  // 4: atoms.splitter.private.ConnectMessage
	(*CoordinatorInfoRequest)(nil),          // 5: atoms.splitter.private.CoordinatorInfoRequest
	(*CoordinatorRestartRequest)(nil),       // 6: atoms.splitter.private.CoordinatorRestartRequest
	(*ConsumerSuspendRequest)(nil),          // 7: atoms.splitter.private.ConsumerSuspendRequest
	(*ConsumerResumeRequest)(nil),           // 8: atoms.splitter.private.ConsumerResumeRequest
	(*ConsumerDrainRequest)(nil),            // 9: atoms.splitter.private.ConsumerDrainRequest
	(*CoordinatorClusterSyncRequest)(nil),   // 10: atoms.splitter.private.CoordinatorClusterSyncRequest
	(*CoordinatorRevokeGrantsRequest)(nil),  // 11: atoms.splitter.private.CoordinatorRevokeGrantsRequest
	(*CoordinatorInfoResponse)(nil),         // 12: atoms.splitter.private.CoordinatorInfoResponse
	(*CoordinatorRestartResponse)(nil),      // 13: atoms.splitter.private.CoordinatorRestartResponse
	(*ConsumerSuspendResponse)(nil),         // 14: atoms.splitter.private.ConsumerSuspendResponse
	(*ConsumerResumeResponse)(nil),          // 15: atoms.splitter.private.ConsumerResumeResponse
	(*ConsumerDrainResponse)(nil),           // 16: atoms.splitter.private.ConsumerDrainResponse
	(*CoordinatorClusterSyncResponse)(nil),  // 17: atoms.splitter.private.CoordinatorClusterSyncResponse
	(*CoordinatorRevokeGrantsResponse)(nil), // 18: atoms.splitter.private.CoordinatorRevokeGrantsResponse
	(*pb.QualifiedServiceName)(nil),         // 19: atoms.splitter.QualifiedServiceName
	(*pb1.Message)(nil),                     // 20: atoms.splitter.lib.service.service.Message
	(*pb.ConsumerMessage)(nil),              // 21: atoms.splitter.ConsumerMessage
	(*ObserverClientMessage)(nil),           // 22: atoms.splitter.private.ObserverClientMessage
	(*ObserverServerMessage)(nil),           // 23: atoms.splitter.private.ObserverServerMessage
}
var file_atoms_splitter_private_coordinator_proto_depIdxs = []int32{
	5,  // 0: atoms.splitter.private.CoordinatorOperationRequest.info:type_name -> atoms.splitter.private.CoordinatorInfoRequest
	6,  // 1: atoms.splitter.private.CoordinatorOperationRequest.restart:type_name -> atoms.splitter.private.CoordinatorRestartRequest
	7,  // 2: atoms.splitter.private.CoordinatorOperationRequest.suspend:type_name -> atoms.splitter.private.ConsumerSuspendRequest
	8,  // 3: atoms.splitter.private.CoordinatorOperationRequest.resume:type_name -> atoms.splitter.private.ConsumerResumeRequest
	9,  // 4: atoms.splitter.private.CoordinatorOperationRequest.drain:type_name -> atoms.splitter.private.ConsumerDrainRequest
	10, // 5: atoms.splitter.private.CoordinatorOperationRequest.sync:type_name -> atoms.splitter.private.CoordinatorClusterSyncRequest
	11, // 6: atoms.splitter.private.CoordinatorOperationRequest.revoke_grants:type_name -> atoms.splitter.private.CoordinatorRevokeGrantsRequest
	12, // 7: atoms.splitter.private.CoordinatorOperationResponse.info:type_name -> atoms.splitter.private.CoordinatorInfoResponse
	13, // 8: atoms.splitter.private.CoordinatorOperationResponse.restart:type_name -> atoms.splitter.private.CoordinatorRestartResponse
	14, // 9: atoms.splitter.private.CoordinatorOperationResponse.suspend:type_name -> atoms.splitter.private.ConsumerSuspendResponse
	15, // 10: atoms.splitter.private.CoordinatorOperationResponse.resume:type_name -> atoms.splitter.private.ConsumerResumeResponse
	16, // 11: atoms.splitter.private.CoordinatorOperationResponse.drain:type_name -> atoms.splitter.private.ConsumerDrainResponse
	17, // 12: atoms.splitter.private.CoordinatorOperationResponse.sync:type_name -> atoms.splitter.private.CoordinatorClusterSyncResponse
	18, // 13: atoms.splitter.private.CoordinatorOperationResponse.revoke_grants:type_name -> atoms.splitter.private.CoordinatorRevokeGrantsResponse
	19, // 14: atoms.splitter.private.CoordinatorHandleRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	0,  // 15: atoms.splitter.private.CoordinatorHandleRequest.operation:type_name -> atoms.splitter.private.CoordinatorOperationRequest
	1,  // 16: atoms.splitter.private.CoordinatorHandleResponse.operation:type_name -> atoms.splitter.private.CoordinatorOperationResponse
	20, // 17: atoms.splitter.private.ConnectMessage.session:type_name -> atoms.splitter.lib.service.service.Message
	21, // 18: atoms.splitter.private.ConnectMessage.consumer:type_name -> atoms.splitter.ConsumerMessage
	4,  // 19: atoms.splitter.private.CoordinatorService.Connect:input_type -> atoms.splitter.private.ConnectMessage
	2,  // 20: atoms.splitter.private.CoordinatorService.Handle:input_type -> atoms.splitter.private.CoordinatorHandleRequest
	22, // 21: atoms.splitter.private.CoordinatorService.Observe:input_type -> atoms.splitter.private.ObserverClientMessage
	4,  // 22: atoms.splitter.private.CoordinatorService.Connect:output_type -> atoms.splitter.private.ConnectMessage
	3,  // 23: atoms.splitter.private.CoordinatorService.Handle:output_type -> atoms.splitter.private.CoordinatorHandleResponse
	23, // 24: atoms.splitter.private.CoordinatorService.Observe:output_type -> atoms.splitter.private.ObserverServerMessage
	22, // [22:25] is the sub-list for method output_type
	19, // [19:22] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_coordinator_proto_init() }
func file_atoms_splitter_private_coordinator_proto_init() {
	if File_atoms_splitter_private_coordinator_proto != nil {
		return
	}
	file_atoms_splitter_private_operation_proto_init()
	file_atoms_splitter_private_observer_proto_init()
	file_atoms_splitter_private_coordinator_proto_msgTypes[0].OneofWrappers = []any{
		(*CoordinatorOperationRequest_Info)(nil),
		(*CoordinatorOperationRequest_Restart)(nil),
		(*CoordinatorOperationRequest_Suspend)(nil),
		(*CoordinatorOperationRequest_Resume)(nil),
		(*CoordinatorOperationRequest_Drain)(nil),
		(*CoordinatorOperationRequest_Sync)(nil),
		(*CoordinatorOperationRequest_RevokeGrants)(nil),
	}
	file_atoms_splitter_private_coordinator_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorOperationResponse_Info)(nil),
		(*CoordinatorOperationResponse_Restart)(nil),
		(*CoordinatorOperationResponse_Suspend)(nil),
		(*CoordinatorOperationResponse_Resume)(nil),
		(*CoordinatorOperationResponse_Drain)(nil),
		(*CoordinatorOperationResponse_Sync)(nil),
		(*CoordinatorOperationResponse_RevokeGrants)(nil),
	}
	file_atoms_splitter_private_coordinator_proto_msgTypes[2].OneofWrappers = []any{
		(*CoordinatorHandleRequest_Operation)(nil),
	}
	file_atoms_splitter_private_coordinator_proto_msgTypes[3].OneofWrappers = []any{
		(*CoordinatorHandleResponse_Operation)(nil),
	}
	file_atoms_splitter_private_coordinator_proto_msgTypes[4].OneofWrappers = []any{
		(*ConnectMessage_Session)(nil),
		(*ConnectMessage_Consumer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_coordinator_proto_rawDesc), len(file_atoms_splitter_private_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_private_coordinator_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_coordinator_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_private_coordinator_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_coordinator_proto = out.File
	file_atoms_splitter_private_coordinator_proto_goTypes = nil
	file_atoms_splitter_private_coordinator_proto_depIdxs = nil
}
