// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: atoms/splitter/private/leader.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderService_Join_FullMethodName   = "/atoms.splitter.private.LeaderService/Join"
	LeaderService_Handle_FullMethodName = "/atoms.splitter.private.LeaderService/Handle"
)

// LeaderServiceClient is the client API for LeaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderServiceClient interface {
	Join(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[JoinMessage, JoinMessage], error)
	Handle(ctx context.Context, in *LeaderHandleRequest, opts ...grpc.CallOption) (*LeaderHandleResponse, error)
}

type leaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderServiceClient(cc grpc.ClientConnInterface) LeaderServiceClient {
	return &leaderServiceClient{cc}
}

func (c *leaderServiceClient) Join(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[JoinMessage, JoinMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeaderService_ServiceDesc.Streams[0], LeaderService_Join_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinMessage, JoinMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaderService_JoinClient = grpc.BidiStreamingClient[JoinMessage, JoinMessage]

func (c *leaderServiceClient) Handle(ctx context.Context, in *LeaderHandleRequest, opts ...grpc.CallOption) (*LeaderHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderHandleResponse)
	err := c.cc.Invoke(ctx, LeaderService_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderServiceServer is the server API for LeaderService service.
// All implementations should embed UnimplementedLeaderServiceServer
// for forward compatibility.
type LeaderServiceServer interface {
	Join(grpc.BidiStreamingServer[JoinMessage, JoinMessage]) error
	Handle(context.Context, *LeaderHandleRequest) (*LeaderHandleResponse, error)
}

// UnimplementedLeaderServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderServiceServer struct{}

func (UnimplementedLeaderServiceServer) Join(grpc.BidiStreamingServer[JoinMessage, JoinMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedLeaderServiceServer) Handle(context.Context, *LeaderHandleRequest) (*LeaderHandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedLeaderServiceServer) testEmbeddedByValue() {}

// UnsafeLeaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderServiceServer will
// result in compilation errors.
type UnsafeLeaderServiceServer interface {
	mustEmbedUnimplementedLeaderServiceServer()
}

func RegisterLeaderServiceServer(s grpc.ServiceRegistrar, srv LeaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderService_ServiceDesc, srv)
}

func _LeaderService_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LeaderServiceServer).Join(&grpc.GenericServerStream[JoinMessage, JoinMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaderService_JoinServer = grpc.BidiStreamingServer[JoinMessage, JoinMessage]

func _LeaderService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderService_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).Handle(ctx, req.(*LeaderHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderService_ServiceDesc is the grpc.ServiceDesc for LeaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoms.splitter.private.LeaderService",
	HandlerType: (*LeaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _LeaderService_Handle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _LeaderService_Join_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atoms/splitter/private/leader.proto",
}
