// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/load.proto

package private

import (
	pb "go.atoms.co/splitter/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{0}
}

func (x *Shard) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Shard) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Shard) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type DomainQuantileInfo struct {
	state          protoimpl.MessageState                  `protogen:"open.v1"`
	DomainQuantile float64                                 `protobuf:"fixed64,1,opt,name=domain_quantile,json=domainQuantile,proto3" json:"domain_quantile,omitempty"`
	ShardQuantiles []*DomainQuantileInfo_ShardQuantileInfo `protobuf:"bytes,2,rep,name=shard_quantiles,json=shardQuantiles,proto3" json:"shard_quantiles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DomainQuantileInfo) Reset() {
	*x = DomainQuantileInfo{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainQuantileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainQuantileInfo) ProtoMessage() {}

func (x *DomainQuantileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainQuantileInfo.ProtoReflect.Descriptor instead.
func (*DomainQuantileInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{1}
}

func (x *DomainQuantileInfo) GetDomainQuantile() float64 {
	if x != nil {
		return x.DomainQuantile
	}
	return 0
}

func (x *DomainQuantileInfo) GetShardQuantiles() []*DomainQuantileInfo_ShardQuantileInfo {
	if x != nil {
		return x.ShardQuantiles
	}
	return nil
}

type DomainTrackerSnapshot struct {
	state          protoimpl.MessageState                           `protogen:"open.v1"`
	CreatedAt      *timestamppb.Timestamp                           `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DomainSnapshot *DomainTrackerSnapshot_P2QuantileSnapshot        `protobuf:"bytes,2,opt,name=domain_snapshot,json=domainSnapshot,proto3" json:"domain_snapshot,omitempty"`
	ShardSnapshot  []*DomainTrackerSnapshot_ShardP2QuantileSnapshot `protobuf:"bytes,3,rep,name=shard_snapshot,json=shardSnapshot,proto3" json:"shard_snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DomainTrackerSnapshot) Reset() {
	*x = DomainTrackerSnapshot{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainTrackerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainTrackerSnapshot) ProtoMessage() {}

func (x *DomainTrackerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainTrackerSnapshot.ProtoReflect.Descriptor instead.
func (*DomainTrackerSnapshot) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{2}
}

func (x *DomainTrackerSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DomainTrackerSnapshot) GetDomainSnapshot() *DomainTrackerSnapshot_P2QuantileSnapshot {
	if x != nil {
		return x.DomainSnapshot
	}
	return nil
}

func (x *DomainTrackerSnapshot) GetShardSnapshot() []*DomainTrackerSnapshot_ShardP2QuantileSnapshot {
	if x != nil {
		return x.ShardSnapshot
	}
	return nil
}

type DomainLoadInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DomainName      string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	TrackerSnapshot *DomainTrackerSnapshot `protobuf:"bytes,2,opt,name=tracker_snapshot,json=trackerSnapshot,proto3" json:"tracker_snapshot,omitempty"`
	QuantileInfo    *DomainQuantileInfo    `protobuf:"bytes,3,opt,name=quantile_info,json=quantileInfo,proto3" json:"quantile_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DomainLoadInfo) Reset() {
	*x = DomainLoadInfo{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainLoadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainLoadInfo) ProtoMessage() {}

func (x *DomainLoadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainLoadInfo.ProtoReflect.Descriptor instead.
func (*DomainLoadInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{3}
}

func (x *DomainLoadInfo) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *DomainLoadInfo) GetTrackerSnapshot() *DomainTrackerSnapshot {
	if x != nil {
		return x.TrackerSnapshot
	}
	return nil
}

func (x *DomainLoadInfo) GetQuantileInfo() *DomainQuantileInfo {
	if x != nil {
		return x.QuantileInfo
	}
	return nil
}

type ServiceLoadInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Info          []*DomainLoadInfo        `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLoadInfo) Reset() {
	*x = ServiceLoadInfo{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLoadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLoadInfo) ProtoMessage() {}

func (x *ServiceLoadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLoadInfo.ProtoReflect.Descriptor instead.
func (*ServiceLoadInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceLoadInfo) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceLoadInfo) GetInfo() []*DomainLoadInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DomainQuantileInfo_ShardQuantileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         *Shard                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Quantile      float64                `protobuf:"fixed64,2,opt,name=quantile,proto3" json:"quantile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainQuantileInfo_ShardQuantileInfo) Reset() {
	*x = DomainQuantileInfo_ShardQuantileInfo{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainQuantileInfo_ShardQuantileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainQuantileInfo_ShardQuantileInfo) ProtoMessage() {}

func (x *DomainQuantileInfo_ShardQuantileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainQuantileInfo_ShardQuantileInfo.ProtoReflect.Descriptor instead.
func (*DomainQuantileInfo_ShardQuantileInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DomainQuantileInfo_ShardQuantileInfo) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *DomainQuantileInfo_ShardQuantileInfo) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

type DomainTrackerSnapshot_P2QuantileSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Percentile       float64                `protobuf:"fixed64,1,opt,name=percentile,proto3" json:"percentile,omitempty"`
	Height           []float64              `protobuf:"fixed64,2,rep,packed,name=height,proto3" json:"height,omitempty"`
	MarkerPos        []uint64               `protobuf:"varint,3,rep,packed,name=marker_pos,json=markerPos,proto3" json:"marker_pos,omitempty"`
	DesiredMarkerPos []float64              `protobuf:"fixed64,4,rep,packed,name=desired_marker_pos,json=desiredMarkerPos,proto3" json:"desired_marker_pos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) Reset() {
	*x = DomainTrackerSnapshot_P2QuantileSnapshot{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainTrackerSnapshot_P2QuantileSnapshot) ProtoMessage() {}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainTrackerSnapshot_P2QuantileSnapshot.ProtoReflect.Descriptor instead.
func (*DomainTrackerSnapshot_P2QuantileSnapshot) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) GetPercentile() float64 {
	if x != nil {
		return x.Percentile
	}
	return 0
}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) GetHeight() []float64 {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) GetMarkerPos() []uint64 {
	if x != nil {
		return x.MarkerPos
	}
	return nil
}

func (x *DomainTrackerSnapshot_P2QuantileSnapshot) GetDesiredMarkerPos() []float64 {
	if x != nil {
		return x.DesiredMarkerPos
	}
	return nil
}

type DomainTrackerSnapshot_ShardP2QuantileSnapshot struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Shard         *Shard                                    `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Snapshot      *DomainTrackerSnapshot_P2QuantileSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainTrackerSnapshot_ShardP2QuantileSnapshot) Reset() {
	*x = DomainTrackerSnapshot_ShardP2QuantileSnapshot{}
	mi := &file_atoms_splitter_private_load_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainTrackerSnapshot_ShardP2QuantileSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainTrackerSnapshot_ShardP2QuantileSnapshot) ProtoMessage() {}

func (x *DomainTrackerSnapshot_ShardP2QuantileSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_load_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainTrackerSnapshot_ShardP2QuantileSnapshot.ProtoReflect.Descriptor instead.
func (*DomainTrackerSnapshot_ShardP2QuantileSnapshot) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_load_proto_rawDescGZIP(), []int{2, 1}
}

func (x *DomainTrackerSnapshot_ShardP2QuantileSnapshot) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *DomainTrackerSnapshot_ShardP2QuantileSnapshot) GetSnapshot() *DomainTrackerSnapshot_P2QuantileSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_atoms_splitter_private_load_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_load_proto_rawDesc = "" +
	"\n" +
	"!atoms/splitter/private/load.proto\x12\x16atoms.splitter.private\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aatoms/splitter/model.proto\"C\n" +
	"\x05Shard\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\x8a\x02\n" +
	"\x12DomainQuantileInfo\x12'\n" +
	"\x0fdomain_quantile\x18\x01 \x01(\x01R\x0edomainQuantile\x12e\n" +
	"\x0fshard_quantiles\x18\x02 \x03(\v2<.atoms.splitter.private.DomainQuantileInfo.ShardQuantileInfoR\x0eshardQuantiles\x1ad\n" +
	"\x11ShardQuantileInfo\x123\n" +
	"\x05shard\x18\x01 \x01(\v2\x1d.atoms.splitter.private.ShardR\x05shard\x12\x1a\n" +
	"\bquantile\x18\x02 \x01(\x01R\bquantile\"\xf6\x04\n" +
	"\x15DomainTrackerSnapshot\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12i\n" +
	"\x0fdomain_snapshot\x18\x02 \x01(\v2@.atoms.splitter.private.DomainTrackerSnapshot.P2QuantileSnapshotR\x0edomainSnapshot\x12l\n" +
	"\x0eshard_snapshot\x18\x03 \x03(\v2E.atoms.splitter.private.DomainTrackerSnapshot.ShardP2QuantileSnapshotR\rshardSnapshot\x1a\x99\x01\n" +
	"\x12P2QuantileSnapshot\x12\x1e\n" +
	"\n" +
	"percentile\x18\x01 \x01(\x01R\n" +
	"percentile\x12\x16\n" +
	"\x06height\x18\x02 \x03(\x01R\x06height\x12\x1d\n" +
	"\n" +
	"marker_pos\x18\x03 \x03(\x04R\tmarkerPos\x12,\n" +
	"\x12desired_marker_pos\x18\x04 \x03(\x01R\x10desiredMarkerPos\x1a\xac\x01\n" +
	"\x17ShardP2QuantileSnapshot\x123\n" +
	"\x05shard\x18\x01 \x01(\v2\x1d.atoms.splitter.private.ShardR\x05shard\x12\\\n" +
	"\bsnapshot\x18\x02 \x01(\v2@.atoms.splitter.private.DomainTrackerSnapshot.P2QuantileSnapshotR\bsnapshot\"\xdc\x01\n" +
	"\x0eDomainLoadInfo\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\x12X\n" +
	"\x10tracker_snapshot\x18\x02 \x01(\v2-.atoms.splitter.private.DomainTrackerSnapshotR\x0ftrackerSnapshot\x12O\n" +
	"\rquantile_info\x18\x03 \x01(\v2*.atoms.splitter.private.DomainQuantileInfoR\fquantileInfo\"\x8d\x01\n" +
	"\x0fServiceLoadInfo\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12:\n" +
	"\x04info\x18\x02 \x03(\v2&.atoms.splitter.private.DomainLoadInfoR\x04infoB!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_load_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_load_proto_rawDescData []byte
)

func file_atoms_splitter_private_load_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_load_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_load_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_load_proto_rawDesc), len(file_atoms_splitter_private_load_proto_rawDesc)))
	})
	return file_atoms_splitter_private_load_proto_rawDescData
}

var file_atoms_splitter_private_load_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_atoms_splitter_private_load_proto_goTypes = []any{
	(*Shard)(nil),                                         // 0: atoms.splitter.private.Shard
	(*DomainQuantileInfo)(nil),                            // 1: atoms.splitter.private.DomainQuantileInfo
	(*DomainTrackerSnapshot)(nil),                         // 2: atoms.splitter.private.DomainTrackerSnapshot
	(*DomainLoadInfo)(nil),                                // 3: atoms.splitter.private.DomainLoadInfo
	(*ServiceLoadInfo)(nil),                               // 4: atoms.splitter.private.ServiceLoadInfo
	(*DomainQuantileInfo_ShardQuantileInfo)(nil),          // 5: atoms.splitter.private.DomainQuantileInfo.ShardQuantileInfo
	(*DomainTrackerSnapshot_P2QuantileSnapshot)(nil),      // 6: atoms.splitter.private.DomainTrackerSnapshot.P2QuantileSnapshot
	(*DomainTrackerSnapshot_ShardP2QuantileSnapshot)(nil), // 7: atoms.splitter.private.DomainTrackerSnapshot.ShardP2QuantileSnapshot
	(*timestamppb.Timestamp)(nil),                         // 8: google.protobuf.Timestamp
	(*pb.QualifiedServiceName)(nil),                       // 9: atoms.splitter.QualifiedServiceName
}
var file_atoms_splitter_private_load_proto_depIdxs = []int32{
	5,  // 0: atoms.splitter.private.DomainQuantileInfo.shard_quantiles:type_name -> atoms.splitter.private.DomainQuantileInfo.ShardQuantileInfo
	8,  // 1: atoms.splitter.private.DomainTrackerSnapshot.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: atoms.splitter.private.DomainTrackerSnapshot.domain_snapshot:type_name -> atoms.splitter.private.DomainTrackerSnapshot.P2QuantileSnapshot
	7,  // 3: atoms.splitter.private.DomainTrackerSnapshot.shard_snapshot:type_name -> atoms.splitter.private.DomainTrackerSnapshot.ShardP2QuantileSnapshot
	2,  // 4: atoms.splitter.private.DomainLoadInfo.tracker_snapshot:type_name -> atoms.splitter.private.DomainTrackerSnapshot
	1,  // 5: atoms.splitter.private.DomainLoadInfo.quantile_info:type_name -> atoms.splitter.private.DomainQuantileInfo
	9,  // 6: atoms.splitter.private.ServiceLoadInfo.service:type_name -> atoms.splitter.QualifiedServiceName
	3,  // 7: atoms.splitter.private.ServiceLoadInfo.info:type_name -> atoms.splitter.private.DomainLoadInfo
	0,  // 8: atoms.splitter.private.DomainQuantileInfo.ShardQuantileInfo.shard:type_name -> atoms.splitter.private.Shard
	0,  // 9: atoms.splitter.private.DomainTrackerSnapshot.ShardP2QuantileSnapshot.shard:type_name -> atoms.splitter.private.Shard
	6,  // 10: atoms.splitter.private.DomainTrackerSnapshot.ShardP2QuantileSnapshot.snapshot:type_name -> atoms.splitter.private.DomainTrackerSnapshot.P2QuantileSnapshot
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_load_proto_init() }
func file_atoms_splitter_private_load_proto_init() {
	if File_atoms_splitter_private_load_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_load_proto_rawDesc), len(file_atoms_splitter_private_load_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_private_load_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_load_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_private_load_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_load_proto = out.File
	file_atoms_splitter_private_load_proto_goTypes = nil
	file_atoms_splitter_private_load_proto_depIdxs = nil
}
