// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: atoms/splitter/private/observer.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObserverService_Observe_FullMethodName = "/atoms.splitter.private.ObserverService/Observe"
)

// ObserverServiceClient is the client API for ObserverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObserverServiceClient interface {
	Observe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ObserverClientMessage, ObserverServerMessage], error)
}

type observerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObserverServiceClient(cc grpc.ClientConnInterface) ObserverServiceClient {
	return &observerServiceClient{cc}
}

func (c *observerServiceClient) Observe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ObserverClientMessage, ObserverServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObserverService_ServiceDesc.Streams[0], ObserverService_Observe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserverClientMessage, ObserverServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObserverService_ObserveClient = grpc.BidiStreamingClient[ObserverClientMessage, ObserverServerMessage]

// ObserverServiceServer is the server API for ObserverService service.
// All implementations should embed UnimplementedObserverServiceServer
// for forward compatibility.
type ObserverServiceServer interface {
	Observe(grpc.BidiStreamingServer[ObserverClientMessage, ObserverServerMessage]) error
}

// UnimplementedObserverServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObserverServiceServer struct{}

func (UnimplementedObserverServiceServer) Observe(grpc.BidiStreamingServer[ObserverClientMessage, ObserverServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedObserverServiceServer) testEmbeddedByValue() {}

// UnsafeObserverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObserverServiceServer will
// result in compilation errors.
type UnsafeObserverServiceServer interface {
	mustEmbedUnimplementedObserverServiceServer()
}

func RegisterObserverServiceServer(s grpc.ServiceRegistrar, srv ObserverServiceServer) {
	// If the following call pancis, it indicates UnimplementedObserverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObserverService_ServiceDesc, srv)
}

func _ObserverService_Observe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObserverServiceServer).Observe(&grpc.GenericServerStream[ObserverClientMessage, ObserverServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObserverService_ObserveServer = grpc.BidiStreamingServer[ObserverClientMessage, ObserverServerMessage]

// ObserverService_ServiceDesc is the grpc.ServiceDesc for ObserverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObserverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoms.splitter.private.ObserverService",
	HandlerType: (*ObserverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Observe",
			Handler:       _ObserverService_Observe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atoms/splitter/private/observer.proto",
}
