// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/observer.proto

package private

import (
	pb "go.atoms.co/splitter/lib/service/session/pb"
	pb1 "go.atoms.co/splitter/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObserverClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ObserverClientMessage_Session
	//	*ObserverClientMessage_Register_
	Msg           isObserverClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverClientMessage) Reset() {
	*x = ObserverClientMessage{}
	mi := &file_atoms_splitter_private_observer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverClientMessage) ProtoMessage() {}

func (x *ObserverClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_observer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverClientMessage.ProtoReflect.Descriptor instead.
func (*ObserverClientMessage) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_observer_proto_rawDescGZIP(), []int{0}
}

func (x *ObserverClientMessage) GetMsg() isObserverClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ObserverClientMessage) GetSession() *pb.Message {
	if x != nil {
		if x, ok := x.Msg.(*ObserverClientMessage_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ObserverClientMessage) GetRegister() *ObserverClientMessage_Register {
	if x != nil {
		if x, ok := x.Msg.(*ObserverClientMessage_Register_); ok {
			return x.Register
		}
	}
	return nil
}

type isObserverClientMessage_Msg interface {
	isObserverClientMessage_Msg()
}

type ObserverClientMessage_Session struct {
	Session *pb.Message `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type ObserverClientMessage_Register_ struct {
	Register *ObserverClientMessage_Register `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

func (*ObserverClientMessage_Session) isObserverClientMessage_Msg() {}

func (*ObserverClientMessage_Register_) isObserverClientMessage_Msg() {}

type ObserverServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ObserverServerMessage_Session
	//	*ObserverServerMessage_Cluster
	Msg           isObserverServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverServerMessage) Reset() {
	*x = ObserverServerMessage{}
	mi := &file_atoms_splitter_private_observer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverServerMessage) ProtoMessage() {}

func (x *ObserverServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_observer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverServerMessage.ProtoReflect.Descriptor instead.
func (*ObserverServerMessage) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_observer_proto_rawDescGZIP(), []int{1}
}

func (x *ObserverServerMessage) GetMsg() isObserverServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ObserverServerMessage) GetSession() *pb.Message {
	if x != nil {
		if x, ok := x.Msg.(*ObserverServerMessage_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ObserverServerMessage) GetCluster() *pb1.ClusterMessage {
	if x != nil {
		if x, ok := x.Msg.(*ObserverServerMessage_Cluster); ok {
			return x.Cluster
		}
	}
	return nil
}

type isObserverServerMessage_Msg interface {
	isObserverServerMessage_Msg()
}

type ObserverServerMessage_Session struct {
	Session *pb.Message `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type ObserverServerMessage_Cluster struct {
	Cluster *pb1.ClusterMessage `protobuf:"bytes,2,opt,name=cluster,proto3,oneof"`
}

func (*ObserverServerMessage_Session) isObserverServerMessage_Msg() {}

func (*ObserverServerMessage_Cluster) isObserverServerMessage_Msg() {}

type ObserverClientMessage_Register struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Observer      *pb1.Instance             `protobuf:"bytes,1,opt,name=observer,proto3" json:"observer,omitempty"`
	Service       *pb1.QualifiedServiceName `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverClientMessage_Register) Reset() {
	*x = ObserverClientMessage_Register{}
	mi := &file_atoms_splitter_private_observer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverClientMessage_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverClientMessage_Register) ProtoMessage() {}

func (x *ObserverClientMessage_Register) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_observer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverClientMessage_Register.ProtoReflect.Descriptor instead.
func (*ObserverClientMessage_Register) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_observer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ObserverClientMessage_Register) GetObserver() *pb1.Instance {
	if x != nil {
		return x.Observer
	}
	return nil
}

func (x *ObserverClientMessage_Register) GetService() *pb1.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_atoms_splitter_private_observer_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_observer_proto_rawDesc = "" +
	"\n" +
	"%atoms/splitter/private/observer.proto\x12\x16atoms.splitter.private\x1a0atoms/splitter/lib/service/session/session.proto\x1a\x1catoms/splitter/cluster.proto\x1a\x1aatoms/splitter/model.proto\"\xc0\x02\n" +
	"\x15ObserverClientMessage\x12G\n" +
	"\asession\x18\x01 \x01(\v2+.atoms.splitter.lib.service.service.MessageH\x00R\asession\x12T\n" +
	"\bregister\x18\x02 \x01(\v26.atoms.splitter.private.ObserverClientMessage.RegisterH\x00R\bregister\x1a\x80\x01\n" +
	"\bRegister\x124\n" +
	"\bobserver\x18\x01 \x01(\v2\x18.atoms.splitter.InstanceR\bobserver\x12>\n" +
	"\aservice\x18\x02 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aserviceB\x05\n" +
	"\x03msg\"\xa3\x01\n" +
	"\x15ObserverServerMessage\x12G\n" +
	"\asession\x18\x01 \x01(\v2+.atoms.splitter.lib.service.service.MessageH\x00R\asession\x12:\n" +
	"\acluster\x18\x02 \x01(\v2\x1e.atoms.splitter.ClusterMessageH\x00R\aclusterB\x05\n" +
	"\x03msg2~\n" +
	"\x0fObserverService\x12k\n" +
	"\aObserve\x12-.atoms.splitter.private.ObserverClientMessage\x1a-.atoms.splitter.private.ObserverServerMessage(\x010\x01B!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_observer_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_observer_proto_rawDescData []byte
)

func file_atoms_splitter_private_observer_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_observer_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_observer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_observer_proto_rawDesc), len(file_atoms_splitter_private_observer_proto_rawDesc)))
	})
	return file_atoms_splitter_private_observer_proto_rawDescData
}

var file_atoms_splitter_private_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atoms_splitter_private_observer_proto_goTypes = []any{
	(*ObserverClientMessage)(nil),          // 0: atoms.splitter.private.ObserverClientMessage
	(*ObserverServerMessage)(nil),          // 1: atoms.splitter.private.ObserverServerMessage
	(*ObserverClientMessage_Register)(nil), // 2: atoms.splitter.private.ObserverClientMessage.Register
	(*pb.Message)(nil),                     // 3: atoms.splitter.lib.service.service.Message
	(*pb1.ClusterMessage)(nil),             // 4: atoms.splitter.ClusterMessage
	(*pb1.Instance)(nil),                   // 5: atoms.splitter.Instance
	(*pb1.QualifiedServiceName)(nil),       // 6: atoms.splitter.QualifiedServiceName
}
var file_atoms_splitter_private_observer_proto_depIdxs = []int32{
	3, // 0: atoms.splitter.private.ObserverClientMessage.session:type_name -> atoms.splitter.lib.service.service.Message
	2, // 1: atoms.splitter.private.ObserverClientMessage.register:type_name -> atoms.splitter.private.ObserverClientMessage.Register
	3, // 2: atoms.splitter.private.ObserverServerMessage.session:type_name -> atoms.splitter.lib.service.service.Message
	4, // 3: atoms.splitter.private.ObserverServerMessage.cluster:type_name -> atoms.splitter.ClusterMessage
	5, // 4: atoms.splitter.private.ObserverClientMessage.Register.observer:type_name -> atoms.splitter.Instance
	6, // 5: atoms.splitter.private.ObserverClientMessage.Register.service:type_name -> atoms.splitter.QualifiedServiceName
	0, // 6: atoms.splitter.private.ObserverService.Observe:input_type -> atoms.splitter.private.ObserverClientMessage
	1, // 7: atoms.splitter.private.ObserverService.Observe:output_type -> atoms.splitter.private.ObserverServerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_observer_proto_init() }
func file_atoms_splitter_private_observer_proto_init() {
	if File_atoms_splitter_private_observer_proto != nil {
		return
	}
	file_atoms_splitter_private_observer_proto_msgTypes[0].OneofWrappers = []any{
		(*ObserverClientMessage_Session)(nil),
		(*ObserverClientMessage_Register_)(nil),
	}
	file_atoms_splitter_private_observer_proto_msgTypes[1].OneofWrappers = []any{
		(*ObserverServerMessage_Session)(nil),
		(*ObserverServerMessage_Cluster)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_observer_proto_rawDesc), len(file_atoms_splitter_private_observer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_private_observer_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_observer_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_private_observer_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_observer_proto = out.File
	file_atoms_splitter_private_observer_proto_goTypes = nil
	file_atoms_splitter_private_observer_proto_depIdxs = nil
}
