// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: atoms/splitter/private/operation.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationService_RaftInfo_FullMethodName                = "/atoms.splitter.private.OperationService/RaftInfo"
	OperationService_Snapshot_FullMethodName                = "/atoms.splitter.private.OperationService/Snapshot"
	OperationService_Restore_FullMethodName                 = "/atoms.splitter.private.OperationService/Restore"
	OperationService_CoordinatorInfo_FullMethodName         = "/atoms.splitter.private.OperationService/CoordinatorInfo"
	OperationService_CoordinatorRestart_FullMethodName      = "/atoms.splitter.private.OperationService/CoordinatorRestart"
	OperationService_CoordinatorRevokeGrants_FullMethodName = "/atoms.splitter.private.OperationService/CoordinatorRevokeGrants"
	OperationService_CoordinatorClusterSync_FullMethodName  = "/atoms.splitter.private.OperationService/CoordinatorClusterSync"
	OperationService_ConsumerSuspend_FullMethodName         = "/atoms.splitter.private.OperationService/ConsumerSuspend"
	OperationService_ConsumerResume_FullMethodName          = "/atoms.splitter.private.OperationService/ConsumerResume"
	OperationService_ConsumerDrain_FullMethodName           = "/atoms.splitter.private.OperationService/ConsumerDrain"
)

// OperationServiceClient is the client API for OperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationServiceClient interface {
	RaftInfo(ctx context.Context, in *RaftInfoRequest, opts ...grpc.CallOption) (*RaftInfoResponse, error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	CoordinatorInfo(ctx context.Context, in *CoordinatorInfoRequest, opts ...grpc.CallOption) (*CoordinatorInfoResponse, error)
	CoordinatorRestart(ctx context.Context, in *CoordinatorRestartRequest, opts ...grpc.CallOption) (*CoordinatorRestartResponse, error)
	CoordinatorRevokeGrants(ctx context.Context, in *CoordinatorRevokeGrantsRequest, opts ...grpc.CallOption) (*CoordinatorRevokeGrantsResponse, error)
	CoordinatorClusterSync(ctx context.Context, in *CoordinatorClusterSyncRequest, opts ...grpc.CallOption) (*CoordinatorClusterSyncResponse, error)
	ConsumerSuspend(ctx context.Context, in *ConsumerSuspendRequest, opts ...grpc.CallOption) (*ConsumerSuspendResponse, error)
	ConsumerResume(ctx context.Context, in *ConsumerResumeRequest, opts ...grpc.CallOption) (*ConsumerResumeResponse, error)
	ConsumerDrain(ctx context.Context, in *ConsumerDrainRequest, opts ...grpc.CallOption) (*ConsumerDrainResponse, error)
}

type operationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationServiceClient(cc grpc.ClientConnInterface) OperationServiceClient {
	return &operationServiceClient{cc}
}

func (c *operationServiceClient) RaftInfo(ctx context.Context, in *RaftInfoRequest, opts ...grpc.CallOption) (*RaftInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaftInfoResponse)
	err := c.cc.Invoke(ctx, OperationService_RaftInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, OperationService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, OperationService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) CoordinatorInfo(ctx context.Context, in *CoordinatorInfoRequest, opts ...grpc.CallOption) (*CoordinatorInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorInfoResponse)
	err := c.cc.Invoke(ctx, OperationService_CoordinatorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) CoordinatorRestart(ctx context.Context, in *CoordinatorRestartRequest, opts ...grpc.CallOption) (*CoordinatorRestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorRestartResponse)
	err := c.cc.Invoke(ctx, OperationService_CoordinatorRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) CoordinatorRevokeGrants(ctx context.Context, in *CoordinatorRevokeGrantsRequest, opts ...grpc.CallOption) (*CoordinatorRevokeGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorRevokeGrantsResponse)
	err := c.cc.Invoke(ctx, OperationService_CoordinatorRevokeGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) CoordinatorClusterSync(ctx context.Context, in *CoordinatorClusterSyncRequest, opts ...grpc.CallOption) (*CoordinatorClusterSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorClusterSyncResponse)
	err := c.cc.Invoke(ctx, OperationService_CoordinatorClusterSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) ConsumerSuspend(ctx context.Context, in *ConsumerSuspendRequest, opts ...grpc.CallOption) (*ConsumerSuspendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumerSuspendResponse)
	err := c.cc.Invoke(ctx, OperationService_ConsumerSuspend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) ConsumerResume(ctx context.Context, in *ConsumerResumeRequest, opts ...grpc.CallOption) (*ConsumerResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumerResumeResponse)
	err := c.cc.Invoke(ctx, OperationService_ConsumerResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) ConsumerDrain(ctx context.Context, in *ConsumerDrainRequest, opts ...grpc.CallOption) (*ConsumerDrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumerDrainResponse)
	err := c.cc.Invoke(ctx, OperationService_ConsumerDrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationServiceServer is the server API for OperationService service.
// All implementations should embed UnimplementedOperationServiceServer
// for forward compatibility.
type OperationServiceServer interface {
	RaftInfo(context.Context, *RaftInfoRequest) (*RaftInfoResponse, error)
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	CoordinatorInfo(context.Context, *CoordinatorInfoRequest) (*CoordinatorInfoResponse, error)
	CoordinatorRestart(context.Context, *CoordinatorRestartRequest) (*CoordinatorRestartResponse, error)
	CoordinatorRevokeGrants(context.Context, *CoordinatorRevokeGrantsRequest) (*CoordinatorRevokeGrantsResponse, error)
	CoordinatorClusterSync(context.Context, *CoordinatorClusterSyncRequest) (*CoordinatorClusterSyncResponse, error)
	ConsumerSuspend(context.Context, *ConsumerSuspendRequest) (*ConsumerSuspendResponse, error)
	ConsumerResume(context.Context, *ConsumerResumeRequest) (*ConsumerResumeResponse, error)
	ConsumerDrain(context.Context, *ConsumerDrainRequest) (*ConsumerDrainResponse, error)
}

// UnimplementedOperationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationServiceServer struct{}

func (UnimplementedOperationServiceServer) RaftInfo(context.Context, *RaftInfoRequest) (*RaftInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RaftInfo not implemented")
}
func (UnimplementedOperationServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedOperationServiceServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedOperationServiceServer) CoordinatorInfo(context.Context, *CoordinatorInfoRequest) (*CoordinatorInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoordinatorInfo not implemented")
}
func (UnimplementedOperationServiceServer) CoordinatorRestart(context.Context, *CoordinatorRestartRequest) (*CoordinatorRestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoordinatorRestart not implemented")
}
func (UnimplementedOperationServiceServer) CoordinatorRevokeGrants(context.Context, *CoordinatorRevokeGrantsRequest) (*CoordinatorRevokeGrantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoordinatorRevokeGrants not implemented")
}
func (UnimplementedOperationServiceServer) CoordinatorClusterSync(context.Context, *CoordinatorClusterSyncRequest) (*CoordinatorClusterSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoordinatorClusterSync not implemented")
}
func (UnimplementedOperationServiceServer) ConsumerSuspend(context.Context, *ConsumerSuspendRequest) (*ConsumerSuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumerSuspend not implemented")
}
func (UnimplementedOperationServiceServer) ConsumerResume(context.Context, *ConsumerResumeRequest) (*ConsumerResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumerResume not implemented")
}
func (UnimplementedOperationServiceServer) ConsumerDrain(context.Context, *ConsumerDrainRequest) (*ConsumerDrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumerDrain not implemented")
}
func (UnimplementedOperationServiceServer) testEmbeddedByValue() {}

// UnsafeOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationServiceServer will
// result in compilation errors.
type UnsafeOperationServiceServer interface {
	mustEmbedUnimplementedOperationServiceServer()
}

func RegisterOperationServiceServer(s grpc.ServiceRegistrar, srv OperationServiceServer) {
	// If the following call pancis, it indicates UnimplementedOperationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationService_ServiceDesc, srv)
}

func _OperationService_RaftInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).RaftInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_RaftInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).RaftInfo(ctx, req.(*RaftInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_CoordinatorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).CoordinatorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_CoordinatorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).CoordinatorInfo(ctx, req.(*CoordinatorInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_CoordinatorRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).CoordinatorRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_CoordinatorRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).CoordinatorRestart(ctx, req.(*CoordinatorRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_CoordinatorRevokeGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorRevokeGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).CoordinatorRevokeGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_CoordinatorRevokeGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).CoordinatorRevokeGrants(ctx, req.(*CoordinatorRevokeGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_CoordinatorClusterSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorClusterSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).CoordinatorClusterSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_CoordinatorClusterSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).CoordinatorClusterSync(ctx, req.(*CoordinatorClusterSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_ConsumerSuspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerSuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).ConsumerSuspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_ConsumerSuspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).ConsumerSuspend(ctx, req.(*ConsumerSuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_ConsumerResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).ConsumerResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_ConsumerResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).ConsumerResume(ctx, req.(*ConsumerResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_ConsumerDrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerDrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).ConsumerDrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_ConsumerDrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).ConsumerDrain(ctx, req.(*ConsumerDrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationService_ServiceDesc is the grpc.ServiceDesc for OperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoms.splitter.private.OperationService",
	HandlerType: (*OperationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RaftInfo",
			Handler:    _OperationService_RaftInfo_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _OperationService_Snapshot_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _OperationService_Restore_Handler,
		},
		{
			MethodName: "CoordinatorInfo",
			Handler:    _OperationService_CoordinatorInfo_Handler,
		},
		{
			MethodName: "CoordinatorRestart",
			Handler:    _OperationService_CoordinatorRestart_Handler,
		},
		{
			MethodName: "CoordinatorRevokeGrants",
			Handler:    _OperationService_CoordinatorRevokeGrants_Handler,
		},
		{
			MethodName: "CoordinatorClusterSync",
			Handler:    _OperationService_CoordinatorClusterSync_Handler,
		},
		{
			MethodName: "ConsumerSuspend",
			Handler:    _OperationService_ConsumerSuspend_Handler,
		},
		{
			MethodName: "ConsumerResume",
			Handler:    _OperationService_ConsumerResume_Handler,
		},
		{
			MethodName: "ConsumerDrain",
			Handler:    _OperationService_ConsumerDrain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoms/splitter/private/operation.proto",
}
