// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/operation.proto

package private

import (
	pb "go.atoms.co/splitter/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumer      *pb.Instance           `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Joined        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined,proto3" json:"joined,omitempty"`
	NamedKeys     []*pb.DomainKeyName    `protobuf:"bytes,3,rep,name=named_keys,json=namedKeys,proto3" json:"named_keys,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceInfo) GetConsumer() *pb.Instance {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *InstanceInfo) GetJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.Joined
	}
	return nil
}

func (x *InstanceInfo) GetNamedKeys() []*pb.DomainKeyName {
	if x != nil {
		return x.NamedKeys
	}
	return nil
}

func (x *InstanceInfo) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RaftInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftInfoRequest) Reset() {
	*x = RaftInfoRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftInfoRequest) ProtoMessage() {}

func (x *RaftInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftInfoRequest.ProtoReflect.Descriptor instead.
func (*RaftInfoRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{1}
}

type RaftInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaftState     map[string]string      `protobuf:"bytes,1,rep,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftInfoResponse) Reset() {
	*x = RaftInfoResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftInfoResponse) ProtoMessage() {}

func (x *RaftInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftInfoResponse.ProtoReflect.Descriptor instead.
func (*RaftInfoResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{2}
}

func (x *RaftInfoResponse) GetRaftState() map[string]string {
	if x != nil {
		return x.RaftState
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{3}
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nuke          bool                   `protobuf:"varint,1,opt,name=nuke,proto3" json:"nuke,omitempty"`
	Snapshot      *Snapshot              `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreRequest) GetNuke() bool {
	if x != nil {
		return x.Nuke
	}
	return false
}

func (x *RestoreRequest) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type CoordinatorInfoRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorInfoRequest) Reset() {
	*x = CoordinatorInfoRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorInfoRequest) ProtoMessage() {}

func (x *CoordinatorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorInfoRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorInfoRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{7}
}

func (x *CoordinatorInfoRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

type CoordinatorInfoResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Consumers     []*pb.Instance              `protobuf:"bytes,1,rep,name=consumers,proto3" json:"consumers,omitempty"`
	Snapshot      *pb.ClusterMessage_Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Infos         []*InstanceInfo             `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorInfoResponse) Reset() {
	*x = CoordinatorInfoResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorInfoResponse) ProtoMessage() {}

func (x *CoordinatorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorInfoResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorInfoResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{8}
}

func (x *CoordinatorInfoResponse) GetConsumers() []*pb.Instance {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *CoordinatorInfoResponse) GetSnapshot() *pb.ClusterMessage_Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *CoordinatorInfoResponse) GetInfos() []*InstanceInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type CoordinatorRestartRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorRestartRequest) Reset() {
	*x = CoordinatorRestartRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorRestartRequest) ProtoMessage() {}

func (x *CoordinatorRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorRestartRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorRestartRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{9}
}

func (x *CoordinatorRestartRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

type CoordinatorRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorRestartResponse) Reset() {
	*x = CoordinatorRestartResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorRestartResponse) ProtoMessage() {}

func (x *CoordinatorRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorRestartResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorRestartResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{10}
}

type CoordinatorClusterSyncRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorClusterSyncRequest) Reset() {
	*x = CoordinatorClusterSyncRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorClusterSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorClusterSyncRequest) ProtoMessage() {}

func (x *CoordinatorClusterSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorClusterSyncRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorClusterSyncRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{11}
}

func (x *CoordinatorClusterSyncRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

type CoordinatorClusterSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorClusterSyncResponse) Reset() {
	*x = CoordinatorClusterSyncResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorClusterSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorClusterSyncResponse) ProtoMessage() {}

func (x *CoordinatorClusterSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorClusterSyncResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorClusterSyncResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{12}
}

type CoordinatorRevokeGrantsRequest struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName                         `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Grants        []*CoordinatorRevokeGrantsRequest_ConsumerGrants `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorRevokeGrantsRequest) Reset() {
	*x = CoordinatorRevokeGrantsRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorRevokeGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorRevokeGrantsRequest) ProtoMessage() {}

func (x *CoordinatorRevokeGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorRevokeGrantsRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorRevokeGrantsRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{13}
}

func (x *CoordinatorRevokeGrantsRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *CoordinatorRevokeGrantsRequest) GetGrants() []*CoordinatorRevokeGrantsRequest_ConsumerGrants {
	if x != nil {
		return x.Grants
	}
	return nil
}

type CoordinatorRevokeGrantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorRevokeGrantsResponse) Reset() {
	*x = CoordinatorRevokeGrantsResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorRevokeGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorRevokeGrantsResponse) ProtoMessage() {}

func (x *CoordinatorRevokeGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorRevokeGrantsResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorRevokeGrantsResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{14}
}

type ConsumerSuspendRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	ConsumerId    string                   `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerSuspendRequest) Reset() {
	*x = ConsumerSuspendRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerSuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerSuspendRequest) ProtoMessage() {}

func (x *ConsumerSuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerSuspendRequest.ProtoReflect.Descriptor instead.
func (*ConsumerSuspendRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{15}
}

func (x *ConsumerSuspendRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ConsumerSuspendRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type ConsumerSuspendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerSuspendResponse) Reset() {
	*x = ConsumerSuspendResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerSuspendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerSuspendResponse) ProtoMessage() {}

func (x *ConsumerSuspendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerSuspendResponse.ProtoReflect.Descriptor instead.
func (*ConsumerSuspendResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{16}
}

type ConsumerResumeRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	ConsumerId    string                   `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerResumeRequest) Reset() {
	*x = ConsumerResumeRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerResumeRequest) ProtoMessage() {}

func (x *ConsumerResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerResumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumerResumeRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{17}
}

func (x *ConsumerResumeRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ConsumerResumeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type ConsumerResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerResumeResponse) Reset() {
	*x = ConsumerResumeResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerResumeResponse) ProtoMessage() {}

func (x *ConsumerResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerResumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumerResumeResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{18}
}

type ConsumerDrainRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *pb.QualifiedServiceName `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	ConsumerId    string                   `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerDrainRequest) Reset() {
	*x = ConsumerDrainRequest{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerDrainRequest) ProtoMessage() {}

func (x *ConsumerDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerDrainRequest.ProtoReflect.Descriptor instead.
func (*ConsumerDrainRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{19}
}

func (x *ConsumerDrainRequest) GetService() *pb.QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ConsumerDrainRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type ConsumerDrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerDrainResponse) Reset() {
	*x = ConsumerDrainResponse{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerDrainResponse) ProtoMessage() {}

func (x *ConsumerDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerDrainResponse.ProtoReflect.Descriptor instead.
func (*ConsumerDrainResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{20}
}

type CoordinatorRevokeGrantsRequest_ConsumerGrants struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumer      string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Grants        []string               `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorRevokeGrantsRequest_ConsumerGrants) Reset() {
	*x = CoordinatorRevokeGrantsRequest_ConsumerGrants{}
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorRevokeGrantsRequest_ConsumerGrants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorRevokeGrantsRequest_ConsumerGrants) ProtoMessage() {}

func (x *CoordinatorRevokeGrantsRequest_ConsumerGrants) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_operation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorRevokeGrantsRequest_ConsumerGrants.ProtoReflect.Descriptor instead.
func (*CoordinatorRevokeGrantsRequest_ConsumerGrants) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_operation_proto_rawDescGZIP(), []int{13, 0}
}

func (x *CoordinatorRevokeGrantsRequest_ConsumerGrants) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *CoordinatorRevokeGrantsRequest_ConsumerGrants) GetGrants() []string {
	if x != nil {
		return x.Grants
	}
	return nil
}

var File_atoms_splitter_private_operation_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_operation_proto_rawDesc = "" +
	"\n" +
	"&atoms/splitter/private/operation.proto\x12\x16atoms.splitter.private\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"atoms/splitter/private/state.proto\x1a\x1catoms/splitter/cluster.proto\x1a\x1aatoms/splitter/model.proto\"\xcc\x01\n" +
	"\fInstanceInfo\x124\n" +
	"\bconsumer\x18\x01 \x01(\v2\x18.atoms.splitter.InstanceR\bconsumer\x122\n" +
	"\x06joined\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06joined\x12<\n" +
	"\n" +
	"named_keys\x18\x03 \x03(\v2\x1d.atoms.splitter.DomainKeyNameR\tnamedKeys\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limit\"\x11\n" +
	"\x0fRaftInfoRequest\"\xa8\x01\n" +
	"\x10RaftInfoResponse\x12V\n" +
	"\n" +
	"raft_state\x18\x01 \x03(\v27.atoms.splitter.private.RaftInfoResponse.RaftStateEntryR\traftState\x1a<\n" +
	"\x0eRaftStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fSnapshotRequest\"P\n" +
	"\x10SnapshotResponse\x12<\n" +
	"\bsnapshot\x18\x01 \x01(\v2 .atoms.splitter.private.SnapshotR\bsnapshot\"b\n" +
	"\x0eRestoreRequest\x12\x12\n" +
	"\x04nuke\x18\x01 \x01(\bR\x04nuke\x12<\n" +
	"\bsnapshot\x18\x02 \x01(\v2 .atoms.splitter.private.SnapshotR\bsnapshot\"O\n" +
	"\x0fRestoreResponse\x12<\n" +
	"\bsnapshot\x18\x01 \x01(\v2 .atoms.splitter.private.SnapshotR\bsnapshot\"X\n" +
	"\x16CoordinatorInfoRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\"\xd2\x01\n" +
	"\x17CoordinatorInfoResponse\x126\n" +
	"\tconsumers\x18\x01 \x03(\v2\x18.atoms.splitter.InstanceR\tconsumers\x12C\n" +
	"\bsnapshot\x18\x02 \x01(\v2'.atoms.splitter.ClusterMessage.SnapshotR\bsnapshot\x12:\n" +
	"\x05infos\x18\x03 \x03(\v2$.atoms.splitter.private.InstanceInfoR\x05infos\"[\n" +
	"\x19CoordinatorRestartRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\"\x1c\n" +
	"\x1aCoordinatorRestartResponse\"_\n" +
	"\x1dCoordinatorClusterSyncRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\" \n" +
	"\x1eCoordinatorClusterSyncResponse\"\x85\x02\n" +
	"\x1eCoordinatorRevokeGrantsRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12]\n" +
	"\x06grants\x18\x02 \x03(\v2E.atoms.splitter.private.CoordinatorRevokeGrantsRequest.ConsumerGrantsR\x06grants\x1aD\n" +
	"\x0eConsumerGrants\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06grants\x18\x02 \x03(\tR\x06grants\"!\n" +
	"\x1fCoordinatorRevokeGrantsResponse\"y\n" +
	"\x16ConsumerSuspendRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\"\x19\n" +
	"\x17ConsumerSuspendResponse\"x\n" +
	"\x15ConsumerResumeRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\"\x18\n" +
	"\x16ConsumerResumeResponse\"w\n" +
	"\x14ConsumerDrainRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\"\x17\n" +
	"\x15ConsumerDrainResponse2\x87\t\n" +
	"\x10OperationService\x12]\n" +
	"\bRaftInfo\x12'.atoms.splitter.private.RaftInfoRequest\x1a(.atoms.splitter.private.RaftInfoResponse\x12]\n" +
	"\bSnapshot\x12'.atoms.splitter.private.SnapshotRequest\x1a(.atoms.splitter.private.SnapshotResponse\x12Z\n" +
	"\aRestore\x12&.atoms.splitter.private.RestoreRequest\x1a'.atoms.splitter.private.RestoreResponse\x12r\n" +
	"\x0fCoordinatorInfo\x12..atoms.splitter.private.CoordinatorInfoRequest\x1a/.atoms.splitter.private.CoordinatorInfoResponse\x12{\n" +
	"\x12CoordinatorRestart\x121.atoms.splitter.private.CoordinatorRestartRequest\x1a2.atoms.splitter.private.CoordinatorRestartResponse\x12\x8a\x01\n" +
	"\x17CoordinatorRevokeGrants\x126.atoms.splitter.private.CoordinatorRevokeGrantsRequest\x1a7.atoms.splitter.private.CoordinatorRevokeGrantsResponse\x12\x87\x01\n" +
	"\x16CoordinatorClusterSync\x125.atoms.splitter.private.CoordinatorClusterSyncRequest\x1a6.atoms.splitter.private.CoordinatorClusterSyncResponse\x12r\n" +
	"\x0fConsumerSuspend\x12..atoms.splitter.private.ConsumerSuspendRequest\x1a/.atoms.splitter.private.ConsumerSuspendResponse\x12o\n" +
	"\x0eConsumerResume\x12-.atoms.splitter.private.ConsumerResumeRequest\x1a..atoms.splitter.private.ConsumerResumeResponse\x12l\n" +
	"\rConsumerDrain\x12,.atoms.splitter.private.ConsumerDrainRequest\x1a-.atoms.splitter.private.ConsumerDrainResponseB!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_operation_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_operation_proto_rawDescData []byte
)

func file_atoms_splitter_private_operation_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_operation_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_operation_proto_rawDesc), len(file_atoms_splitter_private_operation_proto_rawDesc)))
	})
	return file_atoms_splitter_private_operation_proto_rawDescData
}

var file_atoms_splitter_private_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_atoms_splitter_private_operation_proto_goTypes = []any{
	(*InstanceInfo)(nil),                                  // 0: atoms.splitter.private.InstanceInfo
	(*RaftInfoRequest)(nil),                               // 1: atoms.splitter.private.RaftInfoRequest
	(*RaftInfoResponse)(nil),                              // 2: atoms.splitter.private.RaftInfoResponse
	(*SnapshotRequest)(nil),                               // 3: atoms.splitter.private.SnapshotRequest
	(*SnapshotResponse)(nil),                              // 4: atoms.splitter.private.SnapshotResponse
	(*RestoreRequest)(nil),                                // 5: atoms.splitter.private.RestoreRequest
	(*RestoreResponse)(nil),                               // 6: atoms.splitter.private.RestoreResponse
	(*CoordinatorInfoRequest)(nil),                        // 7: atoms.splitter.private.CoordinatorInfoRequest
	(*CoordinatorInfoResponse)(nil),                       // 8: atoms.splitter.private.CoordinatorInfoResponse
	(*CoordinatorRestartRequest)(nil),                     // 9: atoms.splitter.private.CoordinatorRestartRequest
	(*CoordinatorRestartResponse)(nil),                    // 10: atoms.splitter.private.CoordinatorRestartResponse
	(*CoordinatorClusterSyncRequest)(nil),                 // 11: atoms.splitter.private.CoordinatorClusterSyncRequest
	(*CoordinatorClusterSyncResponse)(nil),                // 12: atoms.splitter.private.CoordinatorClusterSyncResponse
	(*CoordinatorRevokeGrantsRequest)(nil),                // 13: atoms.splitter.private.CoordinatorRevokeGrantsRequest
	(*CoordinatorRevokeGrantsResponse)(nil),               // 14: atoms.splitter.private.CoordinatorRevokeGrantsResponse
	(*ConsumerSuspendRequest)(nil),                        // 15: atoms.splitter.private.ConsumerSuspendRequest
	(*ConsumerSuspendResponse)(nil),                       // 16: atoms.splitter.private.ConsumerSuspendResponse
	(*ConsumerResumeRequest)(nil),                         // 17: atoms.splitter.private.ConsumerResumeRequest
	(*ConsumerResumeResponse)(nil),                        // 18: atoms.splitter.private.ConsumerResumeResponse
	(*ConsumerDrainRequest)(nil),                          // 19: atoms.splitter.private.ConsumerDrainRequest
	(*ConsumerDrainResponse)(nil),                         // 20: atoms.splitter.private.ConsumerDrainResponse
	nil,                                                   // 21: atoms.splitter.private.RaftInfoResponse.RaftStateEntry
	(*CoordinatorRevokeGrantsRequest_ConsumerGrants)(nil), // 22: atoms.splitter.private.CoordinatorRevokeGrantsRequest.ConsumerGrants
	(*pb.Instance)(nil),                                   // 23: atoms.splitter.Instance
	(*timestamppb.Timestamp)(nil),                         // 24: google.protobuf.Timestamp
	(*pb.DomainKeyName)(nil),                              // 25: atoms.splitter.DomainKeyName
	(*Snapshot)(nil),                                      // 26: atoms.splitter.private.Snapshot
	(*pb.QualifiedServiceName)(nil),                       // 27: atoms.splitter.QualifiedServiceName
	(*pb.ClusterMessage_Snapshot)(nil),                    // 28: atoms.splitter.ClusterMessage.Snapshot
}
var file_atoms_splitter_private_operation_proto_depIdxs = []int32{
	23, // 0: atoms.splitter.private.InstanceInfo.consumer:type_name -> atoms.splitter.Instance
	24, // 1: atoms.splitter.private.InstanceInfo.joined:type_name -> google.protobuf.Timestamp
	25, // 2: atoms.splitter.private.InstanceInfo.named_keys:type_name -> atoms.splitter.DomainKeyName
	21, // 3: atoms.splitter.private.RaftInfoResponse.raft_state:type_name -> atoms.splitter.private.RaftInfoResponse.RaftStateEntry
	26, // 4: atoms.splitter.private.SnapshotResponse.snapshot:type_name -> atoms.splitter.private.Snapshot
	26, // 5: atoms.splitter.private.RestoreRequest.snapshot:type_name -> atoms.splitter.private.Snapshot
	26, // 6: atoms.splitter.private.RestoreResponse.snapshot:type_name -> atoms.splitter.private.Snapshot
	27, // 7: atoms.splitter.private.CoordinatorInfoRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	23, // 8: atoms.splitter.private.CoordinatorInfoResponse.consumers:type_name -> atoms.splitter.Instance
	28, // 9: atoms.splitter.private.CoordinatorInfoResponse.snapshot:type_name -> atoms.splitter.ClusterMessage.Snapshot
	0,  // 10: atoms.splitter.private.CoordinatorInfoResponse.infos:type_name -> atoms.splitter.private.InstanceInfo
	27, // 11: atoms.splitter.private.CoordinatorRestartRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	27, // 12: atoms.splitter.private.CoordinatorClusterSyncRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	27, // 13: atoms.splitter.private.CoordinatorRevokeGrantsRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	22, // 14: atoms.splitter.private.CoordinatorRevokeGrantsRequest.grants:type_name -> atoms.splitter.private.CoordinatorRevokeGrantsRequest.ConsumerGrants
	27, // 15: atoms.splitter.private.ConsumerSuspendRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	27, // 16: atoms.splitter.private.ConsumerResumeRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	27, // 17: atoms.splitter.private.ConsumerDrainRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	1,  // 18: atoms.splitter.private.OperationService.RaftInfo:input_type -> atoms.splitter.private.RaftInfoRequest
	3,  // 19: atoms.splitter.private.OperationService.Snapshot:input_type -> atoms.splitter.private.SnapshotRequest
	5,  // 20: atoms.splitter.private.OperationService.Restore:input_type -> atoms.splitter.private.RestoreRequest
	7,  // 21: atoms.splitter.private.OperationService.CoordinatorInfo:input_type -> atoms.splitter.private.CoordinatorInfoRequest
	9,  // 22: atoms.splitter.private.OperationService.CoordinatorRestart:input_type -> atoms.splitter.private.CoordinatorRestartRequest
	13, // 23: atoms.splitter.private.OperationService.CoordinatorRevokeGrants:input_type -> atoms.splitter.private.CoordinatorRevokeGrantsRequest
	11, // 24: atoms.splitter.private.OperationService.CoordinatorClusterSync:input_type -> atoms.splitter.private.CoordinatorClusterSyncRequest
	15, // 25: atoms.splitter.private.OperationService.ConsumerSuspend:input_type -> atoms.splitter.private.ConsumerSuspendRequest
	17, // 26: atoms.splitter.private.OperationService.ConsumerResume:input_type -> atoms.splitter.private.ConsumerResumeRequest
	19, // 27: atoms.splitter.private.OperationService.ConsumerDrain:input_type -> atoms.splitter.private.ConsumerDrainRequest
	2,  // 28: atoms.splitter.private.OperationService.RaftInfo:output_type -> atoms.splitter.private.RaftInfoResponse
	4,  // 29: atoms.splitter.private.OperationService.Snapshot:output_type -> atoms.splitter.private.SnapshotResponse
	6,  // 30: atoms.splitter.private.OperationService.Restore:output_type -> atoms.splitter.private.RestoreResponse
	8,  // 31: atoms.splitter.private.OperationService.CoordinatorInfo:output_type -> atoms.splitter.private.CoordinatorInfoResponse
	10, // 32: atoms.splitter.private.OperationService.CoordinatorRestart:output_type -> atoms.splitter.private.CoordinatorRestartResponse
	14, // 33: atoms.splitter.private.OperationService.CoordinatorRevokeGrants:output_type -> atoms.splitter.private.CoordinatorRevokeGrantsResponse
	12, // 34: atoms.splitter.private.OperationService.CoordinatorClusterSync:output_type -> atoms.splitter.private.CoordinatorClusterSyncResponse
	16, // 35: atoms.splitter.private.OperationService.ConsumerSuspend:output_type -> atoms.splitter.private.ConsumerSuspendResponse
	18, // 36: atoms.splitter.private.OperationService.ConsumerResume:output_type -> atoms.splitter.private.ConsumerResumeResponse
	20, // 37: atoms.splitter.private.OperationService.ConsumerDrain:output_type -> atoms.splitter.private.ConsumerDrainResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_operation_proto_init() }
func file_atoms_splitter_private_operation_proto_init() {
	if File_atoms_splitter_private_operation_proto != nil {
		return
	}
	file_atoms_splitter_private_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_operation_proto_rawDesc), len(file_atoms_splitter_private_operation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_private_operation_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_operation_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_private_operation_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_operation_proto = out.File
	file_atoms_splitter_private_operation_proto_goTypes = nil
	file_atoms_splitter_private_operation_proto_depIdxs = nil
}
