// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: atoms/splitter/private/placement.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacementManagementService_List_FullMethodName   = "/atoms.splitter.private.PlacementManagementService/List"
	PlacementManagementService_New_FullMethodName    = "/atoms.splitter.private.PlacementManagementService/New"
	PlacementManagementService_Info_FullMethodName   = "/atoms.splitter.private.PlacementManagementService/Info"
	PlacementManagementService_Update_FullMethodName = "/atoms.splitter.private.PlacementManagementService/Update"
	PlacementManagementService_Delete_FullMethodName = "/atoms.splitter.private.PlacementManagementService/Delete"
)

// PlacementManagementServiceClient is the client API for PlacementManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlacementManagementServiceClient interface {
	List(ctx context.Context, in *ListPlacementsRequest, opts ...grpc.CallOption) (*ListPlacementsResponse, error)
	New(ctx context.Context, in *NewPlacementRequest, opts ...grpc.CallOption) (*NewPlacementResponse, error)
	Info(ctx context.Context, in *InfoPlacementRequest, opts ...grpc.CallOption) (*InfoPlacementResponse, error)
	Update(ctx context.Context, in *UpdatePlacementRequest, opts ...grpc.CallOption) (*UpdatePlacementResponse, error)
	Delete(ctx context.Context, in *DeletePlacementRequest, opts ...grpc.CallOption) (*DeletePlacementResponse, error)
}

type placementManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementManagementServiceClient(cc grpc.ClientConnInterface) PlacementManagementServiceClient {
	return &placementManagementServiceClient{cc}
}

func (c *placementManagementServiceClient) List(ctx context.Context, in *ListPlacementsRequest, opts ...grpc.CallOption) (*ListPlacementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlacementsResponse)
	err := c.cc.Invoke(ctx, PlacementManagementService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementManagementServiceClient) New(ctx context.Context, in *NewPlacementRequest, opts ...grpc.CallOption) (*NewPlacementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewPlacementResponse)
	err := c.cc.Invoke(ctx, PlacementManagementService_New_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementManagementServiceClient) Info(ctx context.Context, in *InfoPlacementRequest, opts ...grpc.CallOption) (*InfoPlacementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoPlacementResponse)
	err := c.cc.Invoke(ctx, PlacementManagementService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementManagementServiceClient) Update(ctx context.Context, in *UpdatePlacementRequest, opts ...grpc.CallOption) (*UpdatePlacementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlacementResponse)
	err := c.cc.Invoke(ctx, PlacementManagementService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementManagementServiceClient) Delete(ctx context.Context, in *DeletePlacementRequest, opts ...grpc.CallOption) (*DeletePlacementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlacementResponse)
	err := c.cc.Invoke(ctx, PlacementManagementService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementManagementServiceServer is the server API for PlacementManagementService service.
// All implementations should embed UnimplementedPlacementManagementServiceServer
// for forward compatibility.
type PlacementManagementServiceServer interface {
	List(context.Context, *ListPlacementsRequest) (*ListPlacementsResponse, error)
	New(context.Context, *NewPlacementRequest) (*NewPlacementResponse, error)
	Info(context.Context, *InfoPlacementRequest) (*InfoPlacementResponse, error)
	Update(context.Context, *UpdatePlacementRequest) (*UpdatePlacementResponse, error)
	Delete(context.Context, *DeletePlacementRequest) (*DeletePlacementResponse, error)
}

// UnimplementedPlacementManagementServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacementManagementServiceServer struct{}

func (UnimplementedPlacementManagementServiceServer) List(context.Context, *ListPlacementsRequest) (*ListPlacementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPlacementManagementServiceServer) New(context.Context, *NewPlacementRequest) (*NewPlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}
func (UnimplementedPlacementManagementServiceServer) Info(context.Context, *InfoPlacementRequest) (*InfoPlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedPlacementManagementServiceServer) Update(context.Context, *UpdatePlacementRequest) (*UpdatePlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPlacementManagementServiceServer) Delete(context.Context, *DeletePlacementRequest) (*DeletePlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPlacementManagementServiceServer) testEmbeddedByValue() {}

// UnsafePlacementManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementManagementServiceServer will
// result in compilation errors.
type UnsafePlacementManagementServiceServer interface {
	mustEmbedUnimplementedPlacementManagementServiceServer()
}

func RegisterPlacementManagementServiceServer(s grpc.ServiceRegistrar, srv PlacementManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlacementManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacementManagementService_ServiceDesc, srv)
}

func _PlacementManagementService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlacementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementManagementServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementManagementService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementManagementServiceServer).List(ctx, req.(*ListPlacementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementManagementService_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPlacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementManagementServiceServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementManagementService_New_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementManagementServiceServer).New(ctx, req.(*NewPlacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementManagementService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoPlacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementManagementServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementManagementService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementManagementServiceServer).Info(ctx, req.(*InfoPlacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementManagementService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementManagementServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementManagementService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementManagementServiceServer).Update(ctx, req.(*UpdatePlacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementManagementService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementManagementServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementManagementService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementManagementServiceServer).Delete(ctx, req.(*DeletePlacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacementManagementService_ServiceDesc is the grpc.ServiceDesc for PlacementManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoms.splitter.private.PlacementManagementService",
	HandlerType: (*PlacementManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PlacementManagementService_List_Handler,
		},
		{
			MethodName: "New",
			Handler:    _PlacementManagementService_New_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _PlacementManagementService_Info_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PlacementManagementService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PlacementManagementService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoms/splitter/private/placement.proto",
}
