// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/placement.proto

package private

import (
	pb "go.atoms.co/splitter/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalPlacement_State int32

const (
	InternalPlacement_UNKNOWN        InternalPlacement_State = 0
	InternalPlacement_ACTIVE         InternalPlacement_State = 1
	InternalPlacement_SUSPENDED      InternalPlacement_State = 2
	InternalPlacement_DECOMMISSIONED InternalPlacement_State = 3
)

// Enum value maps for InternalPlacement_State.
var (
	InternalPlacement_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "SUSPENDED",
		3: "DECOMMISSIONED",
	}
	InternalPlacement_State_value = map[string]int32{
		"UNKNOWN":        0,
		"ACTIVE":         1,
		"SUSPENDED":      2,
		"DECOMMISSIONED": 3,
	}
)

func (x InternalPlacement_State) Enum() *InternalPlacement_State {
	p := new(InternalPlacement_State)
	*p = x
	return p
}

func (x InternalPlacement_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalPlacement_State) Descriptor() protoreflect.EnumDescriptor {
	return file_atoms_splitter_private_placement_proto_enumTypes[0].Descriptor()
}

func (InternalPlacement_State) Type() protoreflect.EnumType {
	return &file_atoms_splitter_private_placement_proto_enumTypes[0]
}

func (x InternalPlacement_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalPlacement_State.Descriptor instead.
func (InternalPlacement_State) EnumDescriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{1, 0}
}

type BlockDistribution struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Region        string                     `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Splits        []*BlockDistribution_Split `protobuf:"bytes,2,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDistribution) Reset() {
	*x = BlockDistribution{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDistribution) ProtoMessage() {}

func (x *BlockDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDistribution.ProtoReflect.Descriptor instead.
func (*BlockDistribution) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{0}
}

func (x *BlockDistribution) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BlockDistribution) GetSplits() []*BlockDistribution_Split {
	if x != nil {
		return x.Splits
	}
	return nil
}

type InternalPlacement struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          *pb.QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         InternalPlacement_State    `protobuf:"varint,2,opt,name=state,proto3,enum=atoms.splitter.private.InternalPlacement_State" json:"state,omitempty"`
	Config        *InternalPlacement_Config  `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Created       *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalPlacement) Reset() {
	*x = InternalPlacement{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPlacement) ProtoMessage() {}

func (x *InternalPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPlacement.ProtoReflect.Descriptor instead.
func (*InternalPlacement) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{1}
}

func (x *InternalPlacement) GetName() *pb.QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *InternalPlacement) GetState() InternalPlacement_State {
	if x != nil {
		return x.State
	}
	return InternalPlacement_UNKNOWN
}

func (x *InternalPlacement) GetConfig() *InternalPlacement_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InternalPlacement) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type ListPlacementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlacementsRequest) Reset() {
	*x = ListPlacementsRequest{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlacementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlacementsRequest) ProtoMessage() {}

func (x *ListPlacementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlacementsRequest.ProtoReflect.Descriptor instead.
func (*ListPlacementsRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{2}
}

func (x *ListPlacementsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type InternalPlacementInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placement     *InternalPlacement     `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalPlacementInfo) Reset() {
	*x = InternalPlacementInfo{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalPlacementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPlacementInfo) ProtoMessage() {}

func (x *InternalPlacementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPlacementInfo.ProtoReflect.Descriptor instead.
func (*InternalPlacementInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{3}
}

func (x *InternalPlacementInfo) GetPlacement() *InternalPlacement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *InternalPlacementInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InternalPlacementInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListPlacementsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Info          []*InternalPlacementInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlacementsResponse) Reset() {
	*x = ListPlacementsResponse{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlacementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlacementsResponse) ProtoMessage() {}

func (x *ListPlacementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlacementsResponse.ProtoReflect.Descriptor instead.
func (*ListPlacementsResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlacementsResponse) GetInfo() []*InternalPlacementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type NewPlacementRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          *pb.QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *InternalPlacement_Config  `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPlacementRequest) Reset() {
	*x = NewPlacementRequest{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPlacementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPlacementRequest) ProtoMessage() {}

func (x *NewPlacementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPlacementRequest.ProtoReflect.Descriptor instead.
func (*NewPlacementRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{5}
}

func (x *NewPlacementRequest) GetName() *pb.QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *NewPlacementRequest) GetConfig() *InternalPlacement_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type NewPlacementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *InternalPlacementInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPlacementResponse) Reset() {
	*x = NewPlacementResponse{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPlacementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPlacementResponse) ProtoMessage() {}

func (x *NewPlacementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPlacementResponse.ProtoReflect.Descriptor instead.
func (*NewPlacementResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{6}
}

func (x *NewPlacementResponse) GetInfo() *InternalPlacementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type InfoPlacementRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          *pb.QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoPlacementRequest) Reset() {
	*x = InfoPlacementRequest{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoPlacementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPlacementRequest) ProtoMessage() {}

func (x *InfoPlacementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPlacementRequest.ProtoReflect.Descriptor instead.
func (*InfoPlacementRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{7}
}

func (x *InfoPlacementRequest) GetName() *pb.QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

type InfoPlacementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *InternalPlacementInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoPlacementResponse) Reset() {
	*x = InfoPlacementResponse{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoPlacementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPlacementResponse) ProtoMessage() {}

func (x *InfoPlacementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPlacementResponse.ProtoReflect.Descriptor instead.
func (*InfoPlacementResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{8}
}

func (x *InfoPlacementResponse) GetInfo() *InternalPlacementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdatePlacementRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          *pb.QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	State         InternalPlacement_State    `protobuf:"varint,3,opt,name=state,proto3,enum=atoms.splitter.private.InternalPlacement_State" json:"state,omitempty"`
	Config        *InternalPlacement_Config  `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlacementRequest) Reset() {
	*x = UpdatePlacementRequest{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlacementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlacementRequest) ProtoMessage() {}

func (x *UpdatePlacementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlacementRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlacementRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePlacementRequest) GetName() *pb.QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdatePlacementRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdatePlacementRequest) GetState() InternalPlacement_State {
	if x != nil {
		return x.State
	}
	return InternalPlacement_UNKNOWN
}

func (x *UpdatePlacementRequest) GetConfig() *InternalPlacement_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdatePlacementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *InternalPlacementInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlacementResponse) Reset() {
	*x = UpdatePlacementResponse{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlacementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlacementResponse) ProtoMessage() {}

func (x *UpdatePlacementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlacementResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlacementResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePlacementResponse) GetInfo() *InternalPlacementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DeletePlacementRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          *pb.QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlacementRequest) Reset() {
	*x = DeletePlacementRequest{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlacementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlacementRequest) ProtoMessage() {}

func (x *DeletePlacementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlacementRequest.ProtoReflect.Descriptor instead.
func (*DeletePlacementRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePlacementRequest) GetName() *pb.QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

type DeletePlacementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlacementResponse) Reset() {
	*x = DeletePlacementResponse{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlacementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlacementResponse) ProtoMessage() {}

func (x *DeletePlacementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlacementResponse.ProtoReflect.Descriptor instead.
func (*DeletePlacementResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{12}
}

type BlockDistribution_Split struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         int64                  `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDistribution_Split) Reset() {
	*x = BlockDistribution_Split{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDistribution_Split) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDistribution_Split) ProtoMessage() {}

func (x *BlockDistribution_Split) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDistribution_Split.ProtoReflect.Descriptor instead.
func (*BlockDistribution_Split) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BlockDistribution_Split) GetBlock() int64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *BlockDistribution_Split) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type InternalPlacement_Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Target         *BlockDistribution     `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Current        *BlockDistribution     `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	BlocksPerCycle int32                  `protobuf:"varint,3,opt,name=blocks_per_cycle,json=blocksPerCycle,proto3" json:"blocks_per_cycle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InternalPlacement_Config) Reset() {
	*x = InternalPlacement_Config{}
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalPlacement_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPlacement_Config) ProtoMessage() {}

func (x *InternalPlacement_Config) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_placement_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPlacement_Config.ProtoReflect.Descriptor instead.
func (*InternalPlacement_Config) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_placement_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InternalPlacement_Config) GetTarget() *BlockDistribution {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InternalPlacement_Config) GetCurrent() *BlockDistribution {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *InternalPlacement_Config) GetBlocksPerCycle() int32 {
	if x != nil {
		return x.BlocksPerCycle
	}
	return 0
}

var File_atoms_splitter_private_placement_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_placement_proto_rawDesc = "" +
	"\n" +
	"&atoms/splitter/private/placement.proto\x12\x16atoms.splitter.private\x1a\x1eatoms/splitter/placement.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x11BlockDistribution\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12G\n" +
	"\x06splits\x18\x02 \x03(\v2/.atoms.splitter.private.BlockDistribution.SplitR\x06splits\x1a5\n" +
	"\x05Split\x12\x14\n" +
	"\x05block\x18\x01 \x01(\x03R\x05block\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"\x98\x04\n" +
	"\x11InternalPlacement\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\x12E\n" +
	"\x05state\x18\x02 \x01(\x0e2/.atoms.splitter.private.InternalPlacement.StateR\x05state\x12H\n" +
	"\x06config\x18\x03 \x01(\v20.atoms.splitter.private.InternalPlacement.ConfigR\x06config\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x1a\xba\x01\n" +
	"\x06Config\x12A\n" +
	"\x06target\x18\x01 \x01(\v2).atoms.splitter.private.BlockDistributionR\x06target\x12C\n" +
	"\acurrent\x18\x02 \x01(\v2).atoms.splitter.private.BlockDistributionR\acurrent\x12(\n" +
	"\x10blocks_per_cycle\x18\x03 \x01(\x05R\x0eblocksPerCycle\"C\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tSUSPENDED\x10\x02\x12\x12\n" +
	"\x0eDECOMMISSIONED\x10\x03\"/\n" +
	"\x15ListPlacementsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"\xb4\x01\n" +
	"\x15InternalPlacementInfo\x12G\n" +
	"\tplacement\x18\x01 \x01(\v2).atoms.splitter.private.InternalPlacementR\tplacement\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"[\n" +
	"\x16ListPlacementsResponse\x12A\n" +
	"\x04info\x18\x01 \x03(\v2-.atoms.splitter.private.InternalPlacementInfoR\x04info\"\x9b\x01\n" +
	"\x13NewPlacementRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\x12H\n" +
	"\x06config\x18\x02 \x01(\v20.atoms.splitter.private.InternalPlacement.ConfigR\x06config\"Y\n" +
	"\x14NewPlacementResponse\x12A\n" +
	"\x04info\x18\x01 \x01(\v2-.atoms.splitter.private.InternalPlacementInfoR\x04info\"R\n" +
	"\x14InfoPlacementRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\"Z\n" +
	"\x15InfoPlacementResponse\x12A\n" +
	"\x04info\x18\x01 \x01(\v2-.atoms.splitter.private.InternalPlacementInfoR\x04info\"\xff\x01\n" +
	"\x16UpdatePlacementRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12E\n" +
	"\x05state\x18\x03 \x01(\x0e2/.atoms.splitter.private.InternalPlacement.StateR\x05state\x12H\n" +
	"\x06config\x18\x04 \x01(\v20.atoms.splitter.private.InternalPlacement.ConfigR\x06config\"\\\n" +
	"\x17UpdatePlacementResponse\x12A\n" +
	"\x04info\x18\x01 \x01(\v2-.atoms.splitter.private.InternalPlacementInfoR\x04info\"T\n" +
	"\x16DeletePlacementRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\"\x19\n" +
	"\x17DeletePlacementResponse2\xa0\x04\n" +
	"\x1aPlacementManagementService\x12e\n" +
	"\x04List\x12-.atoms.splitter.private.ListPlacementsRequest\x1a..atoms.splitter.private.ListPlacementsResponse\x12`\n" +
	"\x03New\x12+.atoms.splitter.private.NewPlacementRequest\x1a,.atoms.splitter.private.NewPlacementResponse\x12c\n" +
	"\x04Info\x12,.atoms.splitter.private.InfoPlacementRequest\x1a-.atoms.splitter.private.InfoPlacementResponse\x12i\n" +
	"\x06Update\x12..atoms.splitter.private.UpdatePlacementRequest\x1a/.atoms.splitter.private.UpdatePlacementResponse\x12i\n" +
	"\x06Delete\x12..atoms.splitter.private.DeletePlacementRequest\x1a/.atoms.splitter.private.DeletePlacementResponseB!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_placement_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_placement_proto_rawDescData []byte
)

func file_atoms_splitter_private_placement_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_placement_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_placement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_placement_proto_rawDesc), len(file_atoms_splitter_private_placement_proto_rawDesc)))
	})
	return file_atoms_splitter_private_placement_proto_rawDescData
}

var file_atoms_splitter_private_placement_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_atoms_splitter_private_placement_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_atoms_splitter_private_placement_proto_goTypes = []any{
	(InternalPlacement_State)(0),      // 0: atoms.splitter.private.InternalPlacement.State
	(*BlockDistribution)(nil),         // 1: atoms.splitter.private.BlockDistribution
	(*InternalPlacement)(nil),         // 2: atoms.splitter.private.InternalPlacement
	(*ListPlacementsRequest)(nil),     // 3: atoms.splitter.private.ListPlacementsRequest
	(*InternalPlacementInfo)(nil),     // 4: atoms.splitter.private.InternalPlacementInfo
	(*ListPlacementsResponse)(nil),    // 5: atoms.splitter.private.ListPlacementsResponse
	(*NewPlacementRequest)(nil),       // 6: atoms.splitter.private.NewPlacementRequest
	(*NewPlacementResponse)(nil),      // 7: atoms.splitter.private.NewPlacementResponse
	(*InfoPlacementRequest)(nil),      // 8: atoms.splitter.private.InfoPlacementRequest
	(*InfoPlacementResponse)(nil),     // 9: atoms.splitter.private.InfoPlacementResponse
	(*UpdatePlacementRequest)(nil),    // 10: atoms.splitter.private.UpdatePlacementRequest
	(*UpdatePlacementResponse)(nil),   // 11: atoms.splitter.private.UpdatePlacementResponse
	(*DeletePlacementRequest)(nil),    // 12: atoms.splitter.private.DeletePlacementRequest
	(*DeletePlacementResponse)(nil),   // 13: atoms.splitter.private.DeletePlacementResponse
	(*BlockDistribution_Split)(nil),   // 14: atoms.splitter.private.BlockDistribution.Split
	(*InternalPlacement_Config)(nil),  // 15: atoms.splitter.private.InternalPlacement.Config
	(*pb.QualifiedPlacementName)(nil), // 16: atoms.splitter.QualifiedPlacementName
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_atoms_splitter_private_placement_proto_depIdxs = []int32{
	14, // 0: atoms.splitter.private.BlockDistribution.splits:type_name -> atoms.splitter.private.BlockDistribution.Split
	16, // 1: atoms.splitter.private.InternalPlacement.name:type_name -> atoms.splitter.QualifiedPlacementName
	0,  // 2: atoms.splitter.private.InternalPlacement.state:type_name -> atoms.splitter.private.InternalPlacement.State
	15, // 3: atoms.splitter.private.InternalPlacement.config:type_name -> atoms.splitter.private.InternalPlacement.Config
	17, // 4: atoms.splitter.private.InternalPlacement.created:type_name -> google.protobuf.Timestamp
	2,  // 5: atoms.splitter.private.InternalPlacementInfo.placement:type_name -> atoms.splitter.private.InternalPlacement
	17, // 6: atoms.splitter.private.InternalPlacementInfo.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 7: atoms.splitter.private.ListPlacementsResponse.info:type_name -> atoms.splitter.private.InternalPlacementInfo
	16, // 8: atoms.splitter.private.NewPlacementRequest.name:type_name -> atoms.splitter.QualifiedPlacementName
	15, // 9: atoms.splitter.private.NewPlacementRequest.config:type_name -> atoms.splitter.private.InternalPlacement.Config
	4,  // 10: atoms.splitter.private.NewPlacementResponse.info:type_name -> atoms.splitter.private.InternalPlacementInfo
	16, // 11: atoms.splitter.private.InfoPlacementRequest.name:type_name -> atoms.splitter.QualifiedPlacementName
	4,  // 12: atoms.splitter.private.InfoPlacementResponse.info:type_name -> atoms.splitter.private.InternalPlacementInfo
	16, // 13: atoms.splitter.private.UpdatePlacementRequest.name:type_name -> atoms.splitter.QualifiedPlacementName
	0,  // 14: atoms.splitter.private.UpdatePlacementRequest.state:type_name -> atoms.splitter.private.InternalPlacement.State
	15, // 15: atoms.splitter.private.UpdatePlacementRequest.config:type_name -> atoms.splitter.private.InternalPlacement.Config
	4,  // 16: atoms.splitter.private.UpdatePlacementResponse.info:type_name -> atoms.splitter.private.InternalPlacementInfo
	16, // 17: atoms.splitter.private.DeletePlacementRequest.name:type_name -> atoms.splitter.QualifiedPlacementName
	1,  // 18: atoms.splitter.private.InternalPlacement.Config.target:type_name -> atoms.splitter.private.BlockDistribution
	1,  // 19: atoms.splitter.private.InternalPlacement.Config.current:type_name -> atoms.splitter.private.BlockDistribution
	3,  // 20: atoms.splitter.private.PlacementManagementService.List:input_type -> atoms.splitter.private.ListPlacementsRequest
	6,  // 21: atoms.splitter.private.PlacementManagementService.New:input_type -> atoms.splitter.private.NewPlacementRequest
	8,  // 22: atoms.splitter.private.PlacementManagementService.Info:input_type -> atoms.splitter.private.InfoPlacementRequest
	10, // 23: atoms.splitter.private.PlacementManagementService.Update:input_type -> atoms.splitter.private.UpdatePlacementRequest
	12, // 24: atoms.splitter.private.PlacementManagementService.Delete:input_type -> atoms.splitter.private.DeletePlacementRequest
	5,  // 25: atoms.splitter.private.PlacementManagementService.List:output_type -> atoms.splitter.private.ListPlacementsResponse
	7,  // 26: atoms.splitter.private.PlacementManagementService.New:output_type -> atoms.splitter.private.NewPlacementResponse
	9,  // 27: atoms.splitter.private.PlacementManagementService.Info:output_type -> atoms.splitter.private.InfoPlacementResponse
	11, // 28: atoms.splitter.private.PlacementManagementService.Update:output_type -> atoms.splitter.private.UpdatePlacementResponse
	13, // 29: atoms.splitter.private.PlacementManagementService.Delete:output_type -> atoms.splitter.private.DeletePlacementResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_placement_proto_init() }
func file_atoms_splitter_private_placement_proto_init() {
	if File_atoms_splitter_private_placement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_placement_proto_rawDesc), len(file_atoms_splitter_private_placement_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_private_placement_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_placement_proto_depIdxs,
		EnumInfos:         file_atoms_splitter_private_placement_proto_enumTypes,
		MessageInfos:      file_atoms_splitter_private_placement_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_placement_proto = out.File
	file_atoms_splitter_private_placement_proto_goTypes = nil
	file_atoms_splitter_private_placement_proto_depIdxs = nil
}
