// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/private/state.proto

package private

import (
	pb "go.atoms.co/splitter/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tenant        *pb.TenantInfo           `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Services      []*pb.ServiceInfoEx      `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Placements    []*InternalPlacementInfo `protobuf:"bytes,3,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetTenant() *pb.TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *State) GetServices() []*pb.ServiceInfoEx {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *State) GetPlacements() []*InternalPlacementInfo {
	if x != nil {
		return x.Placements
	}
	return nil
}

type ServiceUpdate struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Service       *pb.ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Updated       []*pb.Domain              `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Removed       []*pb.QualifiedDomainName `protobuf:"bytes,3,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceUpdate) GetService() *pb.ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceUpdate) GetUpdated() []*pb.Domain {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *ServiceUpdate) GetRemoved() []*pb.QualifiedDomainName {
	if x != nil {
		return x.Removed
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tenant        *Update_Tenant         `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Service       *Update_Service        `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Placement     *Update_Placement      `protobuf:"bytes,4,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{2}
}

func (x *Update) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Update) GetTenant() *Update_Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *Update) GetService() *Update_Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Update) GetPlacement() *Update_Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

type Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{3}
}

func (x *Delete) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type Restore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restore) Reset() {
	*x = Restore{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restore) ProtoMessage() {}

func (x *Restore) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restore.ProtoReflect.Descriptor instead.
func (*Restore) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{4}
}

func (x *Restore) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Mutation_Update
	//	*Mutation_Delete
	//	*Mutation_Restore
	Msg           isMutation_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{5}
}

func (x *Mutation) GetMsg() isMutation_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Mutation) GetUpdate() *Update {
	if x != nil {
		if x, ok := x.Msg.(*Mutation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Mutation) GetDelete() *Delete {
	if x != nil {
		if x, ok := x.Msg.(*Mutation_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Mutation) GetRestore() *Restore {
	if x != nil {
		if x, ok := x.Msg.(*Mutation_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

type isMutation_Msg interface {
	isMutation_Msg()
}

type Mutation_Update struct {
	Update *Update `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type Mutation_Delete struct {
	Delete *Delete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type Mutation_Restore struct {
	Restore *Restore `protobuf:"bytes,3,opt,name=restore,proto3,oneof"`
}

func (*Mutation_Update) isMutation_Msg() {}

func (*Mutation_Delete) isMutation_Msg() {}

func (*Mutation_Restore) isMutation_Msg() {}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*State               `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{6}
}

func (x *Snapshot) GetTenants() []*State {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type Update_Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       *pb.TenantInfo         `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update_Tenant) Reset() {
	*x = Update_Tenant{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update_Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update_Tenant) ProtoMessage() {}

func (x *Update_Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update_Tenant.ProtoReflect.Descriptor instead.
func (*Update_Tenant) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Update_Tenant) GetUpdated() *pb.TenantInfo {
	if x != nil {
		return x.Updated
	}
	return nil
}

type Update_Service struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Updated       []*ServiceUpdate           `protobuf:"bytes,1,rep,name=updated,proto3" json:"updated,omitempty"`
	Removed       []*pb.QualifiedServiceName `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update_Service) Reset() {
	*x = Update_Service{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update_Service) ProtoMessage() {}

func (x *Update_Service) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update_Service.ProtoReflect.Descriptor instead.
func (*Update_Service) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Update_Service) GetUpdated() []*ServiceUpdate {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *Update_Service) GetRemoved() []*pb.QualifiedServiceName {
	if x != nil {
		return x.Removed
	}
	return nil
}

type Update_Placement struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Updated       []*InternalPlacementInfo     `protobuf:"bytes,1,rep,name=updated,proto3" json:"updated,omitempty"`
	Removed       []*pb.QualifiedPlacementName `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update_Placement) Reset() {
	*x = Update_Placement{}
	mi := &file_atoms_splitter_private_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update_Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update_Placement) ProtoMessage() {}

func (x *Update_Placement) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_private_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update_Placement.ProtoReflect.Descriptor instead.
func (*Update_Placement) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_private_state_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Update_Placement) GetUpdated() []*InternalPlacementInfo {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *Update_Placement) GetRemoved() []*pb.QualifiedPlacementName {
	if x != nil {
		return x.Removed
	}
	return nil
}

var File_atoms_splitter_private_state_proto protoreflect.FileDescriptor

const file_atoms_splitter_private_state_proto_rawDesc = "" +
	"\n" +
	"\"atoms/splitter/private/state.proto\x12\x16atoms.splitter.private\x1a\x1aatoms/splitter/model.proto\x1a\x1fatoms/splitter/management.proto\x1a\x1eatoms/splitter/placement.proto\x1a&atoms/splitter/private/placement.proto\"\xc5\x01\n" +
	"\x05State\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.atoms.splitter.TenantInfoR\x06tenant\x129\n" +
	"\bservices\x18\x02 \x03(\v2\x1d.atoms.splitter.ServiceInfoExR\bservices\x12M\n" +
	"\n" +
	"placements\x18\x03 \x03(\v2-.atoms.splitter.private.InternalPlacementInfoR\n" +
	"placements\"\xb7\x01\n" +
	"\rServiceUpdate\x125\n" +
	"\aservice\x18\x01 \x01(\v2\x1b.atoms.splitter.ServiceInfoR\aservice\x120\n" +
	"\aupdated\x18\x02 \x03(\v2\x16.atoms.splitter.DomainR\aupdated\x12=\n" +
	"\aremoved\x18\x03 \x03(\v2#.atoms.splitter.QualifiedDomainNameR\aremoved\"\xcb\x04\n" +
	"\x06Update\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x06tenant\x18\x02 \x01(\v2%.atoms.splitter.private.Update.TenantR\x06tenant\x12@\n" +
	"\aservice\x18\x03 \x01(\v2&.atoms.splitter.private.Update.ServiceR\aservice\x12F\n" +
	"\tplacement\x18\x04 \x01(\v2(.atoms.splitter.private.Update.PlacementR\tplacement\x1a>\n" +
	"\x06Tenant\x124\n" +
	"\aupdated\x18\x01 \x01(\v2\x1a.atoms.splitter.TenantInfoR\aupdated\x1a\x8a\x01\n" +
	"\aService\x12?\n" +
	"\aupdated\x18\x01 \x03(\v2%.atoms.splitter.private.ServiceUpdateR\aupdated\x12>\n" +
	"\aremoved\x18\x02 \x03(\v2$.atoms.splitter.QualifiedServiceNameR\aremoved\x1a\x96\x01\n" +
	"\tPlacement\x12G\n" +
	"\aupdated\x18\x01 \x03(\v2-.atoms.splitter.private.InternalPlacementInfoR\aupdated\x12@\n" +
	"\aremoved\x18\x02 \x03(\v2&.atoms.splitter.QualifiedPlacementNameR\aremoved\" \n" +
	"\x06Delete\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"G\n" +
	"\aRestore\x12<\n" +
	"\bsnapshot\x18\x01 \x01(\v2 .atoms.splitter.private.SnapshotR\bsnapshot\"\xc2\x01\n" +
	"\bMutation\x128\n" +
	"\x06update\x18\x01 \x01(\v2\x1e.atoms.splitter.private.UpdateH\x00R\x06update\x128\n" +
	"\x06delete\x18\x02 \x01(\v2\x1e.atoms.splitter.private.DeleteH\x00R\x06delete\x12;\n" +
	"\arestore\x18\x03 \x01(\v2\x1f.atoms.splitter.private.RestoreH\x00R\arestoreB\x05\n" +
	"\x03msg\"C\n" +
	"\bSnapshot\x127\n" +
	"\atenants\x18\x01 \x03(\v2\x1d.atoms.splitter.private.StateR\atenantsB!Z\x1fgo.atoms.co/splitter/pb/privateb\x06proto3"

var (
	file_atoms_splitter_private_state_proto_rawDescOnce sync.Once
	file_atoms_splitter_private_state_proto_rawDescData []byte
)

func file_atoms_splitter_private_state_proto_rawDescGZIP() []byte {
	file_atoms_splitter_private_state_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_private_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_state_proto_rawDesc), len(file_atoms_splitter_private_state_proto_rawDesc)))
	})
	return file_atoms_splitter_private_state_proto_rawDescData
}

var file_atoms_splitter_private_state_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_atoms_splitter_private_state_proto_goTypes = []any{
	(*State)(nil),                     // 0: atoms.splitter.private.State
	(*ServiceUpdate)(nil),             // 1: atoms.splitter.private.ServiceUpdate
	(*Update)(nil),                    // 2: atoms.splitter.private.Update
	(*Delete)(nil),                    // 3: atoms.splitter.private.Delete
	(*Restore)(nil),                   // 4: atoms.splitter.private.Restore
	(*Mutation)(nil),                  // 5: atoms.splitter.private.Mutation
	(*Snapshot)(nil),                  // 6: atoms.splitter.private.Snapshot
	(*Update_Tenant)(nil),             // 7: atoms.splitter.private.Update.Tenant
	(*Update_Service)(nil),            // 8: atoms.splitter.private.Update.Service
	(*Update_Placement)(nil),          // 9: atoms.splitter.private.Update.Placement
	(*pb.TenantInfo)(nil),             // 10: atoms.splitter.TenantInfo
	(*pb.ServiceInfoEx)(nil),          // 11: atoms.splitter.ServiceInfoEx
	(*InternalPlacementInfo)(nil),     // 12: atoms.splitter.private.InternalPlacementInfo
	(*pb.ServiceInfo)(nil),            // 13: atoms.splitter.ServiceInfo
	(*pb.Domain)(nil),                 // 14: atoms.splitter.Domain
	(*pb.QualifiedDomainName)(nil),    // 15: atoms.splitter.QualifiedDomainName
	(*pb.QualifiedServiceName)(nil),   // 16: atoms.splitter.QualifiedServiceName
	(*pb.QualifiedPlacementName)(nil), // 17: atoms.splitter.QualifiedPlacementName
}
var file_atoms_splitter_private_state_proto_depIdxs = []int32{
	10, // 0: atoms.splitter.private.State.tenant:type_name -> atoms.splitter.TenantInfo
	11, // 1: atoms.splitter.private.State.services:type_name -> atoms.splitter.ServiceInfoEx
	12, // 2: atoms.splitter.private.State.placements:type_name -> atoms.splitter.private.InternalPlacementInfo
	13, // 3: atoms.splitter.private.ServiceUpdate.service:type_name -> atoms.splitter.ServiceInfo
	14, // 4: atoms.splitter.private.ServiceUpdate.updated:type_name -> atoms.splitter.Domain
	15, // 5: atoms.splitter.private.ServiceUpdate.removed:type_name -> atoms.splitter.QualifiedDomainName
	7,  // 6: atoms.splitter.private.Update.tenant:type_name -> atoms.splitter.private.Update.Tenant
	8,  // 7: atoms.splitter.private.Update.service:type_name -> atoms.splitter.private.Update.Service
	9,  // 8: atoms.splitter.private.Update.placement:type_name -> atoms.splitter.private.Update.Placement
	6,  // 9: atoms.splitter.private.Restore.snapshot:type_name -> atoms.splitter.private.Snapshot
	2,  // 10: atoms.splitter.private.Mutation.update:type_name -> atoms.splitter.private.Update
	3,  // 11: atoms.splitter.private.Mutation.delete:type_name -> atoms.splitter.private.Delete
	4,  // 12: atoms.splitter.private.Mutation.restore:type_name -> atoms.splitter.private.Restore
	0,  // 13: atoms.splitter.private.Snapshot.tenants:type_name -> atoms.splitter.private.State
	10, // 14: atoms.splitter.private.Update.Tenant.updated:type_name -> atoms.splitter.TenantInfo
	1,  // 15: atoms.splitter.private.Update.Service.updated:type_name -> atoms.splitter.private.ServiceUpdate
	16, // 16: atoms.splitter.private.Update.Service.removed:type_name -> atoms.splitter.QualifiedServiceName
	12, // 17: atoms.splitter.private.Update.Placement.updated:type_name -> atoms.splitter.private.InternalPlacementInfo
	17, // 18: atoms.splitter.private.Update.Placement.removed:type_name -> atoms.splitter.QualifiedPlacementName
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_atoms_splitter_private_state_proto_init() }
func file_atoms_splitter_private_state_proto_init() {
	if File_atoms_splitter_private_state_proto != nil {
		return
	}
	file_atoms_splitter_private_placement_proto_init()
	file_atoms_splitter_private_state_proto_msgTypes[5].OneofWrappers = []any{
		(*Mutation_Update)(nil),
		(*Mutation_Delete)(nil),
		(*Mutation_Restore)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_private_state_proto_rawDesc), len(file_atoms_splitter_private_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_private_state_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_private_state_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_private_state_proto_msgTypes,
	}.Build()
	File_atoms_splitter_private_state_proto = out.File
	file_atoms_splitter_private_state_proto_goTypes = nil
	file_atoms_splitter_private_state_proto_depIdxs = nil
}
