load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cmd",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    importpath = "go.atoms.co/splitter/cmd/splitterctl/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/core",
        "//pkg/model",
        "@co_atoms_go_lib//backoffx",
        "@co_atoms_go_lib//net/grpcx",
        "@co_atoms_go_lib//signalx",
        "@co_atoms_go_lib//statshandlerx",
        "@co_atoms_go_lib//stringx",
        "@co_atoms_go_lib_net_location//go/location",
        "@co_atoms_go_slicex//:slicex",
        "@com_github_jille_grpc_multi_resolver//:grpc-multi-resolver",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "cmd_test",
    srcs = glob(["domains_test.go"]),
    embed = [":cmd"],
    deps = [
        "//pkg/model",
        "@com_github_stretchr_testify//require",
    ],
)
