// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/cluster.proto

package pb

import (
	pb "go.atoms.co/splitter/lib/service/location/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClusterMessage_Snapshot_
	//	*ClusterMessage_Change_
	Msg           isClusterMessage_Msg   `protobuf_oneof:"msg"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage) Reset() {
	*x = ClusterMessage{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage) ProtoMessage() {}

func (x *ClusterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage.ProtoReflect.Descriptor instead.
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMessage) GetMsg() isClusterMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClusterMessage) GetSnapshot() *ClusterMessage_Snapshot {
	if x != nil {
		if x, ok := x.Msg.(*ClusterMessage_Snapshot_); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ClusterMessage) GetChange() *ClusterMessage_Change {
	if x != nil {
		if x, ok := x.Msg.(*ClusterMessage_Change_); ok {
			return x.Change
		}
	}
	return nil
}

func (x *ClusterMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterMessage) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isClusterMessage_Msg interface {
	isClusterMessage_Msg()
}

type ClusterMessage_Snapshot_ struct {
	Snapshot *ClusterMessage_Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type ClusterMessage_Change_ struct {
	Change *ClusterMessage_Change `protobuf:"bytes,2,opt,name=change,proto3,oneof"`
}

func (*ClusterMessage_Snapshot_) isClusterMessage_Msg() {}

func (*ClusterMessage_Change_) isClusterMessage_Msg() {}

type ClusterMessage_GrantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	State         GrantState             `protobuf:"varint,3,opt,name=state,proto3,enum=atoms.splitter.GrantState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_GrantInfo) Reset() {
	*x = ClusterMessage_GrantInfo{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_GrantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_GrantInfo) ProtoMessage() {}

func (x *ClusterMessage_GrantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_GrantInfo.ProtoReflect.Descriptor instead.
func (*ClusterMessage_GrantInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClusterMessage_GrantInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterMessage_GrantInfo) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *ClusterMessage_GrantInfo) GetState() GrantState {
	if x != nil {
		return x.State
	}
	return GrantState_UNKNOWN
}

type ClusterMessage_Assignment struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Consumer      *Instance                   `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Grants        []*ClusterMessage_GrantInfo `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Assignment) Reset() {
	*x = ClusterMessage_Assignment{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Assignment) ProtoMessage() {}

func (x *ClusterMessage_Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Assignment.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Assignment) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ClusterMessage_Assignment) GetConsumer() *Instance {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *ClusterMessage_Assignment) GetGrants() []*ClusterMessage_GrantInfo {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ClusterMessage_Snapshot struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Assignments   []*ClusterMessage_Assignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Origin        *pb.Instance                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Shards        []*Shard                     `protobuf:"bytes,3,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Snapshot) Reset() {
	*x = ClusterMessage_Snapshot{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Snapshot) ProtoMessage() {}

func (x *ClusterMessage_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Snapshot.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Snapshot) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ClusterMessage_Snapshot) GetAssignments() []*ClusterMessage_Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *ClusterMessage_Snapshot) GetOrigin() *pb.Instance {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ClusterMessage_Snapshot) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ClusterMessage_Assign struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Assignments   []*ClusterMessage_Assignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Assign) Reset() {
	*x = ClusterMessage_Assign{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Assign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Assign) ProtoMessage() {}

func (x *ClusterMessage_Assign) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Assign.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Assign) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ClusterMessage_Assign) GetAssignments() []*ClusterMessage_Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type ClusterMessage_Update struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Grants        []*ClusterMessage_GrantInfo `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Update) Reset() {
	*x = ClusterMessage_Update{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Update) ProtoMessage() {}

func (x *ClusterMessage_Update) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Update.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Update) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ClusterMessage_Update) GetGrants() []*ClusterMessage_GrantInfo {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ClusterMessage_Unassign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []string               `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Unassign) Reset() {
	*x = ClusterMessage_Unassign{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Unassign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Unassign) ProtoMessage() {}

func (x *ClusterMessage_Unassign) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Unassign.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Unassign) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ClusterMessage_Unassign) GetGrants() []string {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ClusterMessage_Remove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumers     []string               `protobuf:"bytes,1,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Remove) Reset() {
	*x = ClusterMessage_Remove{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Remove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Remove) ProtoMessage() {}

func (x *ClusterMessage_Remove) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Remove.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Remove) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ClusterMessage_Remove) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type ClusterMessage_Shards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shards        []*Shard               `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Shards) Reset() {
	*x = ClusterMessage_Shards{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Shards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Shards) ProtoMessage() {}

func (x *ClusterMessage_Shards) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Shards.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Shards) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 7}
}

func (x *ClusterMessage_Shards) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ClusterMessage_Change struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Assign        *ClusterMessage_Assign   `protobuf:"bytes,1,opt,name=assign,proto3" json:"assign,omitempty"`
	Update        *ClusterMessage_Update   `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	Unassign      *ClusterMessage_Unassign `protobuf:"bytes,3,opt,name=unassign,proto3" json:"unassign,omitempty"`
	Remove        *ClusterMessage_Remove   `protobuf:"bytes,4,opt,name=remove,proto3" json:"remove,omitempty"`
	Shards        *ClusterMessage_Shards   `protobuf:"bytes,5,opt,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage_Change) Reset() {
	*x = ClusterMessage_Change{}
	mi := &file_atoms_splitter_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage_Change) ProtoMessage() {}

func (x *ClusterMessage_Change) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage_Change.ProtoReflect.Descriptor instead.
func (*ClusterMessage_Change) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_cluster_proto_rawDescGZIP(), []int{0, 8}
}

func (x *ClusterMessage_Change) GetAssign() *ClusterMessage_Assign {
	if x != nil {
		return x.Assign
	}
	return nil
}

func (x *ClusterMessage_Change) GetUpdate() *ClusterMessage_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ClusterMessage_Change) GetUnassign() *ClusterMessage_Unassign {
	if x != nil {
		return x.Unassign
	}
	return nil
}

func (x *ClusterMessage_Change) GetRemove() *ClusterMessage_Remove {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *ClusterMessage_Change) GetShards() *ClusterMessage_Shards {
	if x != nil {
		return x.Shards
	}
	return nil
}

var File_atoms_splitter_cluster_proto protoreflect.FileDescriptor

const file_atoms_splitter_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1catoms/splitter/cluster.proto\x12\x0eatoms.splitter\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2atoms/splitter/lib/service/location/location.proto\x1a\x1aatoms/splitter/model.proto\"\xca\n" +
	"\n" +
	"\x0eClusterMessage\x12E\n" +
	"\bsnapshot\x18\x01 \x01(\v2'.atoms.splitter.ClusterMessage.SnapshotH\x00R\bsnapshot\x12?\n" +
	"\x06change\x18\x02 \x01(\v2%.atoms.splitter.ClusterMessage.ChangeH\x00R\x06change\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1az\n" +
	"\tGrantInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x05shard\x18\x02 \x01(\v2\x15.atoms.splitter.ShardR\x05shard\x120\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1a.atoms.splitter.GrantStateR\x05state\x1a\x84\x01\n" +
	"\n" +
	"Assignment\x124\n" +
	"\bconsumer\x18\x01 \x01(\v2\x18.atoms.splitter.InstanceR\bconsumer\x12@\n" +
	"\x06grants\x18\x02 \x03(\v2(.atoms.splitter.ClusterMessage.GrantInfoR\x06grants\x1a\xcd\x01\n" +
	"\bSnapshot\x12K\n" +
	"\vassignments\x18\x01 \x03(\v2).atoms.splitter.ClusterMessage.AssignmentR\vassignments\x12E\n" +
	"\x06origin\x18\x02 \x01(\v2-.atoms.splitter.lib.service.location.InstanceR\x06origin\x12-\n" +
	"\x06shards\x18\x03 \x03(\v2\x15.atoms.splitter.ShardR\x06shards\x1aU\n" +
	"\x06Assign\x12K\n" +
	"\vassignments\x18\x01 \x03(\v2).atoms.splitter.ClusterMessage.AssignmentR\vassignments\x1aJ\n" +
	"\x06Update\x12@\n" +
	"\x06grants\x18\x01 \x03(\v2(.atoms.splitter.ClusterMessage.GrantInfoR\x06grants\x1a\"\n" +
	"\bUnassign\x12\x16\n" +
	"\x06grants\x18\x01 \x03(\tR\x06grants\x1a&\n" +
	"\x06Remove\x12\x1c\n" +
	"\tconsumers\x18\x01 \x03(\tR\tconsumers\x1a7\n" +
	"\x06Shards\x12-\n" +
	"\x06shards\x18\x01 \x03(\v2\x15.atoms.splitter.ShardR\x06shards\x1a\xc9\x02\n" +
	"\x06Change\x12=\n" +
	"\x06assign\x18\x01 \x01(\v2%.atoms.splitter.ClusterMessage.AssignR\x06assign\x12=\n" +
	"\x06update\x18\x02 \x01(\v2%.atoms.splitter.ClusterMessage.UpdateR\x06update\x12C\n" +
	"\bunassign\x18\x03 \x01(\v2'.atoms.splitter.ClusterMessage.UnassignR\bunassign\x12=\n" +
	"\x06remove\x18\x04 \x01(\v2%.atoms.splitter.ClusterMessage.RemoveR\x06remove\x12=\n" +
	"\x06shards\x18\x05 \x01(\v2%.atoms.splitter.ClusterMessage.ShardsR\x06shardsB\x05\n" +
	"\x03msgB1\n" +
	"\x14co.atoms.splitter.pbP\x01Z\x17go.atoms.co/splitter/pbb\x06proto3"

var (
	file_atoms_splitter_cluster_proto_rawDescOnce sync.Once
	file_atoms_splitter_cluster_proto_rawDescData []byte
)

func file_atoms_splitter_cluster_proto_rawDescGZIP() []byte {
	file_atoms_splitter_cluster_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_cluster_proto_rawDesc), len(file_atoms_splitter_cluster_proto_rawDesc)))
	})
	return file_atoms_splitter_cluster_proto_rawDescData
}

var file_atoms_splitter_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_atoms_splitter_cluster_proto_goTypes = []any{
	(*ClusterMessage)(nil),            // 0: atoms.splitter.ClusterMessage
	(*ClusterMessage_GrantInfo)(nil),  // 1: atoms.splitter.ClusterMessage.GrantInfo
	(*ClusterMessage_Assignment)(nil), // 2: atoms.splitter.ClusterMessage.Assignment
	(*ClusterMessage_Snapshot)(nil),   // 3: atoms.splitter.ClusterMessage.Snapshot
	(*ClusterMessage_Assign)(nil),     // 4: atoms.splitter.ClusterMessage.Assign
	(*ClusterMessage_Update)(nil),     // 5: atoms.splitter.ClusterMessage.Update
	(*ClusterMessage_Unassign)(nil),   // 6: atoms.splitter.ClusterMessage.Unassign
	(*ClusterMessage_Remove)(nil),     // 7: atoms.splitter.ClusterMessage.Remove
	(*ClusterMessage_Shards)(nil),     // 8: atoms.splitter.ClusterMessage.Shards
	(*ClusterMessage_Change)(nil),     // 9: atoms.splitter.ClusterMessage.Change
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*Shard)(nil),                     // 11: atoms.splitter.Shard
	(GrantState)(0),                   // 12: atoms.splitter.GrantState
	(*Instance)(nil),                  // 13: atoms.splitter.Instance
	(*pb.Instance)(nil),               // 14: atoms.splitter.lib.service.location.Instance
}
var file_atoms_splitter_cluster_proto_depIdxs = []int32{
	3,  // 0: atoms.splitter.ClusterMessage.snapshot:type_name -> atoms.splitter.ClusterMessage.Snapshot
	9,  // 1: atoms.splitter.ClusterMessage.change:type_name -> atoms.splitter.ClusterMessage.Change
	10, // 2: atoms.splitter.ClusterMessage.timestamp:type_name -> google.protobuf.Timestamp
	11, // 3: atoms.splitter.ClusterMessage.GrantInfo.shard:type_name -> atoms.splitter.Shard
	12, // 4: atoms.splitter.ClusterMessage.GrantInfo.state:type_name -> atoms.splitter.GrantState
	13, // 5: atoms.splitter.ClusterMessage.Assignment.consumer:type_name -> atoms.splitter.Instance
	1,  // 6: atoms.splitter.ClusterMessage.Assignment.grants:type_name -> atoms.splitter.ClusterMessage.GrantInfo
	2,  // 7: atoms.splitter.ClusterMessage.Snapshot.assignments:type_name -> atoms.splitter.ClusterMessage.Assignment
	14, // 8: atoms.splitter.ClusterMessage.Snapshot.origin:type_name -> atoms.splitter.lib.service.location.Instance
	11, // 9: atoms.splitter.ClusterMessage.Snapshot.shards:type_name -> atoms.splitter.Shard
	2,  // 10: atoms.splitter.ClusterMessage.Assign.assignments:type_name -> atoms.splitter.ClusterMessage.Assignment
	1,  // 11: atoms.splitter.ClusterMessage.Update.grants:type_name -> atoms.splitter.ClusterMessage.GrantInfo
	11, // 12: atoms.splitter.ClusterMessage.Shards.shards:type_name -> atoms.splitter.Shard
	4,  // 13: atoms.splitter.ClusterMessage.Change.assign:type_name -> atoms.splitter.ClusterMessage.Assign
	5,  // 14: atoms.splitter.ClusterMessage.Change.update:type_name -> atoms.splitter.ClusterMessage.Update
	6,  // 15: atoms.splitter.ClusterMessage.Change.unassign:type_name -> atoms.splitter.ClusterMessage.Unassign
	7,  // 16: atoms.splitter.ClusterMessage.Change.remove:type_name -> atoms.splitter.ClusterMessage.Remove
	8,  // 17: atoms.splitter.ClusterMessage.Change.shards:type_name -> atoms.splitter.ClusterMessage.Shards
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_atoms_splitter_cluster_proto_init() }
func file_atoms_splitter_cluster_proto_init() {
	if File_atoms_splitter_cluster_proto != nil {
		return
	}
	file_atoms_splitter_model_proto_init()
	file_atoms_splitter_cluster_proto_msgTypes[0].OneofWrappers = []any{
		(*ClusterMessage_Snapshot_)(nil),
		(*ClusterMessage_Change_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_cluster_proto_rawDesc), len(file_atoms_splitter_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_cluster_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_cluster_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_cluster_proto_msgTypes,
	}.Build()
	File_atoms_splitter_cluster_proto = out.File
	file_atoms_splitter_cluster_proto_goTypes = nil
	file_atoms_splitter_cluster_proto_depIdxs = nil
}
