// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: atoms/splitter/consumerapi.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsumerService_Join_FullMethodName = "/atoms.splitter.ConsumerService/Join"
)

// ConsumerServiceClient is the client API for ConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerServiceClient interface {
	Join(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[JoinMessage, JoinMessage], error)
}

type consumerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerServiceClient(cc grpc.ClientConnInterface) ConsumerServiceClient {
	return &consumerServiceClient{cc}
}

func (c *consumerServiceClient) Join(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[JoinMessage, JoinMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsumerService_ServiceDesc.Streams[0], ConsumerService_Join_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinMessage, JoinMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsumerService_JoinClient = grpc.BidiStreamingClient[JoinMessage, JoinMessage]

// ConsumerServiceServer is the server API for ConsumerService service.
// All implementations should embed UnimplementedConsumerServiceServer
// for forward compatibility.
type ConsumerServiceServer interface {
	Join(grpc.BidiStreamingServer[JoinMessage, JoinMessage]) error
}

// UnimplementedConsumerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumerServiceServer struct{}

func (UnimplementedConsumerServiceServer) Join(grpc.BidiStreamingServer[JoinMessage, JoinMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedConsumerServiceServer) testEmbeddedByValue() {}

// UnsafeConsumerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServiceServer will
// result in compilation errors.
type UnsafeConsumerServiceServer interface {
	mustEmbedUnimplementedConsumerServiceServer()
}

func RegisterConsumerServiceServer(s grpc.ServiceRegistrar, srv ConsumerServiceServer) {
	// If the following call pancis, it indicates UnimplementedConsumerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsumerService_ServiceDesc, srv)
}

func _ConsumerService_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConsumerServiceServer).Join(&grpc.GenericServerStream[JoinMessage, JoinMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsumerService_JoinServer = grpc.BidiStreamingServer[JoinMessage, JoinMessage]

// ConsumerService_ServiceDesc is the grpc.ServiceDesc for ConsumerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsumerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoms.splitter.ConsumerService",
	HandlerType: (*ConsumerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _ConsumerService_Join_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atoms/splitter/consumerapi.proto",
}
