// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/managementapi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{0}
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantInfo          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{1}
}

func (x *ListTenantsResponse) GetTenants() []*TenantInfo {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type NewTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *Tenant_Config         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTenantRequest) Reset() {
	*x = NewTenantRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTenantRequest) ProtoMessage() {}

func (x *NewTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTenantRequest.ProtoReflect.Descriptor instead.
func (*NewTenantRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{2}
}

func (x *NewTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewTenantRequest) GetConfig() *Tenant_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type NewTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTenantResponse) Reset() {
	*x = NewTenantResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTenantResponse) ProtoMessage() {}

func (x *NewTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTenantResponse.ProtoReflect.Descriptor instead.
func (*NewTenantResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{3}
}

func (x *NewTenantResponse) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type InfoTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoTenantRequest) Reset() {
	*x = InfoTenantRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoTenantRequest) ProtoMessage() {}

func (x *InfoTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoTenantRequest.ProtoReflect.Descriptor instead.
func (*InfoTenantRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{4}
}

func (x *InfoTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InfoTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoTenantResponse) Reset() {
	*x = InfoTenantResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoTenantResponse) ProtoMessage() {}

func (x *InfoTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoTenantResponse.ProtoReflect.Descriptor instead.
func (*InfoTenantResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{5}
}

func (x *InfoTenantResponse) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Config        *Tenant_Config         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Operational   *Tenant_Operational    `protobuf:"bytes,4,opt,name=operational,proto3" json:"operational,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTenantRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateTenantRequest) GetConfig() *Tenant_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateTenantRequest) GetOperational() *Tenant_Operational {
	if x != nil {
		return x.Operational
	}
	return nil
}

type UpdateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTenantResponse) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{9}
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{10}
}

func (x *ListServicesRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfoEx       `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{11}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfoEx {
	if x != nil {
		return x.Services
	}
	return nil
}

type NewServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedServiceName  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *Service_Config        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServiceRequest) Reset() {
	*x = NewServiceRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServiceRequest) ProtoMessage() {}

func (x *NewServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServiceRequest.ProtoReflect.Descriptor instead.
func (*NewServiceRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{12}
}

func (x *NewServiceRequest) GetName() *QualifiedServiceName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *NewServiceRequest) GetConfig() *Service_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type NewServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServiceResponse) Reset() {
	*x = NewServiceResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServiceResponse) ProtoMessage() {}

func (x *NewServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServiceResponse.ProtoReflect.Descriptor instead.
func (*NewServiceResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{13}
}

func (x *NewServiceResponse) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

type InfoServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedServiceName  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoServiceRequest) Reset() {
	*x = InfoServiceRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoServiceRequest) ProtoMessage() {}

func (x *InfoServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoServiceRequest.ProtoReflect.Descriptor instead.
func (*InfoServiceRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{14}
}

func (x *InfoServiceRequest) GetName() *QualifiedServiceName {
	if x != nil {
		return x.Name
	}
	return nil
}

type InfoServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfoEx         `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoServiceResponse) Reset() {
	*x = InfoServiceResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoServiceResponse) ProtoMessage() {}

func (x *InfoServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoServiceResponse.ProtoReflect.Descriptor instead.
func (*InfoServiceResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{15}
}

func (x *InfoServiceResponse) GetService() *ServiceInfoEx {
	if x != nil {
		return x.Service
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedServiceName  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Config        *Service_Config        `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Operational   *Service_Operational   `protobuf:"bytes,4,opt,name=operational,proto3" json:"operational,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateServiceRequest) GetName() *QualifiedServiceName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateServiceRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateServiceRequest) GetConfig() *Service_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateServiceRequest) GetOperational() *Service_Operational {
	if x != nil {
		return x.Operational
	}
	return nil
}

type UpdateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceResponse) Reset() {
	*x = UpdateServiceResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResponse) ProtoMessage() {}

func (x *UpdateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateServiceResponse) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedServiceName  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteServiceRequest) GetName() *QualifiedServiceName {
	if x != nil {
		return x.Name
	}
	return nil
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{19}
}

type ListDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *QualifiedServiceName  `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{20}
}

func (x *ListDomainsRequest) GetService() *QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*Domain              `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{21}
}

func (x *ListDomainsResponse) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type NewDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedDomainName   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DomainType             `protobuf:"varint,2,opt,name=type,proto3,enum=atoms.splitter.DomainType" json:"type,omitempty"`
	Config        *Domain_Config         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	State         Domain_State           `protobuf:"varint,4,opt,name=state,proto3,enum=atoms.splitter.Domain_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewDomainRequest) Reset() {
	*x = NewDomainRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDomainRequest) ProtoMessage() {}

func (x *NewDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDomainRequest.ProtoReflect.Descriptor instead.
func (*NewDomainRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{22}
}

func (x *NewDomainRequest) GetName() *QualifiedDomainName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *NewDomainRequest) GetType() DomainType {
	if x != nil {
		return x.Type
	}
	return DomainType_INVALID
}

func (x *NewDomainRequest) GetConfig() *Domain_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NewDomainRequest) GetState() Domain_State {
	if x != nil {
		return x.State
	}
	return Domain_UNKNOWN
}

type NewDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *Domain                `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewDomainResponse) Reset() {
	*x = NewDomainResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDomainResponse) ProtoMessage() {}

func (x *NewDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDomainResponse.ProtoReflect.Descriptor instead.
func (*NewDomainResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{23}
}

func (x *NewDomainResponse) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type UpdateDomainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           *QualifiedDomainName   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServiceVersion int64                  `protobuf:"varint,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Config         *Domain_Config         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	State          Domain_State           `protobuf:"varint,4,opt,name=state,proto3,enum=atoms.splitter.Domain_State" json:"state,omitempty"`
	Operational    *Domain_Operational    `protobuf:"bytes,5,opt,name=operational,proto3" json:"operational,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDomainRequest) Reset() {
	*x = UpdateDomainRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDomainRequest) ProtoMessage() {}

func (x *UpdateDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDomainRequest.ProtoReflect.Descriptor instead.
func (*UpdateDomainRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateDomainRequest) GetName() *QualifiedDomainName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateDomainRequest) GetServiceVersion() int64 {
	if x != nil {
		return x.ServiceVersion
	}
	return 0
}

func (x *UpdateDomainRequest) GetConfig() *Domain_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateDomainRequest) GetState() Domain_State {
	if x != nil {
		return x.State
	}
	return Domain_UNKNOWN
}

func (x *UpdateDomainRequest) GetOperational() *Domain_Operational {
	if x != nil {
		return x.Operational
	}
	return nil
}

type UpdateDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *Domain                `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDomainResponse) Reset() {
	*x = UpdateDomainResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDomainResponse) ProtoMessage() {}

func (x *UpdateDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDomainResponse.ProtoReflect.Descriptor instead.
func (*UpdateDomainResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateDomainResponse) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type DeleteDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedDomainName   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainRequest) Reset() {
	*x = DeleteDomainRequest{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainRequest) ProtoMessage() {}

func (x *DeleteDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteDomainRequest) GetName() *QualifiedDomainName {
	if x != nil {
		return x.Name
	}
	return nil
}

type DeleteDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainResponse) Reset() {
	*x = DeleteDomainResponse{}
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainResponse) ProtoMessage() {}

func (x *DeleteDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_managementapi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainResponse.ProtoReflect.Descriptor instead.
func (*DeleteDomainResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_managementapi_proto_rawDescGZIP(), []int{27}
}

var File_atoms_splitter_managementapi_proto protoreflect.FileDescriptor

const file_atoms_splitter_managementapi_proto_rawDesc = "" +
	"\n" +
	"\"atoms/splitter/managementapi.proto\x12\x0eatoms.splitter\x1a\x1aatoms/splitter/model.proto\x1a\x1fatoms/splitter/management.proto\"\x14\n" +
	"\x12ListTenantsRequest\"K\n" +
	"\x13ListTenantsResponse\x124\n" +
	"\atenants\x18\x01 \x03(\v2\x1a.atoms.splitter.TenantInfoR\atenants\"]\n" +
	"\x10NewTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.atoms.splitter.Tenant.ConfigR\x06config\"G\n" +
	"\x11NewTenantResponse\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.atoms.splitter.TenantInfoR\x06tenant\"'\n" +
	"\x11InfoTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x12InfoTenantResponse\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.atoms.splitter.TenantInfoR\x06tenant\"\xc0\x01\n" +
	"\x13UpdateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x125\n" +
	"\x06config\x18\x03 \x01(\v2\x1d.atoms.splitter.Tenant.ConfigR\x06config\x12D\n" +
	"\voperational\x18\x04 \x01(\v2\".atoms.splitter.Tenant.OperationalR\voperational\"J\n" +
	"\x14UpdateTenantResponse\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.atoms.splitter.TenantInfoR\x06tenant\")\n" +
	"\x13DeleteTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteTenantResponse\"-\n" +
	"\x13ListServicesRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"Q\n" +
	"\x14ListServicesResponse\x129\n" +
	"\bservices\x18\x01 \x03(\v2\x1d.atoms.splitter.ServiceInfoExR\bservices\"\x85\x01\n" +
	"\x11NewServiceRequest\x128\n" +
	"\x04name\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\x04name\x126\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.atoms.splitter.Service.ConfigR\x06config\"K\n" +
	"\x12NewServiceResponse\x125\n" +
	"\aservice\x18\x01 \x01(\v2\x1b.atoms.splitter.ServiceInfoR\aservice\"N\n" +
	"\x12InfoServiceRequest\x128\n" +
	"\x04name\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\x04name\"N\n" +
	"\x13InfoServiceResponse\x127\n" +
	"\aservice\x18\x01 \x01(\v2\x1d.atoms.splitter.ServiceInfoExR\aservice\"\xe9\x01\n" +
	"\x14UpdateServiceRequest\x128\n" +
	"\x04name\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x126\n" +
	"\x06config\x18\x03 \x01(\v2\x1e.atoms.splitter.Service.ConfigR\x06config\x12E\n" +
	"\voperational\x18\x04 \x01(\v2#.atoms.splitter.Service.OperationalR\voperational\"N\n" +
	"\x15UpdateServiceResponse\x125\n" +
	"\aservice\x18\x01 \x01(\v2\x1b.atoms.splitter.ServiceInfoR\aservice\"P\n" +
	"\x14DeleteServiceRequest\x128\n" +
	"\x04name\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\x04name\"\x17\n" +
	"\x15DeleteServiceResponse\"T\n" +
	"\x12ListDomainsRequest\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\"G\n" +
	"\x13ListDomainsResponse\x120\n" +
	"\adomains\x18\x01 \x03(\v2\x16.atoms.splitter.DomainR\adomains\"\xe6\x01\n" +
	"\x10NewDomainRequest\x127\n" +
	"\x04name\x18\x01 \x01(\v2#.atoms.splitter.QualifiedDomainNameR\x04name\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.atoms.splitter.DomainTypeR\x04type\x125\n" +
	"\x06config\x18\x03 \x01(\v2\x1d.atoms.splitter.Domain.ConfigR\x06config\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.atoms.splitter.Domain.StateR\x05state\"C\n" +
	"\x11NewDomainResponse\x12.\n" +
	"\x06domain\x18\x01 \x01(\v2\x16.atoms.splitter.DomainR\x06domain\"\xa8\x02\n" +
	"\x13UpdateDomainRequest\x127\n" +
	"\x04name\x18\x01 \x01(\v2#.atoms.splitter.QualifiedDomainNameR\x04name\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\x03R\x0eserviceVersion\x125\n" +
	"\x06config\x18\x03 \x01(\v2\x1d.atoms.splitter.Domain.ConfigR\x06config\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.atoms.splitter.Domain.StateR\x05state\x12D\n" +
	"\voperational\x18\x05 \x01(\v2\".atoms.splitter.Domain.OperationalR\voperational\"F\n" +
	"\x14UpdateDomainResponse\x12.\n" +
	"\x06domain\x18\x01 \x01(\v2\x16.atoms.splitter.DomainR\x06domain\"N\n" +
	"\x13DeleteDomainRequest\x127\n" +
	"\x04name\x18\x01 \x01(\v2#.atoms.splitter.QualifiedDomainNameR\x04name\"\x16\n" +
	"\x14DeleteDomainResponse2\xec\t\n" +
	"\x11ManagementService\x12V\n" +
	"\vListTenants\x12\".atoms.splitter.ListTenantsRequest\x1a#.atoms.splitter.ListTenantsResponse\x12P\n" +
	"\tNewTenant\x12 .atoms.splitter.NewTenantRequest\x1a!.atoms.splitter.NewTenantResponse\x12S\n" +
	"\n" +
	"InfoTenant\x12!.atoms.splitter.InfoTenantRequest\x1a\".atoms.splitter.InfoTenantResponse\x12Y\n" +
	"\fUpdateTenant\x12#.atoms.splitter.UpdateTenantRequest\x1a$.atoms.splitter.UpdateTenantResponse\x12Y\n" +
	"\fDeleteTenant\x12#.atoms.splitter.DeleteTenantRequest\x1a$.atoms.splitter.DeleteTenantResponse\x12Y\n" +
	"\fListServices\x12#.atoms.splitter.ListServicesRequest\x1a$.atoms.splitter.ListServicesResponse\x12S\n" +
	"\n" +
	"NewService\x12!.atoms.splitter.NewServiceRequest\x1a\".atoms.splitter.NewServiceResponse\x12V\n" +
	"\vInfoService\x12\".atoms.splitter.InfoServiceRequest\x1a#.atoms.splitter.InfoServiceResponse\x12\\\n" +
	"\rUpdateService\x12$.atoms.splitter.UpdateServiceRequest\x1a%.atoms.splitter.UpdateServiceResponse\x12\\\n" +
	"\rDeleteService\x12$.atoms.splitter.DeleteServiceRequest\x1a%.atoms.splitter.DeleteServiceResponse\x12V\n" +
	"\vListDomains\x12\".atoms.splitter.ListDomainsRequest\x1a#.atoms.splitter.ListDomainsResponse\x12P\n" +
	"\tNewDomain\x12 .atoms.splitter.NewDomainRequest\x1a!.atoms.splitter.NewDomainResponse\x12Y\n" +
	"\fUpdateDomain\x12#.atoms.splitter.UpdateDomainRequest\x1a$.atoms.splitter.UpdateDomainResponse\x12Y\n" +
	"\fDeleteDomain\x12#.atoms.splitter.DeleteDomainRequest\x1a$.atoms.splitter.DeleteDomainResponseB1\n" +
	"\x14co.atoms.splitter.pbP\x01Z\x17go.atoms.co/splitter/pbb\x06proto3"

var (
	file_atoms_splitter_managementapi_proto_rawDescOnce sync.Once
	file_atoms_splitter_managementapi_proto_rawDescData []byte
)

func file_atoms_splitter_managementapi_proto_rawDescGZIP() []byte {
	file_atoms_splitter_managementapi_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_managementapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_managementapi_proto_rawDesc), len(file_atoms_splitter_managementapi_proto_rawDesc)))
	})
	return file_atoms_splitter_managementapi_proto_rawDescData
}

var file_atoms_splitter_managementapi_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_atoms_splitter_managementapi_proto_goTypes = []any{
	(*ListTenantsRequest)(nil),    // 0: atoms.splitter.ListTenantsRequest
	(*ListTenantsResponse)(nil),   // 1: atoms.splitter.ListTenantsResponse
	(*NewTenantRequest)(nil),      // 2: atoms.splitter.NewTenantRequest
	(*NewTenantResponse)(nil),     // 3: atoms.splitter.NewTenantResponse
	(*InfoTenantRequest)(nil),     // 4: atoms.splitter.InfoTenantRequest
	(*InfoTenantResponse)(nil),    // 5: atoms.splitter.InfoTenantResponse
	(*UpdateTenantRequest)(nil),   // 6: atoms.splitter.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),  // 7: atoms.splitter.UpdateTenantResponse
	(*DeleteTenantRequest)(nil),   // 8: atoms.splitter.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),  // 9: atoms.splitter.DeleteTenantResponse
	(*ListServicesRequest)(nil),   // 10: atoms.splitter.ListServicesRequest
	(*ListServicesResponse)(nil),  // 11: atoms.splitter.ListServicesResponse
	(*NewServiceRequest)(nil),     // 12: atoms.splitter.NewServiceRequest
	(*NewServiceResponse)(nil),    // 13: atoms.splitter.NewServiceResponse
	(*InfoServiceRequest)(nil),    // 14: atoms.splitter.InfoServiceRequest
	(*InfoServiceResponse)(nil),   // 15: atoms.splitter.InfoServiceResponse
	(*UpdateServiceRequest)(nil),  // 16: atoms.splitter.UpdateServiceRequest
	(*UpdateServiceResponse)(nil), // 17: atoms.splitter.UpdateServiceResponse
	(*DeleteServiceRequest)(nil),  // 18: atoms.splitter.DeleteServiceRequest
	(*DeleteServiceResponse)(nil), // 19: atoms.splitter.DeleteServiceResponse
	(*ListDomainsRequest)(nil),    // 20: atoms.splitter.ListDomainsRequest
	(*ListDomainsResponse)(nil),   // 21: atoms.splitter.ListDomainsResponse
	(*NewDomainRequest)(nil),      // 22: atoms.splitter.NewDomainRequest
	(*NewDomainResponse)(nil),     // 23: atoms.splitter.NewDomainResponse
	(*UpdateDomainRequest)(nil),   // 24: atoms.splitter.UpdateDomainRequest
	(*UpdateDomainResponse)(nil),  // 25: atoms.splitter.UpdateDomainResponse
	(*DeleteDomainRequest)(nil),   // 26: atoms.splitter.DeleteDomainRequest
	(*DeleteDomainResponse)(nil),  // 27: atoms.splitter.DeleteDomainResponse
	(*TenantInfo)(nil),            // 28: atoms.splitter.TenantInfo
	(*Tenant_Config)(nil),         // 29: atoms.splitter.Tenant.Config
	(*Tenant_Operational)(nil),    // 30: atoms.splitter.Tenant.Operational
	(*ServiceInfoEx)(nil),         // 31: atoms.splitter.ServiceInfoEx
	(*QualifiedServiceName)(nil),  // 32: atoms.splitter.QualifiedServiceName
	(*Service_Config)(nil),        // 33: atoms.splitter.Service.Config
	(*ServiceInfo)(nil),           // 34: atoms.splitter.ServiceInfo
	(*Service_Operational)(nil),   // 35: atoms.splitter.Service.Operational
	(*Domain)(nil),                // 36: atoms.splitter.Domain
	(*QualifiedDomainName)(nil),   // 37: atoms.splitter.QualifiedDomainName
	(DomainType)(0),               // 38: atoms.splitter.DomainType
	(*Domain_Config)(nil),         // 39: atoms.splitter.Domain.Config
	(Domain_State)(0),             // 40: atoms.splitter.Domain.State
	(*Domain_Operational)(nil),    // 41: atoms.splitter.Domain.Operational
}
var file_atoms_splitter_managementapi_proto_depIdxs = []int32{
	28, // 0: atoms.splitter.ListTenantsResponse.tenants:type_name -> atoms.splitter.TenantInfo
	29, // 1: atoms.splitter.NewTenantRequest.config:type_name -> atoms.splitter.Tenant.Config
	28, // 2: atoms.splitter.NewTenantResponse.tenant:type_name -> atoms.splitter.TenantInfo
	28, // 3: atoms.splitter.InfoTenantResponse.tenant:type_name -> atoms.splitter.TenantInfo
	29, // 4: atoms.splitter.UpdateTenantRequest.config:type_name -> atoms.splitter.Tenant.Config
	30, // 5: atoms.splitter.UpdateTenantRequest.operational:type_name -> atoms.splitter.Tenant.Operational
	28, // 6: atoms.splitter.UpdateTenantResponse.tenant:type_name -> atoms.splitter.TenantInfo
	31, // 7: atoms.splitter.ListServicesResponse.services:type_name -> atoms.splitter.ServiceInfoEx
	32, // 8: atoms.splitter.NewServiceRequest.name:type_name -> atoms.splitter.QualifiedServiceName
	33, // 9: atoms.splitter.NewServiceRequest.config:type_name -> atoms.splitter.Service.Config
	34, // 10: atoms.splitter.NewServiceResponse.service:type_name -> atoms.splitter.ServiceInfo
	32, // 11: atoms.splitter.InfoServiceRequest.name:type_name -> atoms.splitter.QualifiedServiceName
	31, // 12: atoms.splitter.InfoServiceResponse.service:type_name -> atoms.splitter.ServiceInfoEx
	32, // 13: atoms.splitter.UpdateServiceRequest.name:type_name -> atoms.splitter.QualifiedServiceName
	33, // 14: atoms.splitter.UpdateServiceRequest.config:type_name -> atoms.splitter.Service.Config
	35, // 15: atoms.splitter.UpdateServiceRequest.operational:type_name -> atoms.splitter.Service.Operational
	34, // 16: atoms.splitter.UpdateServiceResponse.service:type_name -> atoms.splitter.ServiceInfo
	32, // 17: atoms.splitter.DeleteServiceRequest.name:type_name -> atoms.splitter.QualifiedServiceName
	32, // 18: atoms.splitter.ListDomainsRequest.service:type_name -> atoms.splitter.QualifiedServiceName
	36, // 19: atoms.splitter.ListDomainsResponse.domains:type_name -> atoms.splitter.Domain
	37, // 20: atoms.splitter.NewDomainRequest.name:type_name -> atoms.splitter.QualifiedDomainName
	38, // 21: atoms.splitter.NewDomainRequest.type:type_name -> atoms.splitter.DomainType
	39, // 22: atoms.splitter.NewDomainRequest.config:type_name -> atoms.splitter.Domain.Config
	40, // 23: atoms.splitter.NewDomainRequest.state:type_name -> atoms.splitter.Domain.State
	36, // 24: atoms.splitter.NewDomainResponse.domain:type_name -> atoms.splitter.Domain
	37, // 25: atoms.splitter.UpdateDomainRequest.name:type_name -> atoms.splitter.QualifiedDomainName
	39, // 26: atoms.splitter.UpdateDomainRequest.config:type_name -> atoms.splitter.Domain.Config
	40, // 27: atoms.splitter.UpdateDomainRequest.state:type_name -> atoms.splitter.Domain.State
	41, // 28: atoms.splitter.UpdateDomainRequest.operational:type_name -> atoms.splitter.Domain.Operational
	36, // 29: atoms.splitter.UpdateDomainResponse.domain:type_name -> atoms.splitter.Domain
	37, // 30: atoms.splitter.DeleteDomainRequest.name:type_name -> atoms.splitter.QualifiedDomainName
	0,  // 31: atoms.splitter.ManagementService.ListTenants:input_type -> atoms.splitter.ListTenantsRequest
	2,  // 32: atoms.splitter.ManagementService.NewTenant:input_type -> atoms.splitter.NewTenantRequest
	4,  // 33: atoms.splitter.ManagementService.InfoTenant:input_type -> atoms.splitter.InfoTenantRequest
	6,  // 34: atoms.splitter.ManagementService.UpdateTenant:input_type -> atoms.splitter.UpdateTenantRequest
	8,  // 35: atoms.splitter.ManagementService.DeleteTenant:input_type -> atoms.splitter.DeleteTenantRequest
	10, // 36: atoms.splitter.ManagementService.ListServices:input_type -> atoms.splitter.ListServicesRequest
	12, // 37: atoms.splitter.ManagementService.NewService:input_type -> atoms.splitter.NewServiceRequest
	14, // 38: atoms.splitter.ManagementService.InfoService:input_type -> atoms.splitter.InfoServiceRequest
	16, // 39: atoms.splitter.ManagementService.UpdateService:input_type -> atoms.splitter.UpdateServiceRequest
	18, // 40: atoms.splitter.ManagementService.DeleteService:input_type -> atoms.splitter.DeleteServiceRequest
	20, // 41: atoms.splitter.ManagementService.ListDomains:input_type -> atoms.splitter.ListDomainsRequest
	22, // 42: atoms.splitter.ManagementService.NewDomain:input_type -> atoms.splitter.NewDomainRequest
	24, // 43: atoms.splitter.ManagementService.UpdateDomain:input_type -> atoms.splitter.UpdateDomainRequest
	26, // 44: atoms.splitter.ManagementService.DeleteDomain:input_type -> atoms.splitter.DeleteDomainRequest
	1,  // 45: atoms.splitter.ManagementService.ListTenants:output_type -> atoms.splitter.ListTenantsResponse
	3,  // 46: atoms.splitter.ManagementService.NewTenant:output_type -> atoms.splitter.NewTenantResponse
	5,  // 47: atoms.splitter.ManagementService.InfoTenant:output_type -> atoms.splitter.InfoTenantResponse
	7,  // 48: atoms.splitter.ManagementService.UpdateTenant:output_type -> atoms.splitter.UpdateTenantResponse
	9,  // 49: atoms.splitter.ManagementService.DeleteTenant:output_type -> atoms.splitter.DeleteTenantResponse
	11, // 50: atoms.splitter.ManagementService.ListServices:output_type -> atoms.splitter.ListServicesResponse
	13, // 51: atoms.splitter.ManagementService.NewService:output_type -> atoms.splitter.NewServiceResponse
	15, // 52: atoms.splitter.ManagementService.InfoService:output_type -> atoms.splitter.InfoServiceResponse
	17, // 53: atoms.splitter.ManagementService.UpdateService:output_type -> atoms.splitter.UpdateServiceResponse
	19, // 54: atoms.splitter.ManagementService.DeleteService:output_type -> atoms.splitter.DeleteServiceResponse
	21, // 55: atoms.splitter.ManagementService.ListDomains:output_type -> atoms.splitter.ListDomainsResponse
	23, // 56: atoms.splitter.ManagementService.NewDomain:output_type -> atoms.splitter.NewDomainResponse
	25, // 57: atoms.splitter.ManagementService.UpdateDomain:output_type -> atoms.splitter.UpdateDomainResponse
	27, // 58: atoms.splitter.ManagementService.DeleteDomain:output_type -> atoms.splitter.DeleteDomainResponse
	45, // [45:59] is the sub-list for method output_type
	31, // [31:45] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_atoms_splitter_managementapi_proto_init() }
func file_atoms_splitter_managementapi_proto_init() {
	if File_atoms_splitter_managementapi_proto != nil {
		return
	}
	file_atoms_splitter_model_proto_init()
	file_atoms_splitter_management_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_managementapi_proto_rawDesc), len(file_atoms_splitter_managementapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_managementapi_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_managementapi_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_managementapi_proto_msgTypes,
	}.Build()
	File_atoms_splitter_managementapi_proto = out.File
	file_atoms_splitter_managementapi_proto_goTypes = nil
	file_atoms_splitter_managementapi_proto_depIdxs = nil
}
