// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/management.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain_State int32

const (
	Domain_UNKNOWN   Domain_State = 0
	Domain_ACTIVE    Domain_State = 1
	Domain_SUSPENDED Domain_State = 2
)

// Enum value maps for Domain_State.
var (
	Domain_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "SUSPENDED",
	}
	Domain_State_value = map[string]int32{
		"UNKNOWN":   0,
		"ACTIVE":    1,
		"SUSPENDED": 2,
	}
)

func (x Domain_State) Enum() *Domain_State {
	p := new(Domain_State)
	*p = x
	return p
}

func (x Domain_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain_State) Descriptor() protoreflect.EnumDescriptor {
	return file_atoms_splitter_management_proto_enumTypes[0].Descriptor()
}

func (Domain_State) Type() protoreflect.EnumType {
	return &file_atoms_splitter_management_proto_enumTypes[0]
}

func (x Domain_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain_State.Descriptor instead.
func (Domain_State) EnumDescriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{5, 0}
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *Tenant_Config         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Operational   *Tenant_Operational    `protobuf:"bytes,4,opt,name=operational,proto3" json:"operational,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_atoms_splitter_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetConfig() *Tenant_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Tenant) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Tenant) GetOperational() *Tenant_Operational {
	if x != nil {
		return x.Operational
	}
	return nil
}

type TenantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_atoms_splitter_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{1}
}

func (x *TenantInfo) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *TenantInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TenantInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedServiceName  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *Service_Config        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Operational   *Service_Operational   `protobuf:"bytes,4,opt,name=operational,proto3" json:"operational,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_atoms_splitter_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetName() *QualifiedServiceName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Service) GetConfig() *Service_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Service) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Service) GetOperational() *Service_Operational {
	if x != nil {
		return x.Operational
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_atoms_splitter_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceInfo) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServiceInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ServiceInfoEx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Domains       []*Domain              `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfoEx) Reset() {
	*x = ServiceInfoEx{}
	mi := &file_atoms_splitter_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfoEx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoEx) ProtoMessage() {}

func (x *ServiceInfoEx) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoEx.ProtoReflect.Descriptor instead.
func (*ServiceInfoEx) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInfoEx) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceInfoEx) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedDomainName   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DomainType             `protobuf:"varint,2,opt,name=type,proto3,enum=atoms.splitter.DomainType" json:"type,omitempty"`
	State         Domain_State           `protobuf:"varint,3,opt,name=state,proto3,enum=atoms.splitter.Domain_State" json:"state,omitempty"`
	Config        *Domain_Config         `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Operational   *Domain_Operational    `protobuf:"bytes,6,opt,name=operational,proto3" json:"operational,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_atoms_splitter_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{5}
}

func (x *Domain) GetName() *QualifiedDomainName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Domain) GetType() DomainType {
	if x != nil {
		return x.Type
	}
	return DomainType_INVALID
}

func (x *Domain) GetState() Domain_State {
	if x != nil {
		return x.State
	}
	return Domain_UNKNOWN
}

func (x *Domain) GetConfig() *Domain_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Domain) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Domain) GetOperational() *Domain_Operational {
	if x != nil {
		return x.Operational
	}
	return nil
}

type ShardingPolicy struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Shards        int64                   `protobuf:"varint,1,opt,name=shards,proto3" json:"shards,omitempty"`
	CustomShards  []*ShardingPolicy_Shard `protobuf:"bytes,2,rep,name=custom_shards,json=customShards,proto3" json:"custom_shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardingPolicy) Reset() {
	*x = ShardingPolicy{}
	mi := &file_atoms_splitter_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingPolicy) ProtoMessage() {}

func (x *ShardingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingPolicy.ProtoReflect.Descriptor instead.
func (*ShardingPolicy) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{6}
}

func (x *ShardingPolicy) GetShards() int64 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *ShardingPolicy) GetCustomShards() []*ShardingPolicy_Shard {
	if x != nil {
		return x.CustomShards
	}
	return nil
}

type Tenant_Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant_Config) Reset() {
	*x = Tenant_Config{}
	mi := &file_atoms_splitter_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant_Config) ProtoMessage() {}

func (x *Tenant_Config) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant_Config.ProtoReflect.Descriptor instead.
func (*Tenant_Config) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{0, 0}
}

type Tenant_Operational struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannedRegions []string               `protobuf:"bytes,1,rep,name=banned_regions,json=bannedRegions,proto3" json:"banned_regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant_Operational) Reset() {
	*x = Tenant_Operational{}
	mi := &file_atoms_splitter_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant_Operational) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant_Operational) ProtoMessage() {}

func (x *Tenant_Operational) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant_Operational.ProtoReflect.Descriptor instead.
func (*Tenant_Operational) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Tenant_Operational) GetBannedRegions() []string {
	if x != nil {
		return x.BannedRegions
	}
	return nil
}

type Service_Config struct {
	state                 protoimpl.MessageState             `protogen:"open.v1"`
	Region                string                             `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	DefaultShardingPolicy *ShardingPolicy                    `protobuf:"bytes,2,opt,name=default_sharding_policy,json=defaultShardingPolicy,proto3" json:"default_sharding_policy,omitempty"`
	Overrides             []*Service_Config_LocalityOverride `protobuf:"bytes,3,rep,name=overrides,proto3" json:"overrides,omitempty"`
	Regions               []string                           `protobuf:"bytes,4,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Service_Config) Reset() {
	*x = Service_Config{}
	mi := &file_atoms_splitter_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Config) ProtoMessage() {}

func (x *Service_Config) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Config.ProtoReflect.Descriptor instead.
func (*Service_Config) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Service_Config) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Service_Config) GetDefaultShardingPolicy() *ShardingPolicy {
	if x != nil {
		return x.DefaultShardingPolicy
	}
	return nil
}

func (x *Service_Config) GetOverrides() []*Service_Config_LocalityOverride {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *Service_Config) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type Service_Operational struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BannedRegions      []string               `protobuf:"bytes,1,rep,name=banned_regions,json=bannedRegions,proto3" json:"banned_regions,omitempty"`
	DisableLoadBalance bool                   `protobuf:"varint,2,opt,name=disable_load_balance,json=disableLoadBalance,proto3" json:"disable_load_balance,omitempty"`
	Locked             bool                   `protobuf:"varint,3,opt,name=locked,proto3" json:"locked,omitempty"`
	VerboseLogging     bool                   `protobuf:"varint,4,opt,name=verbose_logging,json=verboseLogging,proto3" json:"verbose_logging,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Service_Operational) Reset() {
	*x = Service_Operational{}
	mi := &file_atoms_splitter_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Operational) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Operational) ProtoMessage() {}

func (x *Service_Operational) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Operational.ProtoReflect.Descriptor instead.
func (*Service_Operational) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Service_Operational) GetBannedRegions() []string {
	if x != nil {
		return x.BannedRegions
	}
	return nil
}

func (x *Service_Operational) GetDisableLoadBalance() bool {
	if x != nil {
		return x.DisableLoadBalance
	}
	return false
}

func (x *Service_Operational) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *Service_Operational) GetVerboseLogging() bool {
	if x != nil {
		return x.VerboseLogging
	}
	return false
}

type Service_Config_LocalityOverride struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShardRegion    string                 `protobuf:"bytes,1,opt,name=shard_region,json=shardRegion,proto3" json:"shard_region,omitempty"`
	ConsumerRegion string                 `protobuf:"bytes,2,opt,name=consumer_region,json=consumerRegion,proto3" json:"consumer_region,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Service_Config_LocalityOverride) Reset() {
	*x = Service_Config_LocalityOverride{}
	mi := &file_atoms_splitter_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Config_LocalityOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Config_LocalityOverride) ProtoMessage() {}

func (x *Service_Config_LocalityOverride) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Config_LocalityOverride.ProtoReflect.Descriptor instead.
func (*Service_Config_LocalityOverride) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Service_Config_LocalityOverride) GetShardRegion() string {
	if x != nil {
		return x.ShardRegion
	}
	return ""
}

func (x *Service_Config_LocalityOverride) GetConsumerRegion() string {
	if x != nil {
		return x.ConsumerRegion
	}
	return ""
}

type Domain_Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Placement      string                 `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"`
	Regions        []string               `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	ShardingPolicy *ShardingPolicy        `protobuf:"bytes,3,opt,name=sharding_policy,json=shardingPolicy,proto3" json:"sharding_policy,omitempty"`
	AntiAffinity   []string               `protobuf:"bytes,4,rep,name=anti_affinity,json=antiAffinity,proto3" json:"anti_affinity,omitempty"`
	Named          []*NamedDomainKey      `protobuf:"bytes,5,rep,name=named,proto3" json:"named,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Domain_Config) Reset() {
	*x = Domain_Config{}
	mi := &file_atoms_splitter_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain_Config) ProtoMessage() {}

func (x *Domain_Config) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain_Config.ProtoReflect.Descriptor instead.
func (*Domain_Config) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Domain_Config) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *Domain_Config) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *Domain_Config) GetShardingPolicy() *ShardingPolicy {
	if x != nil {
		return x.ShardingPolicy
	}
	return nil
}

func (x *Domain_Config) GetAntiAffinity() []string {
	if x != nil {
		return x.AntiAffinity
	}
	return nil
}

func (x *Domain_Config) GetNamed() []*NamedDomainKey {
	if x != nil {
		return x.Named
	}
	return nil
}

type Domain_Operational struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannedRegions []string               `protobuf:"bytes,1,rep,name=banned_regions,json=bannedRegions,proto3" json:"banned_regions,omitempty"`
	Locked        bool                   `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain_Operational) Reset() {
	*x = Domain_Operational{}
	mi := &file_atoms_splitter_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain_Operational) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain_Operational) ProtoMessage() {}

func (x *Domain_Operational) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain_Operational.ProtoReflect.Descriptor instead.
func (*Domain_Operational) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Domain_Operational) GetBannedRegions() []string {
	if x != nil {
		return x.BannedRegions
	}
	return nil
}

func (x *Domain_Operational) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type ShardingPolicy_Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardingPolicy_Shard) Reset() {
	*x = ShardingPolicy_Shard{}
	mi := &file_atoms_splitter_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingPolicy_Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingPolicy_Shard) ProtoMessage() {}

func (x *ShardingPolicy_Shard) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingPolicy_Shard.ProtoReflect.Descriptor instead.
func (*ShardingPolicy_Shard) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_management_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ShardingPolicy_Shard) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ShardingPolicy_Shard) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ShardingPolicy_Shard) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_atoms_splitter_management_proto protoreflect.FileDescriptor

const file_atoms_splitter_management_proto_rawDesc = "" +
	"\n" +
	"\x1fatoms/splitter/management.proto\x12\x0eatoms.splitter\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aatoms/splitter/model.proto\"\x8f\x02\n" +
	"\x06Tenant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.atoms.splitter.Tenant.ConfigR\x06config\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12D\n" +
	"\voperational\x18\x04 \x01(\v2\".atoms.splitter.Tenant.OperationalR\voperational\x1a\b\n" +
	"\x06Config\x1a4\n" +
	"\vOperational\x12%\n" +
	"\x0ebanned_regions\x18\x01 \x03(\tR\rbannedRegions\"\x90\x01\n" +
	"\n" +
	"TenantInfo\x12.\n" +
	"\x06tenant\x18\x01 \x01(\v2\x16.atoms.splitter.TenantR\x06tenant\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe6\x05\n" +
	"\aService\x128\n" +
	"\x04name\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\x04name\x126\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.atoms.splitter.Service.ConfigR\x06config\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12E\n" +
	"\voperational\x18\x04 \x01(\v2#.atoms.splitter.Service.OperationalR\voperational\x1a\xc1\x02\n" +
	"\x06Config\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12V\n" +
	"\x17default_sharding_policy\x18\x02 \x01(\v2\x1e.atoms.splitter.ShardingPolicyR\x15defaultShardingPolicy\x12M\n" +
	"\toverrides\x18\x03 \x03(\v2/.atoms.splitter.Service.Config.LocalityOverrideR\toverrides\x12\x18\n" +
	"\aregions\x18\x04 \x03(\tR\aregions\x1a^\n" +
	"\x10LocalityOverride\x12!\n" +
	"\fshard_region\x18\x01 \x01(\tR\vshardRegion\x12'\n" +
	"\x0fconsumer_region\x18\x02 \x01(\tR\x0econsumerRegion\x1a\xa7\x01\n" +
	"\vOperational\x12%\n" +
	"\x0ebanned_regions\x18\x01 \x03(\tR\rbannedRegions\x120\n" +
	"\x14disable_load_balance\x18\x02 \x01(\bR\x12disableLoadBalance\x12\x16\n" +
	"\x06locked\x18\x03 \x01(\bR\x06locked\x12'\n" +
	"\x0fverbose_logging\x18\x04 \x01(\bR\x0everboseLogging\"\x94\x01\n" +
	"\vServiceInfo\x121\n" +
	"\aservice\x18\x01 \x01(\v2\x17.atoms.splitter.ServiceR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"x\n" +
	"\rServiceInfoEx\x125\n" +
	"\aservice\x18\x01 \x01(\v2\x1b.atoms.splitter.ServiceInfoR\aservice\x120\n" +
	"\adomains\x18\x02 \x03(\v2\x16.atoms.splitter.DomainR\adomains\"\xbe\x05\n" +
	"\x06Domain\x127\n" +
	"\x04name\x18\x01 \x01(\v2#.atoms.splitter.QualifiedDomainNameR\x04name\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.atoms.splitter.DomainTypeR\x04type\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.atoms.splitter.Domain.StateR\x05state\x125\n" +
	"\x06config\x18\x04 \x01(\v2\x1d.atoms.splitter.Domain.ConfigR\x06config\x124\n" +
	"\acreated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12D\n" +
	"\voperational\x18\x06 \x01(\v2\".atoms.splitter.Domain.OperationalR\voperational\x1a\xe4\x01\n" +
	"\x06Config\x12\x1c\n" +
	"\tplacement\x18\x01 \x01(\tR\tplacement\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\x12G\n" +
	"\x0fsharding_policy\x18\x03 \x01(\v2\x1e.atoms.splitter.ShardingPolicyR\x0eshardingPolicy\x12#\n" +
	"\ranti_affinity\x18\x04 \x03(\tR\fantiAffinity\x124\n" +
	"\x05named\x18\x05 \x03(\v2\x1e.atoms.splitter.NamedDomainKeyR\x05named\x1aL\n" +
	"\vOperational\x12%\n" +
	"\x0ebanned_regions\x18\x01 \x03(\tR\rbannedRegions\x12\x16\n" +
	"\x06locked\x18\x02 \x01(\bR\x06locked\"/\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tSUSPENDED\x10\x02\"\xb8\x01\n" +
	"\x0eShardingPolicy\x12\x16\n" +
	"\x06shards\x18\x01 \x01(\x03R\x06shards\x12I\n" +
	"\rcustom_shards\x18\x02 \x03(\v2$.atoms.splitter.ShardingPolicy.ShardR\fcustomShards\x1aC\n" +
	"\x05Shard\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06regionB1\n" +
	"\x14co.atoms.splitter.pbP\x01Z\x17go.atoms.co/splitter/pbb\x06proto3"

var (
	file_atoms_splitter_management_proto_rawDescOnce sync.Once
	file_atoms_splitter_management_proto_rawDescData []byte
)

func file_atoms_splitter_management_proto_rawDescGZIP() []byte {
	file_atoms_splitter_management_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_management_proto_rawDesc), len(file_atoms_splitter_management_proto_rawDesc)))
	})
	return file_atoms_splitter_management_proto_rawDescData
}

var file_atoms_splitter_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_atoms_splitter_management_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_atoms_splitter_management_proto_goTypes = []any{
	(Domain_State)(0),                       // 0: atoms.splitter.Domain.State
	(*Tenant)(nil),                          // 1: atoms.splitter.Tenant
	(*TenantInfo)(nil),                      // 2: atoms.splitter.TenantInfo
	(*Service)(nil),                         // 3: atoms.splitter.Service
	(*ServiceInfo)(nil),                     // 4: atoms.splitter.ServiceInfo
	(*ServiceInfoEx)(nil),                   // 5: atoms.splitter.ServiceInfoEx
	(*Domain)(nil),                          // 6: atoms.splitter.Domain
	(*ShardingPolicy)(nil),                  // 7: atoms.splitter.ShardingPolicy
	(*Tenant_Config)(nil),                   // 8: atoms.splitter.Tenant.Config
	(*Tenant_Operational)(nil),              // 9: atoms.splitter.Tenant.Operational
	(*Service_Config)(nil),                  // 10: atoms.splitter.Service.Config
	(*Service_Operational)(nil),             // 11: atoms.splitter.Service.Operational
	(*Service_Config_LocalityOverride)(nil), // 12: atoms.splitter.Service.Config.LocalityOverride
	(*Domain_Config)(nil),                   // 13: atoms.splitter.Domain.Config
	(*Domain_Operational)(nil),              // 14: atoms.splitter.Domain.Operational
	(*ShardingPolicy_Shard)(nil),            // 15: atoms.splitter.ShardingPolicy.Shard
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
	(*QualifiedServiceName)(nil),            // 17: atoms.splitter.QualifiedServiceName
	(*QualifiedDomainName)(nil),             // 18: atoms.splitter.QualifiedDomainName
	(DomainType)(0),                         // 19: atoms.splitter.DomainType
	(*NamedDomainKey)(nil),                  // 20: atoms.splitter.NamedDomainKey
}
var file_atoms_splitter_management_proto_depIdxs = []int32{
	8,  // 0: atoms.splitter.Tenant.config:type_name -> atoms.splitter.Tenant.Config
	16, // 1: atoms.splitter.Tenant.created:type_name -> google.protobuf.Timestamp
	9,  // 2: atoms.splitter.Tenant.operational:type_name -> atoms.splitter.Tenant.Operational
	1,  // 3: atoms.splitter.TenantInfo.tenant:type_name -> atoms.splitter.Tenant
	16, // 4: atoms.splitter.TenantInfo.timestamp:type_name -> google.protobuf.Timestamp
	17, // 5: atoms.splitter.Service.name:type_name -> atoms.splitter.QualifiedServiceName
	10, // 6: atoms.splitter.Service.config:type_name -> atoms.splitter.Service.Config
	16, // 7: atoms.splitter.Service.created:type_name -> google.protobuf.Timestamp
	11, // 8: atoms.splitter.Service.operational:type_name -> atoms.splitter.Service.Operational
	3,  // 9: atoms.splitter.ServiceInfo.service:type_name -> atoms.splitter.Service
	16, // 10: atoms.splitter.ServiceInfo.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 11: atoms.splitter.ServiceInfoEx.service:type_name -> atoms.splitter.ServiceInfo
	6,  // 12: atoms.splitter.ServiceInfoEx.domains:type_name -> atoms.splitter.Domain
	18, // 13: atoms.splitter.Domain.name:type_name -> atoms.splitter.QualifiedDomainName
	19, // 14: atoms.splitter.Domain.type:type_name -> atoms.splitter.DomainType
	0,  // 15: atoms.splitter.Domain.state:type_name -> atoms.splitter.Domain.State
	13, // 16: atoms.splitter.Domain.config:type_name -> atoms.splitter.Domain.Config
	16, // 17: atoms.splitter.Domain.created:type_name -> google.protobuf.Timestamp
	14, // 18: atoms.splitter.Domain.operational:type_name -> atoms.splitter.Domain.Operational
	15, // 19: atoms.splitter.ShardingPolicy.custom_shards:type_name -> atoms.splitter.ShardingPolicy.Shard
	7,  // 20: atoms.splitter.Service.Config.default_sharding_policy:type_name -> atoms.splitter.ShardingPolicy
	12, // 21: atoms.splitter.Service.Config.overrides:type_name -> atoms.splitter.Service.Config.LocalityOverride
	7,  // 22: atoms.splitter.Domain.Config.sharding_policy:type_name -> atoms.splitter.ShardingPolicy
	20, // 23: atoms.splitter.Domain.Config.named:type_name -> atoms.splitter.NamedDomainKey
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_atoms_splitter_management_proto_init() }
func file_atoms_splitter_management_proto_init() {
	if File_atoms_splitter_management_proto != nil {
		return
	}
	file_atoms_splitter_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_management_proto_rawDesc), len(file_atoms_splitter_management_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_management_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_management_proto_depIdxs,
		EnumInfos:         file_atoms_splitter_management_proto_enumTypes,
		MessageInfos:      file_atoms_splitter_management_proto_msgTypes,
	}.Build()
	File_atoms_splitter_management_proto = out.File
	file_atoms_splitter_management_proto_goTypes = nil
	file_atoms_splitter_management_proto_depIdxs = nil
}
