// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/model.proto

package pb

import (
	pb "go.atoms.co/splitter/lib/service/location/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainType int32

const (
	DomainType_INVALID  DomainType = 0
	DomainType_UNIT     DomainType = 1
	DomainType_GLOBAL   DomainType = 2
	DomainType_REGIONAL DomainType = 3
)

// Enum value maps for DomainType.
var (
	DomainType_name = map[int32]string{
		0: "INVALID",
		1: "UNIT",
		2: "GLOBAL",
		3: "REGIONAL",
	}
	DomainType_value = map[string]int32{
		"INVALID":  0,
		"UNIT":     1,
		"GLOBAL":   2,
		"REGIONAL": 3,
	}
)

func (x DomainType) Enum() *DomainType {
	p := new(DomainType)
	*p = x
	return p
}

func (x DomainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainType) Descriptor() protoreflect.EnumDescriptor {
	return file_atoms_splitter_model_proto_enumTypes[0].Descriptor()
}

func (DomainType) Type() protoreflect.EnumType {
	return &file_atoms_splitter_model_proto_enumTypes[0]
}

func (x DomainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainType.Descriptor instead.
func (DomainType) EnumDescriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{0}
}

type GrantState int32

const (
	GrantState_UNKNOWN          GrantState = 0
	GrantState_ACTIVE           GrantState = 1
	GrantState_ALLOCATED        GrantState = 2
	GrantState_REVOKED          GrantState = 3
	GrantState_ALLOCATED_LOADED GrantState = 4
	GrantState_REVOKED_UNLOADED GrantState = 5
)

// Enum value maps for GrantState.
var (
	GrantState_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "ALLOCATED",
		3: "REVOKED",
		4: "ALLOCATED_LOADED",
		5: "REVOKED_UNLOADED",
	}
	GrantState_value = map[string]int32{
		"UNKNOWN":          0,
		"ACTIVE":           1,
		"ALLOCATED":        2,
		"REVOKED":          3,
		"ALLOCATED_LOADED": 4,
		"REVOKED_UNLOADED": 5,
	}
)

func (x GrantState) Enum() *GrantState {
	p := new(GrantState)
	*p = x
	return p
}

func (x GrantState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrantState) Descriptor() protoreflect.EnumDescriptor {
	return file_atoms_splitter_model_proto_enumTypes[1].Descriptor()
}

func (GrantState) Type() protoreflect.EnumType {
	return &file_atoms_splitter_model_proto_enumTypes[1]
}

func (x GrantState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrantState.Descriptor instead.
func (GrantState) EnumDescriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{1}
}

type QualifiedServiceName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifiedServiceName) Reset() {
	*x = QualifiedServiceName{}
	mi := &file_atoms_splitter_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifiedServiceName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifiedServiceName) ProtoMessage() {}

func (x *QualifiedServiceName) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifiedServiceName.ProtoReflect.Descriptor instead.
func (*QualifiedServiceName) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{0}
}

func (x *QualifiedServiceName) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *QualifiedServiceName) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type QualifiedDomainName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *QualifiedServiceName  `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifiedDomainName) Reset() {
	*x = QualifiedDomainName{}
	mi := &file_atoms_splitter_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifiedDomainName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifiedDomainName) ProtoMessage() {}

func (x *QualifiedDomainName) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifiedDomainName.ProtoReflect.Descriptor instead.
func (*QualifiedDomainName) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{1}
}

func (x *QualifiedDomainName) GetService() *QualifiedServiceName {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *QualifiedDomainName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DomainKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainKey) Reset() {
	*x = DomainKey{}
	mi := &file_atoms_splitter_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainKey) ProtoMessage() {}

func (x *DomainKey) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainKey.ProtoReflect.Descriptor instead.
func (*DomainKey) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{2}
}

func (x *DomainKey) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DomainKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type NamedDomainKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           *DomainKey             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedDomainKey) Reset() {
	*x = NamedDomainKey{}
	mi := &file_atoms_splitter_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedDomainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedDomainKey) ProtoMessage() {}

func (x *NamedDomainKey) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedDomainKey.ProtoReflect.Descriptor instead.
func (*NamedDomainKey) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{3}
}

func (x *NamedDomainKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedDomainKey) GetKey() *DomainKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type DomainKeyName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainKeyName) Reset() {
	*x = DomainKeyName{}
	mi := &file_atoms_splitter_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainKeyName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainKeyName) ProtoMessage() {}

func (x *DomainKeyName) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainKeyName.ProtoReflect.Descriptor instead.
func (*DomainKeyName) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{4}
}

func (x *DomainKeyName) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainKeyName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QualifiedDomainKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *QualifiedDomainName   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Key           *DomainKey             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifiedDomainKey) Reset() {
	*x = QualifiedDomainKey{}
	mi := &file_atoms_splitter_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifiedDomainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifiedDomainKey) ProtoMessage() {}

func (x *QualifiedDomainKey) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifiedDomainKey.ProtoReflect.Descriptor instead.
func (*QualifiedDomainKey) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{5}
}

func (x *QualifiedDomainKey) GetDomain() *QualifiedDomainName {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *QualifiedDomainKey) GetKey() *DomainKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *QualifiedDomainName   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Type          DomainType             `protobuf:"varint,2,opt,name=type,proto3,enum=atoms.splitter.DomainType" json:"type,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_atoms_splitter_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{6}
}

func (x *Shard) GetDomain() *QualifiedDomainName {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *Shard) GetType() DomainType {
	if x != nil {
		return x.Type
	}
	return DomainType_INVALID
}

func (x *Shard) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Shard) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Shard) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *pb.Instance           `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_atoms_splitter_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{7}
}

func (x *Instance) GetInstance() *pb.Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *Instance) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	State         GrantState             `protobuf:"varint,3,opt,name=state,proto3,enum=atoms.splitter.GrantState" json:"state,omitempty"`
	Lease         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease,proto3" json:"lease,omitempty"`
	Assigned      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=assigned,proto3" json:"assigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_atoms_splitter_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_model_proto_rawDescGZIP(), []int{8}
}

func (x *Grant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grant) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *Grant) GetState() GrantState {
	if x != nil {
		return x.State
	}
	return GrantState_UNKNOWN
}

func (x *Grant) GetLease() *timestamppb.Timestamp {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *Grant) GetAssigned() *timestamppb.Timestamp {
	if x != nil {
		return x.Assigned
	}
	return nil
}

var File_atoms_splitter_model_proto protoreflect.FileDescriptor

const file_atoms_splitter_model_proto_rawDesc = "" +
	"\n" +
	"\x1aatoms/splitter/model.proto\x12\x0eatoms.splitter\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2atoms/splitter/lib/service/location/location.proto\"H\n" +
	"\x14QualifiedServiceName\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"i\n" +
	"\x13QualifiedDomainName\x12>\n" +
	"\aservice\x18\x01 \x01(\v2$.atoms.splitter.QualifiedServiceNameR\aservice\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\tDomainKey\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"Q\n" +
	"\x0eNamedDomainKey\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x03key\x18\x02 \x01(\v2\x19.atoms.splitter.DomainKeyR\x03key\";\n" +
	"\rDomainKeyName\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"~\n" +
	"\x12QualifiedDomainKey\x12;\n" +
	"\x06domain\x18\x01 \x01(\v2#.atoms.splitter.QualifiedDomainNameR\x06domain\x12+\n" +
	"\x03key\x18\x02 \x01(\v2\x19.atoms.splitter.DomainKeyR\x03key\"\xb0\x01\n" +
	"\x05Shard\x12;\n" +
	"\x06domain\x18\x01 \x01(\v2#.atoms.splitter.QualifiedDomainNameR\x06domain\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.atoms.splitter.DomainTypeR\x04type\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"q\n" +
	"\bInstance\x12I\n" +
	"\binstance\x18\x01 \x01(\v2-.atoms.splitter.lib.service.location.InstanceR\binstance\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"\xe0\x01\n" +
	"\x05Grant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x05shard\x18\x02 \x01(\v2\x15.atoms.splitter.ShardR\x05shard\x120\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1a.atoms.splitter.GrantStateR\x05state\x120\n" +
	"\x05lease\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05lease\x126\n" +
	"\bassigned\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bassigned*=\n" +
	"\n" +
	"DomainType\x12\v\n" +
	"\aINVALID\x10\x00\x12\b\n" +
	"\x04UNIT\x10\x01\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x02\x12\f\n" +
	"\bREGIONAL\x10\x03*m\n" +
	"\n" +
	"GrantState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tALLOCATED\x10\x02\x12\v\n" +
	"\aREVOKED\x10\x03\x12\x14\n" +
	"\x10ALLOCATED_LOADED\x10\x04\x12\x14\n" +
	"\x10REVOKED_UNLOADED\x10\x05B1\n" +
	"\x14co.atoms.splitter.pbP\x01Z\x17go.atoms.co/splitter/pbb\x06proto3"

var (
	file_atoms_splitter_model_proto_rawDescOnce sync.Once
	file_atoms_splitter_model_proto_rawDescData []byte
)

func file_atoms_splitter_model_proto_rawDescGZIP() []byte {
	file_atoms_splitter_model_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_model_proto_rawDesc), len(file_atoms_splitter_model_proto_rawDesc)))
	})
	return file_atoms_splitter_model_proto_rawDescData
}

var file_atoms_splitter_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_atoms_splitter_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_atoms_splitter_model_proto_goTypes = []any{
	(DomainType)(0),               // 0: atoms.splitter.DomainType
	(GrantState)(0),               // 1: atoms.splitter.GrantState
	(*QualifiedServiceName)(nil),  // 2: atoms.splitter.QualifiedServiceName
	(*QualifiedDomainName)(nil),   // 3: atoms.splitter.QualifiedDomainName
	(*DomainKey)(nil),             // 4: atoms.splitter.DomainKey
	(*NamedDomainKey)(nil),        // 5: atoms.splitter.NamedDomainKey
	(*DomainKeyName)(nil),         // 6: atoms.splitter.DomainKeyName
	(*QualifiedDomainKey)(nil),    // 7: atoms.splitter.QualifiedDomainKey
	(*Shard)(nil),                 // 8: atoms.splitter.Shard
	(*Instance)(nil),              // 9: atoms.splitter.Instance
	(*Grant)(nil),                 // 10: atoms.splitter.Grant
	(*pb.Instance)(nil),           // 11: atoms.splitter.lib.service.location.Instance
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_atoms_splitter_model_proto_depIdxs = []int32{
	2,  // 0: atoms.splitter.QualifiedDomainName.service:type_name -> atoms.splitter.QualifiedServiceName
	4,  // 1: atoms.splitter.NamedDomainKey.key:type_name -> atoms.splitter.DomainKey
	3,  // 2: atoms.splitter.QualifiedDomainKey.domain:type_name -> atoms.splitter.QualifiedDomainName
	4,  // 3: atoms.splitter.QualifiedDomainKey.key:type_name -> atoms.splitter.DomainKey
	3,  // 4: atoms.splitter.Shard.domain:type_name -> atoms.splitter.QualifiedDomainName
	0,  // 5: atoms.splitter.Shard.type:type_name -> atoms.splitter.DomainType
	11, // 6: atoms.splitter.Instance.instance:type_name -> atoms.splitter.lib.service.location.Instance
	8,  // 7: atoms.splitter.Grant.shard:type_name -> atoms.splitter.Shard
	1,  // 8: atoms.splitter.Grant.state:type_name -> atoms.splitter.GrantState
	12, // 9: atoms.splitter.Grant.lease:type_name -> google.protobuf.Timestamp
	12, // 10: atoms.splitter.Grant.assigned:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_atoms_splitter_model_proto_init() }
func file_atoms_splitter_model_proto_init() {
	if File_atoms_splitter_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_model_proto_rawDesc), len(file_atoms_splitter_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_model_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_model_proto_depIdxs,
		EnumInfos:         file_atoms_splitter_model_proto_enumTypes,
		MessageInfos:      file_atoms_splitter_model_proto_msgTypes,
	}.Build()
	File_atoms_splitter_model_proto = out.File
	file_atoms_splitter_model_proto_goTypes = nil
	file_atoms_splitter_model_proto_depIdxs = nil
}
