// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/placement.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Distribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Splits        []*Distribution_Split  `protobuf:"bytes,2,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	mi := &file_atoms_splitter_placement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placement_proto_rawDescGZIP(), []int{0}
}

func (x *Distribution) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Distribution) GetSplits() []*Distribution_Split {
	if x != nil {
		return x.Splits
	}
	return nil
}

type QualifiedPlacementName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifiedPlacementName) Reset() {
	*x = QualifiedPlacementName{}
	mi := &file_atoms_splitter_placement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifiedPlacementName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifiedPlacementName) ProtoMessage() {}

func (x *QualifiedPlacementName) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifiedPlacementName.ProtoReflect.Descriptor instead.
func (*QualifiedPlacementName) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placement_proto_rawDescGZIP(), []int{1}
}

func (x *QualifiedPlacementName) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *QualifiedPlacementName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Placement struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Current       *Distribution           `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_atoms_splitter_placement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placement_proto_rawDescGZIP(), []int{2}
}

func (x *Placement) GetName() *QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Placement) GetCurrent() *Distribution {
	if x != nil {
		return x.Current
	}
	return nil
}

type PlacementInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placement     *Placement             `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementInfo) Reset() {
	*x = PlacementInfo{}
	mi := &file_atoms_splitter_placement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementInfo) ProtoMessage() {}

func (x *PlacementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementInfo.ProtoReflect.Descriptor instead.
func (*PlacementInfo) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placement_proto_rawDescGZIP(), []int{3}
}

func (x *PlacementInfo) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *PlacementInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PlacementInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Distribution_Split struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution_Split) Reset() {
	*x = Distribution_Split{}
	mi := &file_atoms_splitter_placement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_Split) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_Split) ProtoMessage() {}

func (x *Distribution_Split) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_Split.ProtoReflect.Descriptor instead.
func (*Distribution_Split) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placement_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Distribution_Split) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Distribution_Split) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_atoms_splitter_placement_proto protoreflect.FileDescriptor

const file_atoms_splitter_placement_proto_rawDesc = "" +
	"\n" +
	"\x1eatoms/splitter/placement.proto\x12\x0eatoms.splitter\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\fDistribution\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12:\n" +
	"\x06splits\x18\x02 \x03(\v2\".atoms.splitter.Distribution.SplitR\x06splits\x1a1\n" +
	"\x05Split\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"D\n" +
	"\x16QualifiedPlacementName\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x7f\n" +
	"\tPlacement\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\x126\n" +
	"\acurrent\x18\x02 \x01(\v2\x1c.atoms.splitter.DistributionR\acurrent\"\x9c\x01\n" +
	"\rPlacementInfo\x127\n" +
	"\tplacement\x18\x01 \x01(\v2\x19.atoms.splitter.PlacementR\tplacement\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB1\n" +
	"\x14co.atoms.splitter.pbP\x01Z\x17go.atoms.co/splitter/pbb\x06proto3"

var (
	file_atoms_splitter_placement_proto_rawDescOnce sync.Once
	file_atoms_splitter_placement_proto_rawDescData []byte
)

func file_atoms_splitter_placement_proto_rawDescGZIP() []byte {
	file_atoms_splitter_placement_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_placement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_placement_proto_rawDesc), len(file_atoms_splitter_placement_proto_rawDesc)))
	})
	return file_atoms_splitter_placement_proto_rawDescData
}

var file_atoms_splitter_placement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_atoms_splitter_placement_proto_goTypes = []any{
	(*Distribution)(nil),           // 0: atoms.splitter.Distribution
	(*QualifiedPlacementName)(nil), // 1: atoms.splitter.QualifiedPlacementName
	(*Placement)(nil),              // 2: atoms.splitter.Placement
	(*PlacementInfo)(nil),          // 3: atoms.splitter.PlacementInfo
	(*Distribution_Split)(nil),     // 4: atoms.splitter.Distribution.Split
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_atoms_splitter_placement_proto_depIdxs = []int32{
	4, // 0: atoms.splitter.Distribution.splits:type_name -> atoms.splitter.Distribution.Split
	1, // 1: atoms.splitter.Placement.name:type_name -> atoms.splitter.QualifiedPlacementName
	0, // 2: atoms.splitter.Placement.current:type_name -> atoms.splitter.Distribution
	2, // 3: atoms.splitter.PlacementInfo.placement:type_name -> atoms.splitter.Placement
	5, // 4: atoms.splitter.PlacementInfo.timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_atoms_splitter_placement_proto_init() }
func file_atoms_splitter_placement_proto_init() {
	if File_atoms_splitter_placement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_placement_proto_rawDesc), len(file_atoms_splitter_placement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_placement_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_placement_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_placement_proto_msgTypes,
	}.Build()
	File_atoms_splitter_placement_proto = out.File
	file_atoms_splitter_placement_proto_goTypes = nil
	file_atoms_splitter_placement_proto_depIdxs = nil
}
