// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/placementapi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPlacementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlacementsRequest) Reset() {
	*x = ListPlacementsRequest{}
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlacementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlacementsRequest) ProtoMessage() {}

func (x *ListPlacementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlacementsRequest.ProtoReflect.Descriptor instead.
func (*ListPlacementsRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placementapi_proto_rawDescGZIP(), []int{0}
}

func (x *ListPlacementsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListPlacementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*PlacementInfo       `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlacementsResponse) Reset() {
	*x = ListPlacementsResponse{}
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlacementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlacementsResponse) ProtoMessage() {}

func (x *ListPlacementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlacementsResponse.ProtoReflect.Descriptor instead.
func (*ListPlacementsResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placementapi_proto_rawDescGZIP(), []int{1}
}

func (x *ListPlacementsResponse) GetInfo() []*PlacementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type InfoPlacementRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *QualifiedPlacementName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoPlacementRequest) Reset() {
	*x = InfoPlacementRequest{}
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoPlacementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPlacementRequest) ProtoMessage() {}

func (x *InfoPlacementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPlacementRequest.ProtoReflect.Descriptor instead.
func (*InfoPlacementRequest) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placementapi_proto_rawDescGZIP(), []int{2}
}

func (x *InfoPlacementRequest) GetName() *QualifiedPlacementName {
	if x != nil {
		return x.Name
	}
	return nil
}

type InfoPlacementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PlacementInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoPlacementResponse) Reset() {
	*x = InfoPlacementResponse{}
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoPlacementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPlacementResponse) ProtoMessage() {}

func (x *InfoPlacementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_placementapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPlacementResponse.ProtoReflect.Descriptor instead.
func (*InfoPlacementResponse) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_placementapi_proto_rawDescGZIP(), []int{3}
}

func (x *InfoPlacementResponse) GetInfo() *PlacementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_atoms_splitter_placementapi_proto protoreflect.FileDescriptor

const file_atoms_splitter_placementapi_proto_rawDesc = "" +
	"\n" +
	"!atoms/splitter/placementapi.proto\x12\x0eatoms.splitter\x1a\x1eatoms/splitter/placement.proto\"/\n" +
	"\x15ListPlacementsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"K\n" +
	"\x16ListPlacementsResponse\x121\n" +
	"\x04info\x18\x01 \x03(\v2\x1d.atoms.splitter.PlacementInfoR\x04info\"R\n" +
	"\x14InfoPlacementRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\v2&.atoms.splitter.QualifiedPlacementNameR\x04name\"J\n" +
	"\x15InfoPlacementResponse\x121\n" +
	"\x04info\x18\x01 \x01(\v2\x1d.atoms.splitter.PlacementInfoR\x04info2\xbe\x01\n" +
	"\x10PlacementService\x12U\n" +
	"\x04List\x12%.atoms.splitter.ListPlacementsRequest\x1a&.atoms.splitter.ListPlacementsResponse\x12S\n" +
	"\x04Info\x12$.atoms.splitter.InfoPlacementRequest\x1a%.atoms.splitter.InfoPlacementResponseB1\n" +
	"\x14co.atoms.splitter.pbP\x01Z\x17go.atoms.co/splitter/pbb\x06proto3"

var (
	file_atoms_splitter_placementapi_proto_rawDescOnce sync.Once
	file_atoms_splitter_placementapi_proto_rawDescData []byte
)

func file_atoms_splitter_placementapi_proto_rawDescGZIP() []byte {
	file_atoms_splitter_placementapi_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_placementapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_placementapi_proto_rawDesc), len(file_atoms_splitter_placementapi_proto_rawDesc)))
	})
	return file_atoms_splitter_placementapi_proto_rawDescData
}

var file_atoms_splitter_placementapi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_atoms_splitter_placementapi_proto_goTypes = []any{
	(*ListPlacementsRequest)(nil),  // 0: atoms.splitter.ListPlacementsRequest
	(*ListPlacementsResponse)(nil), // 1: atoms.splitter.ListPlacementsResponse
	(*InfoPlacementRequest)(nil),   // 2: atoms.splitter.InfoPlacementRequest
	(*InfoPlacementResponse)(nil),  // 3: atoms.splitter.InfoPlacementResponse
	(*PlacementInfo)(nil),          // 4: atoms.splitter.PlacementInfo
	(*QualifiedPlacementName)(nil), // 5: atoms.splitter.QualifiedPlacementName
}
var file_atoms_splitter_placementapi_proto_depIdxs = []int32{
	4, // 0: atoms.splitter.ListPlacementsResponse.info:type_name -> atoms.splitter.PlacementInfo
	5, // 1: atoms.splitter.InfoPlacementRequest.name:type_name -> atoms.splitter.QualifiedPlacementName
	4, // 2: atoms.splitter.InfoPlacementResponse.info:type_name -> atoms.splitter.PlacementInfo
	0, // 3: atoms.splitter.PlacementService.List:input_type -> atoms.splitter.ListPlacementsRequest
	2, // 4: atoms.splitter.PlacementService.Info:input_type -> atoms.splitter.InfoPlacementRequest
	1, // 5: atoms.splitter.PlacementService.List:output_type -> atoms.splitter.ListPlacementsResponse
	3, // 6: atoms.splitter.PlacementService.Info:output_type -> atoms.splitter.InfoPlacementResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_atoms_splitter_placementapi_proto_init() }
func file_atoms_splitter_placementapi_proto_init() {
	if File_atoms_splitter_placementapi_proto != nil {
		return
	}
	file_atoms_splitter_placement_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_placementapi_proto_rawDesc), len(file_atoms_splitter_placementapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoms_splitter_placementapi_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_placementapi_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_placementapi_proto_msgTypes,
	}.Build()
	File_atoms_splitter_placementapi_proto = out.File
	file_atoms_splitter_placementapi_proto_goTypes = nil
	file_atoms_splitter_placementapi_proto_depIdxs = nil
}
