// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: atoms/splitter/lib/service/session/session.proto

package pb

import (
	pb "go.atoms.co/splitter/lib/service/location/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*Message_Establish_
	//	*Message_Established_
	//	*Message_Heartbeat_
	//	*Message_Ack
	//	*Message_Closed_
	Request       isMessage_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRequest() isMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Message) GetEstablish() *Message_Establish {
	if x != nil {
		if x, ok := x.Request.(*Message_Establish_); ok {
			return x.Establish
		}
	}
	return nil
}

func (x *Message) GetEstablished() *Message_Established {
	if x != nil {
		if x, ok := x.Request.(*Message_Established_); ok {
			return x.Established
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Message_Heartbeat {
	if x != nil {
		if x, ok := x.Request.(*Message_Heartbeat_); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Message) GetAck() *Message_HeartbeatAck {
	if x != nil {
		if x, ok := x.Request.(*Message_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Message) GetClosed() *Message_Closed {
	if x != nil {
		if x, ok := x.Request.(*Message_Closed_); ok {
			return x.Closed
		}
	}
	return nil
}

type isMessage_Request interface {
	isMessage_Request()
}

type Message_Establish_ struct {
	Establish *Message_Establish `protobuf:"bytes,1,opt,name=establish,proto3,oneof"`
}

type Message_Established_ struct {
	Established *Message_Established `protobuf:"bytes,4,opt,name=established,proto3,oneof"`
}

type Message_Heartbeat_ struct {
	Heartbeat *Message_Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Message_HeartbeatAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type Message_Closed_ struct {
	Closed *Message_Closed `protobuf:"bytes,5,opt,name=closed,proto3,oneof"`
}

func (*Message_Establish_) isMessage_Request() {}

func (*Message_Established_) isMessage_Request() {}

func (*Message_Heartbeat_) isMessage_Request() {}

func (*Message_Ack) isMessage_Request() {}

func (*Message_Closed_) isMessage_Request() {}

type Message_Establish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *pb.Instance           `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Establish) Reset() {
	*x = Message_Establish{}
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Establish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Establish) ProtoMessage() {}

func (x *Message_Establish) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Establish.ProtoReflect.Descriptor instead.
func (*Message_Establish) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Establish) GetClient() *pb.Instance {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Message_Establish) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Message_Established struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Server        *pb.Instance           `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Established) Reset() {
	*x = Message_Established{}
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Established) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Established) ProtoMessage() {}

func (x *Message_Established) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Established.ProtoReflect.Descriptor instead.
func (*Message_Established) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Established) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Message_Established) GetServer() *pb.Instance {
	if x != nil {
		return x.Server
	}
	return nil
}

type Message_Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Now           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Heartbeat) Reset() {
	*x = Message_Heartbeat{}
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Heartbeat) ProtoMessage() {}

func (x *Message_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Heartbeat.ProtoReflect.Descriptor instead.
func (*Message_Heartbeat) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_Heartbeat) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

type Message_HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_HeartbeatAck) Reset() {
	*x = Message_HeartbeatAck{}
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_HeartbeatAck) ProtoMessage() {}

func (x *Message_HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_HeartbeatAck.ProtoReflect.Descriptor instead.
func (*Message_HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Message_HeartbeatAck) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Message_Closed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Closed) Reset() {
	*x = Message_Closed{}
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Closed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Closed) ProtoMessage() {}

func (x *Message_Closed) ProtoReflect() protoreflect.Message {
	mi := &file_atoms_splitter_lib_service_session_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Closed.ProtoReflect.Descriptor instead.
func (*Message_Closed) Descriptor() ([]byte, []int) {
	return file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Message_Closed) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_atoms_splitter_lib_service_session_session_proto protoreflect.FileDescriptor

const file_atoms_splitter_lib_service_session_session_proto_rawDesc = "" +
	"\n" +
	"0atoms/splitter/lib/service/session/session.proto\x12\"atoms.splitter.lib.service.service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2atoms/splitter/lib/service/location/location.proto\"\xbd\x06\n" +
	"\aMessage\x12U\n" +
	"\testablish\x18\x01 \x01(\v25.atoms.splitter.lib.service.service.Message.EstablishH\x00R\testablish\x12[\n" +
	"\vestablished\x18\x04 \x01(\v27.atoms.splitter.lib.service.service.Message.EstablishedH\x00R\vestablished\x12U\n" +
	"\theartbeat\x18\x03 \x01(\v25.atoms.splitter.lib.service.service.Message.HeartbeatH\x00R\theartbeat\x12L\n" +
	"\x03ack\x18\x02 \x01(\v28.atoms.splitter.lib.service.service.Message.HeartbeatAckH\x00R\x03ack\x12L\n" +
	"\x06closed\x18\x05 \x01(\v22.atoms.splitter.lib.service.service.Message.ClosedH\x00R\x06closed\x1ab\n" +
	"\tEstablish\x12E\n" +
	"\x06client\x18\x01 \x01(\v2-.atoms.splitter.lib.service.location.InstanceR\x06client\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x1a\x82\x01\n" +
	"\vEstablished\x12,\n" +
	"\x03ttl\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttl\x12E\n" +
	"\x06server\x18\x02 \x01(\v2-.atoms.splitter.lib.service.location.InstanceR\x06server\x1a9\n" +
	"\tHeartbeat\x12,\n" +
	"\x03now\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\x1a<\n" +
	"\fHeartbeatAck\x12,\n" +
	"\x03ttl\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttl\x1a\x1e\n" +
	"\x06Closed\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\t\n" +
	"\arequestB/P\x01Z+go.atoms.co/splitter/lib/service/session/pbb\x06proto3"

var (
	file_atoms_splitter_lib_service_session_session_proto_rawDescOnce sync.Once
	file_atoms_splitter_lib_service_session_session_proto_rawDescData []byte
)

func file_atoms_splitter_lib_service_session_session_proto_rawDescGZIP() []byte {
	file_atoms_splitter_lib_service_session_session_proto_rawDescOnce.Do(func() {
		file_atoms_splitter_lib_service_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoms_splitter_lib_service_session_session_proto_rawDesc), len(file_atoms_splitter_lib_service_session_session_proto_rawDesc)))
	})
	return file_atoms_splitter_lib_service_session_session_proto_rawDescData
}

var file_atoms_splitter_lib_service_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_atoms_splitter_lib_service_session_session_proto_goTypes = []any{
	(*Message)(nil),               // 0: atoms.splitter.lib.service.service.Message
	(*Message_Establish)(nil),     // 1: atoms.splitter.lib.service.service.Message.Establish
	(*Message_Established)(nil),   // 2: atoms.splitter.lib.service.service.Message.Established
	(*Message_Heartbeat)(nil),     // 3: atoms.splitter.lib.service.service.Message.Heartbeat
	(*Message_HeartbeatAck)(nil),  // 4: atoms.splitter.lib.service.service.Message.HeartbeatAck
	(*Message_Closed)(nil),        // 5: atoms.splitter.lib.service.service.Message.Closed
	(*pb.Instance)(nil),           // 6: atoms.splitter.lib.service.location.Instance
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_atoms_splitter_lib_service_session_session_proto_depIdxs = []int32{
	1,  // 0: atoms.splitter.lib.service.service.Message.establish:type_name -> atoms.splitter.lib.service.service.Message.Establish
	2,  // 1: atoms.splitter.lib.service.service.Message.established:type_name -> atoms.splitter.lib.service.service.Message.Established
	3,  // 2: atoms.splitter.lib.service.service.Message.heartbeat:type_name -> atoms.splitter.lib.service.service.Message.Heartbeat
	4,  // 3: atoms.splitter.lib.service.service.Message.ack:type_name -> atoms.splitter.lib.service.service.Message.HeartbeatAck
	5,  // 4: atoms.splitter.lib.service.service.Message.closed:type_name -> atoms.splitter.lib.service.service.Message.Closed
	6,  // 5: atoms.splitter.lib.service.service.Message.Establish.client:type_name -> atoms.splitter.lib.service.location.Instance
	7,  // 6: atoms.splitter.lib.service.service.Message.Established.ttl:type_name -> google.protobuf.Timestamp
	6,  // 7: atoms.splitter.lib.service.service.Message.Established.server:type_name -> atoms.splitter.lib.service.location.Instance
	7,  // 8: atoms.splitter.lib.service.service.Message.Heartbeat.now:type_name -> google.protobuf.Timestamp
	7,  // 9: atoms.splitter.lib.service.service.Message.HeartbeatAck.ttl:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_atoms_splitter_lib_service_session_session_proto_init() }
func file_atoms_splitter_lib_service_session_session_proto_init() {
	if File_atoms_splitter_lib_service_session_session_proto != nil {
		return
	}
	file_atoms_splitter_lib_service_session_session_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Establish_)(nil),
		(*Message_Established_)(nil),
		(*Message_Heartbeat_)(nil),
		(*Message_Ack)(nil),
		(*Message_Closed_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoms_splitter_lib_service_session_session_proto_rawDesc), len(file_atoms_splitter_lib_service_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atoms_splitter_lib_service_session_session_proto_goTypes,
		DependencyIndexes: file_atoms_splitter_lib_service_session_session_proto_depIdxs,
		MessageInfos:      file_atoms_splitter_lib_service_session_session_proto_msgTypes,
	}.Build()
	File_atoms_splitter_lib_service_session_session_proto = out.File
	file_atoms_splitter_lib_service_session_session_proto_goTypes = nil
	file_atoms_splitter_lib_service_session_session_proto_depIdxs = nil
}
